### ISSUE TITLE
panic: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by alexdulin** [hashicorp/consul#10636]
#### Overview of the Issue

We have been observing occasional panics after upgrading to Consul 1.10.0. In particular, it seems to happen only on machines that are also running multiple Envoy docker containers (>30 containers). Machines with few Envoy docker containers (<10) do not seem to crash.

#### Reproduction Steps

Not certain. The crashes have been occurring in a cluster of 40+ agents, 5 servers, all running Consul 1.10.0 and Nomad 1.1.2, Envoy 1.18.3. It does not happen consistently and I cannot pinpoint a single event that triggers it

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 140
	services = 102
build:
	prerelease = 
	revision = 27de64da
	version = 1.10.0
consul:
	acl = enabled
	known_servers = 5
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 2505
	max_procs = 8
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 235
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 10
	member_time = 647589
	members = 58
	query_queue = 0
	query_time = 119
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 2
build:
	prerelease = 
	revision = db839f18
	version = 1.10.1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = [REDACTED]
	server = true
raft:
	applied_index = 460524857
	commit_index = 460524857
	fsm_pending = 0
	last_contact = 1.937988ms
	last_log_index = 460524857
	last_log_term = 1971
	last_snapshot_index = 460511579
	last_snapshot_term = 1971
	latest_configuration = [REDACTED]
	latest_configuration_index = 0
	num_peers = 4
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1971
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 1841
	max_procs = 4
	os = linux
	version = go1.16.6
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 235
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 647589
	members = 48
	query_queue = 0
	query_time = 119
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 185419
	members = 11
	query_queue = 0
	query_time = 119
```

</details>

### Operating system and Environment details

`uname -a`
```
Linux [REDACTED] 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

Here is the panic log. Its really long.
[crash.log](https://github.com/hashicorp/consul/files/6835124/crash.log)

**Comment by dnephin** [comment]
Thank you for reporting this problem!

I'm going to copy out the relevant part of the crash log here to make it easier to find in search
```
fatal error: concurrent map writes
goroutine 3862534 [running]:
runtime.throw(0x2ffd4d5, 0x15)
#011/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc003077548 sp=0xc003077518 pc=0x4385d2
runtime.mapdelete_faststr(0x2961fe0, 0xc00441ed80, 0x2fdd688, 0xc)
#011/usr/local/go/src/runtime/map_faststr.go:382 +0x3a8 fp=0xc0030775b0 sp=0xc003077548 pc=0x414c68
github.com/hashicorp/consul/agent.mergeServiceConfig(0xc001cdea50, 0xc003c6e180, 0x14, 0x1, 0xc002f1a210)
#011/home/circleci/project/consul/agent/service_manager.go:403 +0x9ce fp=0xc003077c68 sp=0xc0030775b0 pc=0x2524b4e
github.com/hashicorp/consul/agent.(*serviceConfigWatch).handleUpdate(0xc005719c20, 0x34a5558, 0xc004d9eb40, 0xc0040c07f8, 0x14, 0x2d701a0, 0xc001cdea50, 0x0, 0x0, 0x488de5d, ...)
#011/home/circleci/project/consul/agent/service_manager.go:279 +0x197 fp=0xc003077e48 sp=0xc003077c68 pc=0x2523877
github.com/hashicorp/consul/agent.(*serviceConfigWatch).runWatch(0xc005719c20, 0x34a5558, 0xc004d9eb40, 0xc000bb3b70, 0xc0018872c0)
#011/home/circleci/project/consul/agent/service_manager.go:246 +0x212 fp=0xc003077fb8 sp=0xc003077e48 pc=0x2523592
```

It looks like the changes in #9872 (and #9873) [modify a map](https://github.com/hashicorp/consul/blob/v1.10.0/agent/service_manager.go#L403) returned from the `agent/cache`. When multiple services receive updates at the same time, there's a chance they both try to modify the same map causing this panic.
