### ISSUE TITLE
Consul cluster enteres infinite rebooting (panic) loop 

### ISSUE THREAD

**Issue by nierob** [hashicorp/consul#12258]
#### Overview of the Issue

We encountered case in which a nomad job triggered consul to restart in an infinite loop. After which it was hard to revert to "workable" state. Reverting the job change was not helpful, stopping / restarting the whole cluster either. In general we were forced to reconstruct the cluster from scratch (drop consul data) to recover.  

The job that triggered the issue, was changing nginx based load balancer to ingress gateway. Below there is minimized version of it:
```hcl
  group "load-balancer" {
    constraint {
      attribute = "${attr.unique.hostname}"
      value = "example.com"
    }

    service {
      name = "service-name"
      tags = ["core", "http"]
      port = "http"

      connect {
        gateway {
          proxy {}
          ingress {
            listener {
              port     = 5080
              protocol = "tcp"
              service {
                name = "service-name-api"
              }
            }
          }
        }
      }
    }

    network {
      mode ="bridge"
      port "http" {
        static = 5080
        host_network = "localhost"
      }
    }
  }
```
`localhost` host_network is just a `lo` interface.

Essentially the issue reduces to the panic below:

```
Feb 03 13:18:02 consul[1888392]: panic: assignment to entry in nil map
Feb 03 13:18:02 consul[1888392]: goroutine 85 [running]:
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/state.updateMeshTopology({0x30bcf00, 0xc0015edd10}, 0x29c, {0xc002d80d60, 0xf}, 0xc001740480, {0x2adfec0, 0xc001c78c40})
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/state/catalog.go:3917 +0x7cd
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/state.ensureServiceTxn({0x30bcf00, 0xc0015edd10}, 0x29c, {0xc002d80d60, 0xf}, 0x0, 0xc001740480)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/state/catalog.go:762 +0x43c
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/state.(*Store).ensureRegistrationTxn(0xc001870e80, {0x30bcf00, 0xc0015edd10}, 0xc00297a3c0, 0x0, 0xc00297a3c0, 0x0)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/state/catalog.go:214 +0x690
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/state.(*Store).EnsureRegistration(0xc00186be00, 0x6e4, 0x6e4)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/state/catalog.go:124 +0xaf
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/fsm.(*FSM).applyRegister(0xc000dda120, {0xc00027d101, 0x6e4, 0x6e4}, 0xc0005dbb86)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/fsm/commands_oss.go:144 +0x1a5
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/fsm.NewFromDeps.func1({0xc00027d101, 0xc00182fa40, 0x203000}, 0x203000)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/fsm/fsm.go:99 +0x36
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/consul/agent/consul/fsm.(*FSM).Apply(0xc000dda120, 0xc0019abc20)
Feb 03 13:18:02 consul[1888392]:         /home/runner/work/consul/consul/agent/consul/fsm/fsm.go:133 +0x16c
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/go-raftchunking.(*ChunkingFSM).Apply(0xc00164f8c0, 0x0)
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/go-raftchunking@v0.6.1/fsm.go:66 +0x254
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0017f8110)
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.3/fsm.go:90 +0x235
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/raft.(*Raft).runFSM.func2({0xc00168f200, 0x40, 0xc00186bf50})
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.3/fsm.go:113 +0x48f
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/raft.(*Raft).runFSM(0xc00183f180)
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.3/fsm.go:216 +0x35a
Feb 03 13:18:02 consul[1888392]: github.com/hashicorp/raft.(*raftState).goFunc.func1()
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.3/state.go:146 +0x62
Feb 03 13:18:02 consul[1888392]: created by github.com/hashicorp/raft.(*raftState).goFunc
Feb 03 13:18:02 consul[1888392]:         /home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.3/state.go:144 +0x92
Feb 03 13:18:02 systemd[1]: consul.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 03 13:18:02 systemd[1]: consul.service: Failed with result 'exit-code'.
Feb 03 13:18:02 systemd[1]: consul.service: Scheduled restart job, restart counter is at 18.
Feb 03 13:18:02 systemd[1]: Stopped "HashiCorp Consul - A service mesh solution".
Feb 03 13:18:02 systemd[1]: Started "HashiCorp Consul - A service mesh solution".
Feb 03 13:18:03 consul[1888481]: ==> Starting Consul agent...
Feb 03 13:18:03 consul[1888481]:            Version: '1.11.2'
```

The failure was reproducible by re-applying the job again.

### Consul info for both Client and Server
Running on Ubuntu, software installed from deb packages.
```
build:
        prerelease = 
        revision = 37c7d06b
        version = 1.11.2
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 838
        max_procs = 16
        os = linux
        version = go1.17.5
```

**Comment by dnephin** [comment]
Thank you for the bug report! I was able to reproduce the problem and I've opened a PR to fix it in #12277
