### ISSUE TITLE
Envoys 'delayed_close_timeout' & http health checks with `Connection: close`

### ISSUE THREAD

**Issue by ahjohannessen** [hashicorp/consul#12969]
I am using consul connect and expose some paths for http healthchecks. The connection from envoy to my app is consistently ended prematurely. I think it is due to consul setting `Connection: close` and envoy starting a close timer with `delayed_close_timeout` of 1 second. 

This results in the connection to my application is ended prematurely and results in an error.

My application complains about this :

```
org.http4s.ember.core.EmberException$EmptyStream: Cannot Parse Empty Stream
	at org.http4s.ember.core.EmberException$EmptyStream$.apply(EmberException.scala:46)
	at org.http4s.ember.core.Parser$MessageP$.recurseFind$$anonfun$1$$anonfun$1(Parser.scala:50)
	at main$ @ ss.Daemon$.main(Daemon.scala:35)
	at get @ fs2.concurrent.Channel$$anon$1.consumeLoop$$anonfun$1$$anonfun$2(Channel.scala:239)
```

Envoy is logging the following in trace mode, you can see that envoy logs this: `setting delayed close timer with timeout 1000 ms`.

I think this is similar what is mentioned here: https://github.com/projectcontour/contour/issues/3285

```
[2022-05-07 15:10:03.153][15][debug][conn_handler] [source/server/active_tcp_listener.cc:142] [C2526] new connection from 192.168.20.27:59016
[2022-05-07 15:10:03.153][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2526] socket event: 2
[2022-05-07 15:10:03.153][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2526] write ready
[2022-05-07 15:10:03.154][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2526] socket event: 3
[2022-05-07 15:10:03.154][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2526] write ready
[2022-05-07 15:10:03.154][15][trace][connection] [source/common/network/connection_impl.cc:603] [C2526] read ready. dispatch_buffered_data=0
[2022-05-07 15:10:03.154][15][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C2526] read returns: 164
[2022-05-07 15:10:03.154][15][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C2526] read error: Resource temporarily unavailable
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:579] [C2526] parsing 164 bytes
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:865] [C2526] message begin
[2022-05-07 15:10:03.154][15][debug][http] [source/common/http/conn_manager_impl.cc:299] [C2526] new stream
[2022-05-07 15:10:03.154][15][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x160a7f33bf80 for 300000ms, min is 300000ms
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2526] completed header: key=Host value=192.168.20.27:20719
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2526] completed header: key=User-Agent value=Consul Health Check
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2526] completed header: key=Accept value=text/plain, text/*, */*
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2526] completed header: key=Accept-Encoding value=gzip
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:716] [C2526] onHeadersCompleteBase
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2526] completed header: key=Connection value=close
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:1053] [C2526] Server: onHeadersComplete size=5
[2022-05-07 15:10:03.154][15][trace][http] [source/common/http/http1/codec_impl.cc:843] [C2526] message complete
[2022-05-07 15:10:03.154][15][debug][http] [source/common/http/conn_manager_impl.cc:904] [C2526][S17812563202329495644] request headers complete (end_stream=true):
':authority', '192.168.20.27:20719'
':path', '/health/live'
':method', 'GET'
'user-agent', 'Consul Health Check'
'accept', 'text/plain, text/*, */*'
'accept-encoding', 'gzip'
'connection', 'close'

[2022-05-07 15:10:03.154][15][debug][http] [source/common/http/filter_manager.cc:850] [C2526][S17812563202329495644] request end stream
[2022-05-07 15:10:03.154][15][debug][connection] [./source/common/network/connection_impl.h:89] [C2526] current connecting state: false
[2022-05-07 15:10:03.154][15][debug][router] [source/common/router/router.cc:470] [C2526][S17812563202329495644] cluster 'local_app' match for URL '/health/live'
[2022-05-07 15:10:03.154][15][debug][router] [source/common/router/router.cc:673] [C2526][S17812563202329495644] router decoding headers:
':authority', '192.168.20.27:20719'
':path', '/health/live'
':method', 'GET'
':scheme', 'http'
'user-agent', 'Consul Health Check'
'accept', 'text/plain, text/*, */*'
'accept-encoding', 'gzip'
'x-forwarded-proto', 'http'
'x-request-id', '2ae891fe-a093-49d8-9433-66aef4e3713d'
'x-envoy-expected-rq-timeout-ms', '15000'

[2022-05-07 15:10:03.154][15][debug][pool] [source/common/http/conn_pool_base.cc:76] queueing stream due to no available connections
[2022-05-07 15:10:03.154][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:268] trying to create new connection
[2022-05-07 15:10:03.154][15][trace][pool] [source/common/conn_pool/conn_pool_base.cc:269] ConnPoolImplBase 0x160a7f2cb900, ready_clients_.size(): 0, busy_clients_.size(): 0, connecting_clients_.size(): 0, connecting_stream_capacity_: 0, num_active_streams_: 0, pending_streams_.size(): 1 per upstream preconnect ratio: 1
[2022-05-07 15:10:03.154][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:145] creating a new connection
[2022-05-07 15:10:03.155][15][debug][connection] [./source/common/network/connection_impl.h:89] [C2527] current connecting state: true
[2022-05-07 15:10:03.155][15][debug][client] [source/common/http/codec_client.cc:57] [C2527] connecting
[2022-05-07 15:10:03.155][15][debug][connection] [source/common/network/connection_impl.cc:912] [C2527] connecting to 127.0.0.1:8080
[2022-05-07 15:10:03.155][15][debug][connection] [source/common/network/connection_impl.cc:931] [C2527] connection in progress
[2022-05-07 15:10:03.155][15][trace][pool] [source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
[2022-05-07 15:10:03.155][15][trace][http] [source/common/http/filter_manager.cc:562] [C2526][S17812563202329495644] decode headers called: filter=0x160a7f0505b0 status=1
[2022-05-07 15:10:03.155][15][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x160a7f33bf80 for 300000ms, min is 300000ms
[2022-05-07 15:10:03.155][15][trace][http] [source/common/http/http1/codec_impl.cc:629] [C2526] parsed 164 bytes
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2527] socket event: 2
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2527] write ready
[2022-05-07 15:10:03.155][15][debug][connection] [source/common/network/connection_impl.cc:683] [C2527] connected
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:418] [C2527] raising connection event 2
[2022-05-07 15:10:03.155][15][debug][client] [source/common/http/codec_client.cc:89] [C2527] connected
[2022-05-07 15:10:03.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:305] [C2527] attaching to next stream
[2022-05-07 15:10:03.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:177] [C2527] creating stream
[2022-05-07 15:10:03.155][15][debug][router] [source/common/router/upstream_request.cc:420] [C2526][S17812563202329495644] pool ready
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:478] [C2527] writing 261 bytes, end_stream false
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2527] write ready
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/raw_buffer_socket.cc:67] [C2527] write returns: 261
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2527] socket event: 2
[2022-05-07 15:10:03.155][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2527] write ready
[2022-05-07 15:10:03.158][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2527] socket event: 3
[2022-05-07 15:10:03.158][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2527] write ready
[2022-05-07 15:10:03.158][15][trace][connection] [source/common/network/connection_impl.cc:603] [C2527] read ready. dispatch_buffered_data=0
[2022-05-07 15:10:03.158][15][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C2527] read returns: 99
[2022-05-07 15:10:03.158][15][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C2527] read error: Resource temporarily unavailable
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:579] [C2527] parsing 99 bytes
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:865] [C2527] message begin
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2527] completed header: key=Date value=Sat, 07 May 2022 15:10:03 GMT
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2527] completed header: key=Connection value=keep-alive
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:716] [C2527] onHeadersCompleteBase
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:492] [C2527] completed header: key=Content-Length value=0
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:1315] [C2527] status_code 200
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:1325] [C2527] Client: onHeadersComplete size=3
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:843] [C2527] message complete
[2022-05-07 15:10:03.158][15][trace][http] [source/common/http/http1/codec_impl.cc:1396] [C2527] message complete
[2022-05-07 15:10:03.158][15][debug][client] [source/common/http/codec_client.cc:126] [C2527] response complete
[2022-05-07 15:10:03.158][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=1)
[2022-05-07 15:10:03.158][15][debug][router] [source/common/router/router.cc:1331] [C2526][S17812563202329495644] upstream headers complete: end_stream=true
[2022-05-07 15:10:03.159][15][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x160a7f33bf80 for 300000ms, min is 300000ms
[2022-05-07 15:10:03.159][15][debug][http] [source/common/http/conn_manager_impl.cc:1461] [C2526][S17812563202329495644] closing connection due to connection close header
[2022-05-07 15:10:03.159][15][debug][http] [source/common/http/conn_manager_impl.cc:1516] [C2526][S17812563202329495644] encoding headers via codec (end_stream=true):
':status', '200'
'date', 'Sat, 07 May 2022 15:10:03 GMT'
'content-length', '0'
'x-envoy-upstream-service-time', '3'
'server', 'envoy'
'connection', 'close'

[2022-05-07 15:10:03.159][15][trace][connection] [source/common/network/connection_impl.cc:478] [C2526] writing 143 bytes, end_stream false
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=2)
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=3)
[2022-05-07 15:10:03.159][15][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x160a7f25c800 for 3600000ms, min is 3600000ms
[2022-05-07 15:10:03.159][15][debug][connection] [source/common/network/connection_impl.cc:139] [C2526] closing data_to_write=143 type=0
[2022-05-07 15:10:03.159][15][debug][connection] [source/common/network/connection_impl_base.cc:47] [C2526] setting delayed close timer with timeout 1000 ms
[2022-05-07 15:10:03.159][15][debug][pool] [source/common/http/http1/conn_pool.cc:53] [C2527] response complete
[2022-05-07 15:10:03.159][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:210] [C2527] destroying stream: 0 remaining
[2022-05-07 15:10:03.159][15][trace][http] [source/common/http/http1/codec_impl.cc:629] [C2527] parsed 99 bytes
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:125] clearing deferred deletion list (size=3)
[2022-05-07 15:10:03.159][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2526] socket event: 2
[2022-05-07 15:10:03.159][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2526] write ready
[2022-05-07 15:10:03.159][15][trace][connection] [source/common/network/raw_buffer_socket.cc:67] [C2526] write returns: 143
[2022-05-07 15:10:03.159][15][debug][connection] [source/common/network/connection_impl.cc:716] [C2526] write flush complete
[2022-05-07 15:10:03.159][15][debug][connection] [source/common/network/connection_impl.cc:250] [C2526] closing socket: 1
[2022-05-07 15:10:03.159][15][trace][connection] [source/common/network/connection_impl.cc:418] [C2526] raising connection event 1
[2022-05-07 15:10:03.159][15][trace][conn_handler] [source/server/active_stream_listener_base.cc:111] [C2526] connection on event 1
[2022-05-07 15:10:03.159][15][debug][conn_handler] [source/server/active_stream_listener_base.cc:120] [C2526] adding to cleanup list
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=1)
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=2)
[2022-05-07 15:10:03.159][15][trace][main] [source/common/event/dispatcher_impl.cc:125] clearing deferred deletion list (size=2)
[2022-05-07 15:10:03.659][15][trace][connection] [source/common/network/connection_impl.cc:563] [C2527] socket event: 3
[2022-05-07 15:10:03.659][15][trace][connection] [source/common/network/connection_impl.cc:674] [C2527] write ready
[2022-05-07 15:10:03.659][15][trace][connection] [source/common/network/connection_impl.cc:603] [C2527] read ready. dispatch_buffered_data=0
[2022-05-07 15:10:03.659][15][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C2527] read returns: 0
[2022-05-07 15:10:03.659][15][debug][connection] [source/common/network/connection_impl.cc:651] [C2527] remote close
[2022-05-07 15:10:03.659][15][debug][connection] [source/common/network/connection_impl.cc:250] [C2527] closing socket: 0
[2022-05-07 15:10:03.660][15][trace][connection] [source/common/network/connection_impl.cc:418] [C2527] raising connection event 0
[2022-05-07 15:10:03.660][15][debug][client] [source/common/http/codec_client.cc:107] [C2527] disconnect. resetting 0 pending requests
[2022-05-07 15:10:03.660][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:439] [C2527] client disconnected, failure reason: 
[2022-05-07 15:10:03.660][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=1)
[2022-05-07 15:10:03.660][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:410] invoking idle callbacks - is_draining_for_deletion_=false
[2022-05-07 15:10:03.660][15][trace][upstream] [source/common/upstream/cluster_manager_impl.cc:1723] Erasing idle pool for host 0x160a7f80e920
[2022-05-07 15:10:03.660][15][trace][main] [source/common/event/dispatcher_impl.cc:249] item added to deferred deletion list (size=2)
[2022-05-07 15:10:03.660][15][trace][upstream] [source/common/upstream/cluster_manager_impl.cc:1730] Pool container empty for host 0x160a7f80e920, erasing host entry
[2022-05-07 15:10:03.660][15][trace][main] [source/common/event/dispatcher_impl.cc:125] clearing deferred deletion list (size=2)
```

**Comment by ahjohannessen** [comment]
I think I have solved my particular issue by setting protocol to http2 inside the proxy stanza:

```
config {
    protocol = "http2"
}
```

**Comment by blake** [comment]
Hi @ahjohannessen, I'm glad to hear that this change resolved the issue for you.

I just wanted to point out that you should instead set the protocol via [service-defaults](https://www.consul.io/docs/connect/config-entries/service-defaults#default-protocol) configuration entry so that downstream proxies use the same protocol when communicating to the upstream.

**Comment by ahjohannessen** [comment]
@blake That would indeed be better, I need to figure out how to do that via Nomad
