### ISSUE TITLE
OOM when doing huge recursive KV deletes

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1421]
I was doing some stress testing using the official 0.6.0-rc1 build on three m3.large machines, deleting 2M KV entries with a single recursive delete call and sometimes saw kernel OOMs or Go runtime panics due to memory issues. Here's a log from one of the panics:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xd7f9a0, 0x16)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc81c724000, 0x28000, 0xc891680000, 0x110bf98)
        /usr/local/go/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_MapBits(0x10ebfe0, 0xc891b80000)
        /usr/local/go/src/runtime/mbitmap.go:144 +0xcc
runtime.mHeap_SysAlloc(0x10ebfe0, 0x500000, 0xc826309e00)
        /usr/local/go/src/runtime/malloc.go:424 +0x186
runtime.mHeap_Grow(0x10ebfe0, 0x280, 0x0)
        /usr/local/go/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x10ebfe0, 0x280, 0x100)
        /usr/local/go/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x10ebfe0, 0x280, 0x100000000, 0xc800000001)
        /usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0xc82ede3ee0)
        /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x10ebfe0, 0x280, 0x10100000000, 0x41679f)
        /usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x500000, 0x7f1700000000, 0x3)
        /usr/local/go/src/runtime/malloc.go:745 +0xb3
runtime.mallocgc.func3()
        /usr/local/go/src/runtime/malloc.go:634 +0x33
runtime.systemstack(0xc82001a000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 26 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc8201ca820 sp=0xc8201ca818
runtime.mallocgc(0x500000, 0xbf8fa0, 0x0, 0x7f176259d000)
        /usr/local/go/src/runtime/malloc.go:635 +0x9c4 fp=0xc8201ca8f0 sp=0xc8201ca820
runtime.newarray(0xbf8fa0, 0x10000, 0xc840c83b40)
        /usr/local/go/src/runtime/malloc.go:777 +0xc9 fp=0xc8201ca930 sp=0xc8201ca8f0
runtime.hashGrow(0xa81440, 0xc8872eb710)
        /usr/local/go/src/runtime/hashmap.go:761 +0x82 fp=0xc8201ca960 sp=0xc8201ca930
runtime.mapassign1(0xa81440, 0xc8872eb710, 0xc8201caa50, 0xc8201caa48)
        /usr/local/go/src/runtime/hashmap.go:481 +0x55b fp=0xc8201caa08 sp=0xc8201ca960
github.com/hashicorp/go-immutable-radix.(*Txn).writeNode(0xc876fc16c0, 0xc840c83a40, 0xd)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:75 +0x39a fp=0xc8201caaa8 sp=0xc8201caa08
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc840c83a40, 0xc8489d3580, 0x19, 0x20, 0xc8489d3593, 0x6, 0xd, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:131 +0x734 fp=0xc8201cac00 sp=0xc8201caaa8
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc840c82d40, 0xc8489d3580, 0x19, 0x20, 0xc8489d3593, 0x6, 0xd, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201cad58 sp=0xc8201cac00
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc85ec6ab40, 0xc8489d3580, 0x19, 0x20, 0xc8489d3591, 0x8, 0xf, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201caeb0 sp=0xc8201cad58
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc844399c40, 0xc8489d3580, 0x19, 0x20, 0xc8489d3590, 0x9, 0x10, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201cb008 sp=0xc8201caeb0
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc85087b940, 0xc8489d3580, 0x19, 0x20, 0xc8489d358f, 0xa, 0x11, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201cb160 sp=0xc8201cb008
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc8714cf300, 0xc8489d3580, 0x19, 0x20, 0xc8489d358e, 0xb, 0x12, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201cb2b8 sp=0xc8201cb160
github.com/hashicorp/go-immutable-radix.(*Txn).insert(0xc876fc16c0, 0xc8714cee40, 0xc8489d3580, 0x19, 0x20, 0xc8489d358d, 0xc, 0x13, 0xa4f080, 0xc8489d3500, ...)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:121 +0x5c6 fp=0xc8201cb410 sp=0xc8201cb2b8
github.com/hashicorp/go-immutable-radix.(*Txn).Insert(0xc876fc16c0, 0xc8489d3580, 0x19, 0x20, 0xa4f080, 0xc8489d3500, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/go-immutable-radix/iradix.go:223 +0x9b fp=0xc8201cb4a0 sp=0xc8201cb410
github.com/hashicorp/go-memdb.(*Txn).Insert(0xc8714ced40, 0xd05e50, 0xa, 0xa4f080, 0xc8489d3500, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/go-memdb/txn.go:197 +0xe56 fp=0xc8201cb6a8 sp=0xc8201cb4a0
github.com/hashicorp/consul/consul/state.(*Graveyard).InsertTxn(0xc82011c158, 0xc8714ced40, 0xc86b100040, 0x18, 0x1f0786, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/state/graveyard.go:31 +0xc2 fp=0xc8201cb778 sp=0xc8201cb6a8
github.com/hashicorp/consul/consul/state.(*StateStore).KVSDeleteTree(0xc82019f8c0, 0x1f0786, 0xc8870e8100, 0x5, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/state/state_store.go:1730 +0x3a3 fp=0xc8201cb928 sp=0xc8201cb778
github.com/hashicorp/consul/consul.(*consulFSM).applyKVSOperation(0xc8201bd880, 0xc88e703781, 0x7f, 0x7f, 0x1f0786, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/fsm.go:165 +0xe0d fp=0xc8201cbaa0 sp=0xc8201cb928
github.com/hashicorp/consul/consul.(*consulFSM).Apply(0xc8201bd880, 0xc8714cea40, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/fsm.go:85 +0x20b fp=0xc8201cbb78 sp=0xc8201cbaa0
github.com/hashicorp/raft.(*Raft).runFSM(0xc82014c1c0)
        /opt/gopath/src/github.com/hashicorp/raft/raft.go:564 +0xe9c fp=0xc8201cbf60 sp=0xc8201cbb78
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /opt/gopath/src/github.com/hashicorp/raft/raft.go:253 +0x20 fp=0xc8201cbf70 sp=0xc8201cbf60
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82014c1c0, 0xc82017b7b0)
        /opt/gopath/src/github.com/hashicorp/raft/state.go:152 +0x44 fp=0xc8201cbf90 sp=0xc8201cbf70
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201cbf98 sp=0xc8201cbf90
created by github.com/hashicorp/raft.(*raftState).goFunc
        /opt/gopath/src/github.com/hashicorp/raft/state.go:153 +0x4d

...snipped
```

**Comment by slackpad** [comment]
This should be mitigated once we have a nicer solution for huge deletes.
