### ISSUE TITLE
Track down consul lock failure in leader/serf...

### ISSUE THREAD

**Issue by sean-** [hashicorp/consul#1899]
I've never seen this before, but don't want to loose sight of it.

```
=== RUN   TestLockCommand_MonitorRetry_Lock_Default
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x23a3c2]

goroutine 981 [running]:
panic(0x6e35c0, 0xc820010190)
        /Users/sean/go-devel/src/runtime/panic.go:500 +0x18e
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Serf).UserEvent(0x0, 0x819b8a, 0x11, 0xc82015a7f8, 0x7, 0x8, 0x0, 0x50, 0x74b520)
        /Users/sean/go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/serf.go:441 +0x132
github.com/hashicorp/consul/consul.(*Server).leaderLoop(0xc820cc4180, 0xc820484ea0)
        /Users/sean/go/src/github.com/hashicorp/consul/consul/leader.go:59 +0xed
created by github.com/hashicorp/consul/consul.(*Server).monitorLeadership
        /Users/sean/go/src/github.com/hashicorp/consul/consul/leader.go:38 +0x172
exit status 2
FAIL    github.com/hashicorp/consul/command     3.043s
```

**Comment by slackpad** [comment]
I recall a related change that might have fixed this but can't seem to find it - will track it down.

**Comment by slackpad** [comment]
There was an issue with delegates in https://github.com/hashicorp/memberlist/pull/57 but that doesn't look like this. Moving this one forward.
