### ISSUE TITLE
Track down TestCheckMonitor_Passing failure

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2044]
```
goroutine 3325 [running]:
runtime.throw(0xbdcf20, 0x21)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820052eb8 sp=0xc820052ea0
runtime.mapaccess2(0x84b4c0, 0xc8202821e0, 0xc82022ee10, 0x1, 0x84da40)
        /usr/local/go/src/runtime/hashmap.go:343 +0x5a fp=0xc820052f00 sp=0xc820052eb8
reflect.mapaccess(0x84b4c0, 0xc8202821e0, 0xc82022ee10, 0xc8202821e0)
        /usr/local/go/src/runtime/hashmap.go:993 +0x35 fp=0xc820052f30 sp=0xc820052f00
reflect.Value.MapIndex(0x84b4c0, 0xc8202821e0, 0x15, 0x84da40, 0xc82022ee10, 0x98, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:1041 +0x14a fp=0xc820052fb8 sp=0xc820052f30
fmt.(*pp).printReflectValue(0xc8200c6000, 0x84b4c0, 0xc8202821e0, 0x15, 0x76, 0x0, 0x4700)
        /usr/local/go/src/fmt/print.go:904 +0x2887 fp=0xc820053770 sp=0xc820052fb8
fmt.(*pp).printArg(0xc8200c6000, 0x84b4c0, 0xc8202821e0, 0x76, 0x0, 0x0)
        /usr/local/go/src/fmt/print.go:810 +0x540 fp=0xc8200538f8 sp=0xc820053770
fmt.(*pp).doPrintf(0xc8200c6000, 0xbd12a0, 0x18, 0xc820053d98, 0x1, 0x1)
        /usr/local/go/src/fmt/print.go:1238 +0x1dcd fp=0xc820053c80 sp=0xc8200538f8
fmt.Sprintf(0xbd12a0, 0x18, 0xc820053d98, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/fmt/print.go:203 +0x6f fp=0xc820053cd0 sp=0xc820053c80
fmt.Errorf(0xbd12a0, 0x18, 0xc820053d98, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/fmt/print.go:212 +0x65 fp=0xc820053d38 sp=0xc820053cd0
github.com/hashicorp/consul/command/agent.expectStatus.func1(0x989680, 0x0, 0x0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:56 +0x13f fp=0xc820053e18 sp=0xc820053d38
github.com/hashicorp/consul/testutil.WaitForResult(0xc8204181c0, 0xc820053f10)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/testutil/wait.go:19 +0x4f fp=0xc820053e50 sp=0xc820053e18
github.com/hashicorp/consul/command/agent.expectStatus(0xc82038c000, 0xaf7c40, 0x6, 0xafa4a8, 0x7)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:66 +0x3fb fp=0xc820053f28 sp=0xc820053e50
github.com/hashicorp/consul/command/agent.TestCheckMonitor_Passing(0xc82038c000)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:70 +0x4b fp=0xc820053f58 sp=0xc820053f28
testing.tRunner(0xc82038c000, 0x1023328)
        /usr/local/go/src/testing/testing.go:473 +0x98 fp=0xc820053f90 sp=0xc820053f58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820053f98 sp=0xc820053f90
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0x892
```

**Comment by slackpad** [comment]
We've changed a lot since we first saw this (Go runtime, Consul changes) and haven't seen this again. Closing and we will re-open if it surfaces.
