### ISSUE TITLE
Panic in discovery.(*V1DataFetcher).buildResultsFromServiceNodes

### ISSUE THREAD

**Issue by jameshartig** [hashicorp/consul#21556]
#### Overview of the Issue

We saw the following panic running v1.19.0:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x26b8c47]
goroutine 54702258 [running]:
github.com/hashicorp/consul/agent/discovery.(*V1DataFetcher).buildResultsFromServiceNodes(0xc0013650e0, {0xc001f3ea00, 0x2, 0xc001fe4fc0?}, 0x0?, 0xc001cc4234)
/builds/levenlabs/infrastructure/consul/consul/agent/discovery/query_fetcher_v1.go:451 +0x127
github.com/hashicorp/consul/agent/discovery.(*V1DataFetcher).FetchPreparedQuery(0xc0013650e0, {{0x0?, 0xc002006c10?}}, 0xc002038c10)
/builds/levenlabs/infrastructure/consul/consul/agent/discovery/query_fetcher_v1.go:380 +0x476
github.com/hashicorp/consul/agent/discovery.(*QueryProcessor).QueryByName(0xc00136fa50, 0xc002038c00, {{0x0?, 0xc0025cd860?}})
/builds/levenlabs/infrastructure/consul/consul/agent/discovery/discovery.go:241 +0x357
github.com/hashicorp/consul/agent/dns.discoveryResultsFetcher.getQueryResults({}, 0xc002123c58)
/builds/levenlabs/infrastructure/consul/consul/agent/dns/discovery_results_fetcher.go:68 +0x32a
github.com/hashicorp/consul/agent/dns.(*Router).handleRequestRecursively(0xc0006d7440, 0xc0015eecf0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0xc000953c00, {0x5461568, ...}, ...)
/builds/levenlabs/infrastructure/consul/consul/agent/dns/router.go:231 +0x657
github.com/hashicorp/consul/agent/dns.(*Router).HandleRequest(0xc0006d7440, 0xc0015eecf0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0x5461568, 0xc0025cd860})
/builds/levenlabs/infrastructure/consul/consul/agent/dns/router.go:188 +0x42a
consul-agent.service: main process exited, code=exited, status=2/INVALIDARGUMENT
github.com/hashicorp/consul/agent/dns.(*Router).ServeDNS(0xc0006d7440, {0x5490570, 0xc001811600}, 0xc0015eecf0)
/builds/levenlabs/infrastructure/consul/consul/agent/dns/router.go:315 +0x53
github.com/miekg/dns.(*Server).serveDNS(0xc0006186c0, {0xc0017f6000, 0x38, 0xffff}, 0xc001811600)
/go/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:659 +0x42a
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0006186c0, 0xc000e42460, {0xc0017f6000, 0x38, 0xffff}, {0x548b810, 0xc0006cece8}, 0xc0024c22e0, {0x0, 0x0})
/go/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:603 +0x1a5
created by github.com/miekg/dns.(*Server).serveUDP in goroutine 59
/go/pkg/mod/github.com/miekg/dns@v1.1.50/server.go:533 +0x405
```

I'm a bit confused by the stacktrace because that line is:
https://github.com/hashicorp/consul/blob/bf0166d85082f384a94c5c0e6227619e63f3c644/agent/discovery/query_fetcher_v1.go#L451

Which could mean that `Service *NodeService` is nil but that would mean that there would've been a nil pointer dereference on one of the lines above. Maybe `makeTaggedAddressesFromServiceAddresses` was being inlined but then I don't see anything in that function that could cause a nil pointer deference either. It could be that the line numbers are subtly wrong but the `query_fetcher_v1.go:380` before it is spot on...

---

#### Reproduction Steps

I'm not sure how the bug was caused but I assume it was caused by some sort of prepared query over a DNS request. We are doing 20k DNS requests per second and we've only seen this once so I would imagine it's some sort of race condition otherwise we'd be seeing it a lot more frequently.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 26
        checks = 31
        services = 26
build:
        prerelease =
        revision = bf0166d+
        version = 1.19.0
        version_metadata =
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 118
        max_procs = 2
        os = linux
        version = go1.22.4
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 88
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1140641
        members = 25
        query_queue = 0
        query_time = 1
```

```
{
  "advertise_addr": "{{ GetInterfaceIP \"eth0\" }}",
  "advertise_reconnect_timeout": "15m",
  "alt_domain": "consul",
  "bind_addr": "0.0.0.0",
  "client_addr": "0.0.0.0",
  "data_dir": "/var/lib/consul/data",
  "datacenter": "gce-asia-east1",
  "dns_config": {
    "cache_max_age": "1s",
    "enable_additional_node_meta_txt": false,
    "enable_truncate": true,
    "use_cache": true
  },
  "domain": "admiral",
  "enable_agent_tls_for_checks": true,
  "enable_debug": true,
  "encrypt": "...",
  "node_name": "backend-stable-asia-east1-test-xt78",
  "ports": {
    "https": 8501
  },
  "recursors": [
    "169.254.169.254"
  ],
  "rejoin_after_leave": true,
  "retry_join": [
    "10.140.0.70"
  ],
  "telemetry": {
    "disable_hostname": true,
    "prometheus_retention_time": "5m"
  },
  "tls": {
    "defaults": {
      "ca_path": "/opt/cacerts",
      "cert_file": "/etc/consul/tls/consul.pem",
      "key_file": "/etc/consul/tls/consul-key.pem",
      "verify_outgoing": true
    },
    "internal_rpc": {
      "verify_incoming": true,
      "verify_server_hostname": true
    }
  }
}
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 8
        checks = 9
        services = 8
build:
        prerelease =
        revision = bf0166d+
        version = 1.19.0
        version_metadata =
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 6
        leader = true
        leader_addr = 10.140.0.61:8300
        server = true
raft:
        applied_index = 127373390
        commit_index = 127373390
        fsm_pending = 0
        last_contact = 0
        last_log_index = 127373390
        last_log_term = 2615
        last_snapshot_index = 127359762
        last_snapshot_term = 2615
        latest_configuration = [{Suffrage:Voter ID:0ab4e772-af8c-5732-1113-afd93b35bdfa Address:10.140.0.5:8300} {Suffrage:Voter ID:a95a79ce-db91-5919-45a1-6b3c895da1ea Address:10.140.0.32:8300} {Suffrage:Voter ID:7855c15c-f435-95a1-7590-0239de148024 Address:10.140.0.61:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2615
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 706
        max_procs = 2
        os = linux
        version = go1.22.4
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 88
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1140641
        members = 25
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 53857
        members = 18
        query_queue = 0
        query_time = 1
```

```
{                                                                                                                                                         
  "advertise_addr": "{{ GetInterfaceIP \"eth0\" }}",
  "alt_domain": "consul",
  "bind_addr": "0.0.0.0",
  "bootstrap_expect": 3,
  "client_addr": "0.0.0.0",
  "data_dir": "/var/lib/consul/data",
  "datacenter": "gce-asia-east1",
  "dns_config": {
    "cache_max_age": "1s",
    "enable_additional_node_meta_txt": false,
    "enable_truncate": true,
    "use_cache": true
  },
  "domain": "admiral",
  "enable_agent_tls_for_checks": true,
  "enable_debug": true,
  "encrypt": "...",
  "leave_on_terminate": true,
  "node_name": "consul-20240708-asia-east1-l5s9",
  "performance": {
    "raft_multiplier": 1
  },
  "ports": {
    "https": 8501
  },
  "reconnect_timeout": "24h",
  "reconnect_timeout_wan": "24h",
  "recursors": [
    "169.254.169.254"
  ],
  "rejoin_after_leave": true,
  "retry_join": [
    "10.140.0.70"
  ],
  "retry_join_wan": [
    "10.142.0.44",
    "10.138.0.107",
    "10.128.0.133",
    "10.132.0.3",
    "10.140.0.70",
    "10.142.0.15"
  ],
  "server": true,
  "skip_leave_on_interrupt": true,
  "telemetry": {
    "disable_hostname": true,
    "prometheus_retention_time": "5m"
  },
  "tls": {
    "defaults": {
      "ca_path": "/opt/cacerts",
      "cert_file": "/etc/consul/tls/consul.pem",
      "key_file": "/etc/consul/tls/consul-key.pem",
      "verify_outgoing": true
    },
    "internal_rpc": {
      "verify_incoming": true,
      "verify_server_hostname": true
    }
  },
  "ui_config": {
    "enabled": true
  }
}
```

</details>

**Comment by jmurret** [comment]
This is resolved with https://github.com/hashicorp/consul/pull/21598 which reverts the experimental v2 dns and will be available in 1.19.2.
