### ISSUE TITLE
Consul server crashed on macOS Sierra

### ISSUE THREAD

**Issue by lowzj** [hashicorp/consul#2407]
### `consul version`

Server:  `v0.7.0`
### `consul info`

Server:

```
agent:
    check_monitors = 0
    check_ttls = 2
    checks = 2
    services = 3
build:
    prerelease = 
    revision = 'a189091
    version = 0.7.0
consul:
    bootstrap = true
    known_datacenters = 1
    leader = false
    leader_addr = 
    server = true
raft:
    applied_index = 0
    commit_index = 0
    fsm_pending = 0
    last_contact = never
    last_log_index = 8
    last_log_term = 2
    last_snapshot_index = 0
    last_snapshot_term = 0
    latest_configuration = [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
    latest_configuration_index = 1
    num_peers = 0
    protocol_version = 1
    protocol_version_max = 3
    protocol_version_min = 0
    snapshot_version_max = 1
    snapshot_version_min = 0
    state = Follower
    term = 2
runtime:
    arch = amd64
    cpu_count = 4
    goroutines = 57
    max_procs = 4
    os = darwin
    version = go1.6.3
serf_lan:
    encrypted = false
    event_queue = 0
    event_time = 3
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1
serf_wan:
    encrypted = false
    event_queue = 0
    event_time = 1
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1
```
### Operating system and Environment details

OS: `macOS Sierra 10.12`
Go version: `go version go1.7.1 darwin/amd64`
consul start command:

```
consul agent -server -bootstrap-expect 1 -data-dir /tmp/a/consul -ui-dir /tmp/consul_ui -log-level=trace -client=127.0.0.1 -bind=127.0.0.1 >> /tmp/consul.log 2>&1
```
### Description of the Issue (and unexpected/desired result)

I upgrade macOS to `10.12(Sierra)`, then the consul server crashed frequently every serval minutes, both consul `0.6.4`, `0.7.0`.
### Log Fragments

Server: [consul.log](https://gist.github.com/lowzj/71ce67c981873a380a1cea742d86c2ad)

**Comment by lowzj** [comment]
It may be caused by the unmatched `go` version. It's `go1.6.3` in `consul info` output, not `go1.7.1` I installed.
I use brew to re-install consul, and the go version in `consul info` output is `go1.7.1`. It seems ok now.

**Comment by tbaeg** [comment]
Looks as though the brew package was updated with `go1.7.1` but the download from `https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_darwin_amd64.zip` has not yet been updated. Update to this would be great.

**Comment by slackpad** [comment]
Consul won't care which version of Go is installed, but we will build the next release of Consul with Go 1.7.1, which had some MacOS X Sierra-related fixes. There were some issues upgrading Go, we are working through those here - https://github.com/hashicorp/consul/pull/2281.

**Comment by nugend** [comment]
I saw a few crashes using the binaries distributed from the Consul download page.

**Comment by nugend** [comment]
Version: Consul v0.7.0
Info: 

```
agent:
check_monitors = 0
check_ttls = 1
checks = 1
services = 2
build:
prerelease =
revision = 'a189091
version = 0.7.0
consul:
bootstrap = false
known_datacenters = 1
leader = true
leader_addr = 127.0.0.1:8300
server = true
raft:
applied_index = 9
commit_index = 9
fsm_pending = 0
last_contact = never
last_log_index = 9
last_log_term = 2
last_snapshot_index = 0
last_snapshot_term = 0
latest_configuration = [{Suffrage:Voter ID:127.0.0.1:8300 Address:127.0.0.1:8300}]
latest_configuration_index = 1
num_peers = 0
protocol_version = 1
protocol_version_max = 3
protocol_version_min = 0
snapshot_version_max = 1
snapshot_version_min = 0
state = Leader
term = 2
runtime:
arch = amd64
cpu_count = 4
goroutines = 53
max_procs = 4
os = darwin
version = go1.6.3
serf_lan:
encrypted = false
event_queue = 1
event_time = 2
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 1
members = 1
query_queue = 0
query_time = 1
serf_wan:
encrypted = false
event_queue = 0
event_time = 1
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 1
members = 1
query_queue = 0
query_time = 1
[]'
```

**Comment by charliestrawn** [comment]
FYI Looks like the fix was back-ported to Go 1.6.3 https://golang.org/doc/devel/release.html#go1.6 binaries compiled with 1.6.3 should work fine on Sierra

**Comment by slackpad** [comment]
@charliestrawn that's a good point. Consul 0.7.0 was built with Go 1.6.3, so there must be some other issue with Sierra.

**Comment by charliestrawn** [comment]
@slackpad potentially, I've been running 0.7.0 with Sierra for a while now and not had problems. Just wanted to post for posterity. If I can help out any further let me know. It might help if @nugend posted the output of `go env`

**Comment by nugend** [comment]
I don't have go installed. I could get that, but would it be pertinent?

**Comment by slackpad** [comment]
> I don't have go installed. I could get that, but would it be pertinent?

@nugend shouldn't matter - consul is shipped as a static binary and doesn't depend on the Go tools being installed.

**Comment by nugend** [comment]
So it *would* be beneficial to debugging the crash if I installed go and relayed `go env` or it wouldn't be beneficial? Sorry, I am dense.

**Comment by magiconair** [comment]
I can recreate this for 0.7.0 with the following steps:

```
./consul agent -server -bootstrap-expect 1 -advertise 127.0.0.1 -data-dir data -ui-dir ui -log-level=debug
```

then access the UI with `http://localhost:8500/ui` and boom:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4604fad00e15 pc=0x16c9e0]

goroutine 83 [running]:
runtime.throw(0xb9f1e0, 0x2a)
	/goroot/src/runtime/panic.go:547 +0x90 fp=0xc8202f5288 sp=0xc8202f5270
runtime.sigpanic()
	/goroot/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8202f52d8 sp=0xc8202f5288
sync.(*Pool).Get(0xf679e0, 0x0, 0x0)
	/goroot/src/sync/pool.go:102 +0x40 fp=0xc8202f5328 sp=0xc8202f52d8
fmt.newPrinter(0x10)
	/goroot/src/fmt/print.go:133 +0x27 fp=0xc8202f5368 sp=0xc8202f5328
fmt.Sprintf(0xa69618, 0x4, 0xc8202f5438, 0x2, 0x2, 0x0, 0x0)
	/goroot/src/fmt/print.go:202 +0x2b fp=0xc8202f53b8 sp=0xc8202f5368
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*PrefixedUi).Info(0xc82013f030, 0xc820318cb0, 0x6c)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/ui.go:167 +0x191 fp=0xc8202f5460 sp=0xc8202f53b8
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*UiWriter).Write(0xc82013b340, 0xc8201de540, 0x6c, 0x70, 0x6d, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/ui_writer.go:16 +0xd5 fp=0xc8202f54a8 sp=0xc8202f5460
github.com/hashicorp/consul/command/agent.(*GatedWriter).Write(0xc820019090, 0xc8201de540, 0x6d, 0x70, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/gated_writer.go:36 +0x112 fp=0xc8202f5568 sp=0xc8202f54a8
github.com/hashicorp/consul/vendor/github.com/hashicorp/logutils.(*LevelFilter).Write(0xc8200190e0, 0xc8201de540, 0x6d, 0x70, 0xc820189ec0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/logutils/level.go:63 +0xbc fp=0xc8202f55b8 sp=0xc8202f5568
io.(*multiWriter).Write(0xc820146fa0, 0xc8201de540, 0x6d, 0x70, 0xf74b20, 0x0, 0x0)
	/goroot/src/io/multi.go:43 +0xda fp=0xc8202f5648 sp=0xc8202f55b8
log.(*Logger).Output(0xc820286190, 0x2, 0xc820189ec0, 0x58, 0x0, 0x0)
	/goroot/src/log/log.go:166 +0x37a fp=0xc8202f5720 sp=0xc8202f5648
log.(*Logger).Printf(0xc820286190, 0xb80fe0, 0x28, 0xc8202f5800, 0x4, 0x4)
	/goroot/src/log/log.go:173 +0x7e fp=0xc8202f5770 sp=0xc8202f5720
github.com/hashicorp/consul/command/agent.(*HTTPServer).wrap.func1.1(0xc8202861e0, 0xc8202dd340, 0xc82018b440, 0x12, 0xecf9d0e40, 0xc059360, 0xf74b20)
	/gopath/src/github.com/hashicorp/consul/command/agent/http.go:367 +0x2c2 fp=0xc8202f5848 sp=0xc8202f5770
github.com/hashicorp/consul/command/agent.(*HTTPServer).wrap.func1(0x116a298, 0xc820316dd0, 0xc8202dd340)
	/gopath/src/github.com/hashicorp/consul/command/agent/http.go:396 +0xb19 fp=0xc8202f5a40 sp=0xc8202f5848
github.com/hashicorp/consul/command/agent.(*HTTPServer).handleFuncMetrics.func1(0x116a298, 0xc820316dd0, 0xc8202dd340)
	/gopath/src/github.com/hashicorp/consul/command/agent/http.go:218 +0x81 fp=0xc8202f5af8 sp=0xc8202f5a40
net/http.HandlerFunc.ServeHTTP(0xc8202196e0, 0x116a298, 0xc820316dd0, 0xc8202dd340)
	/goroot/src/net/http/server.go:1618 +0x3a fp=0xc8202f5b18 sp=0xc8202f5af8
net/http.(*ServeMux).ServeHTTP(0xc820219320, 0x116a298, 0xc820316dd0, 0xc8202dd340)
	/goroot/src/net/http/server.go:1910 +0x17d fp=0xc8202f5b70 sp=0xc8202f5b18
net/http.serverHandler.ServeHTTP(0xc8202a0100, 0x116a298, 0xc820316dd0, 0xc8202dd340)
	/goroot/src/net/http/server.go:2081 +0x19e fp=0xc8202f5bd0 sp=0xc8202f5b70
net/http.(*conn).serve(0xc820244200)
	/goroot/src/net/http/server.go:1472 +0xf2e fp=0xc8202f5f98 sp=0xc8202f5bd0
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202f5fa0 sp=0xc8202f5f98
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2137 +0x44e
```

This seems to be a go1.6.3 issue but since I can repro this reliably with this code and a stock go1.6.3 binary from golang.org:

```
package main

import "log"

func main() {
	for {
		log.Print("foo")
	}
}
```

```
2016/10/22 10:37:04 foo
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4943cfdb1ec7 pc=0x6f460]

goroutine 1 [running]:
runtime.throw(0x122de0, 0x2a)
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/panic.go:547 +0x90 fp=0xc82003bd60 sp=0xc82003bd48
runtime.sigpanic()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82003bdb0 sp=0xc82003bd60
sync.(*Pool).Get(0x184f40, 0x0, 0x0)
	/Users/frschroeder/Downloads/go1.6.3/src/sync/pool.go:102 +0x40 fp=0xc82003be00 sp=0xc82003bdb0
fmt.newPrinter(0xecf9d1c30)
	/Users/frschroeder/Downloads/go1.6.3/src/fmt/print.go:133 +0x27 fp=0xc82003be40 sp=0xc82003be00
fmt.Sprint(0xc82003bf10, 0x1, 0x1, 0x0, 0x0)
	/Users/frschroeder/Downloads/go1.6.3/src/fmt/print.go:238 +0x28 fp=0xc82003be90 sp=0xc82003be40
log.Print(0xc82003bf10, 0x1, 0x1)
	/Users/frschroeder/Downloads/go1.6.3/src/log/log.go:283 +0x35 fp=0xc82003bed8 sp=0xc82003be90
main.main()
	/Users/frschroeder/gopath/src/frank/repro.go:7 +0xcc fp=0xc82003bf50 sp=0xc82003bed8
runtime.main()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/proc.go:188 +0x2b0 fp=0xc82003bfa0 sp=0xc82003bf50
runtime.goexit()
	/Users/frschroeder/Downloads/go1.6.3/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
exit status 2
```

**Comment by magiconair** [comment]
Filed https://github.com/golang/go/issues/17550. Lets see what happens.

**Comment by magiconair** [comment]
Duplicate of https://github.com/golang/go/issues/16570. go1.7.1 is the first supported version for sierra (https://github.com/golang/go/wiki/Darwin) so building with go1.7.1 should fix this.

**Comment by lowzj** [comment]
My problem has been resolved, and I think this issue can be closed. Thanks!

**Comment by slackpad** [comment]
Thanks @magiconair and @lowzj. We got Go upgraded to 1.7.3 last night via https://github.com/hashicorp/consul/pull/2281 so that should fix this for the next release.

**Comment by Sandmania** [comment]
@slackpad any ETA for the next release?

**Comment by slackpad** [comment]
Shooting for later this week!
