### ISSUE TITLE
Concurrent map write in check unit test

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2603]
```
fatal error: concurrent map read and map write

goroutine 6689 [running]:
runtime.throw(0xbab4c3, 0x21)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420316d80 sp=0xc420316d60
runtime.mapaccess1_faststr(0xa4c600, 0xc420753380, 0xb8698b, 0x3, 0xc291a8)
        /usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc420316de0 sp=0xc420316d80
github.com/hashicorp/consul/command/agent.expectStatus.func1(0x989680, 0x10f1280, 0xc42027efc0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:54 +0x78 fp=0xc420316e80 sp=0xc420316de0
github.com/hashicorp/consul/testutil.WaitForResult(0xc420554580, 0xc420316f20)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/testutil/wait.go:19 +0x57 fp=0xc420316eb8 sp=0xc420316e80
github.com/hashicorp/consul/command/agent.expectStatus(0xc420750000, 0xb891cf, 0x6, 0xb8bba7, 0x8)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:65 +0x33e fp=0xc420316f40 sp=0xc420316eb8
github.com/hashicorp/consul/command/agent.TestCheckMonitor_Critical(0xc420750000)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/check_test.go:77 +0x55 fp=0xc420316f78 sp=0xc420316f40
testing.tRunner(0xc420750000, 0xc26f20)
        /usr/local/go/src/testing/testing.go:610 +0x81 fp=0xc420316fa0 sp=0xc420316f78
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420316fa8 sp=0xc420316fa0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:646 +0x2ec
```

**Comment by slackpad** [comment]
Should be fixed by #2578 (dup of #2269).
