### ISSUE TITLE
Unit test panic in Serf UserEvent handler

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2663]
Caught a few of these running on the dev branch for https://github.com/hashicorp/consul/pull/2661:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2347f9]

goroutine 11491 [running]:
panic(0x660420, 0xc420014100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Serf).UserEvent(0x0, 0x70d035, 0x11, 0xc420a64080, 0xa, 0x10, 0x0, 0x2, 0xc42024f7a0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/serf.go:447 +0x129
github.com/hashicorp/consul/consul.(*Server).leaderLoop(0xc420aaa3c0, 0xc420b618c0)
        github.com/hashicorp/consul/consul/_test/_obj_test/leader.go:69 +0x107
created by github.com/hashicorp/consul/consul.(*Server).monitorLeadership
        github.com/hashicorp/consul/consul/_test/_obj_test/leader.go:43 +0x1d0
FAIL    github.com/hashicorp/consul/consul      105.065s
```

Not very repeatable and doesn't seem related to the change there. I know there was a UserEvent-related fix that went in on the Serf side. Need to chase this down.

**Comment by slackpad** [comment]
Similar to https://github.com/hashicorp/consul/issues/1899.
