### ISSUE TITLE
Consul panic after repeated DNS recursion failure

### ISSUE THREAD

**Issue by payoffstan** [hashicorp/consul#284]
Consul hits a runtime.panic after repeated i/o timeouts on dns recursion. This is on 0.3.1. Here's what the log looks like:

    2014/08/14 01:06:15 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 01:06:16 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 08:40:57 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 08:44:33 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 08:44:34 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 08:54:51 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:03:27 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:13:55 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:37:41 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:41:28 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:43:21 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:43:25 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:53:11 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:53:13 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:53:15 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:53:16 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 09:53:25 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
    2014/08/14 10:00:11 [ERR] dns: recurse failed: read udp 10.10.100.130:53: i/o timeout
panic: runtime error: slice bounds out of range

goroutine 488917 [running]:
runtime.panic(0x9c21a0, 0xf7d40f)
        /opt/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/miekg/dns.unpackStructValue(0x9d8360, 0xc2084f8440, 0x0, 0x196, 0xc208285000, 0x2e3, 0x1000, 0x1b, 0xc200000000, 0x0, ...)
        /opt/gopath/src/github.com/miekg/dns/msg.go:1170 +0x5df4
github.com/miekg/dns.UnpackStruct(0xa1b5a0, 0xc2084f8440, 0xc208285000, 0x2e3, 0x1000, 0x11, 0x17, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/msg.go:1254 +0xc8
github.com/miekg/dns.UnpackRR(0xc208285000, 0x2e3, 0x1000, 0x17, 0x7f12c44e3770, 0xc2084f8440, 0x11, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/msg.go:1331 +0x214
github.com/miekg/dns.(*Msg).Unpack(0xc2080f03f0, 0xc208285000, 0x2e3, 0x1000, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/msg.go:1546 +0x504
github.com/miekg/dns.(*Conn).ReadMsg(0xc2080aee10, 0xc2080f02d0, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/client.go:176 +0x1b6
github.com/miekg/dns.(*Client).exchange(0xc2080aedc0, 0xc2080f02d0, 0xc2080ed000, 0x10, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/client.go:152 +0x388
github.com/miekg/dns.(*Client).Exchange(0xc2080aedc0, 0xc2080f02d0, 0xc2080ed000, 0x10, 0xa45c10, 0x6, 0x0, 0x0)
        /opt/gopath/src/github.com/miekg/dns/client.go:91 +0x88
github.com/hashicorp/consul/command/agent.(*DNSServer).handleRecurse(0xc2081109b0, 0x7f12cb00a4a0, 0xc208ed1bc0, 0xc2080f02d0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/dns.go:571 +0x222
github.com/hashicorp/consul/command/agent.*DNSServer.(github.com/hashicorp/consul/command/agent.handleRecurse)·fm(0x7f12cb00a4a0, 0xc208ed1bc0, 0xc2
080f02d0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/dns.go:79 +0x44
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc2080ed010, 0x7f12cb00a4a0, 0xc208ed1bc0, 0xc2080f02d0)
        /opt/gopath/src/github.com/miekg/dns/server.go:79 +0x40
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc2080ecf70, 0x7f12cb00a4a0, 0xc208ed1bc0, 0xc2080f02d0)
        /opt/gopath/src/github.com/miekg/dns/server.go:176 +0xc9
github.com/miekg/dns.(*Server).serve(0xc20813a9c0, 0x7f12cb008ca0, 0xc208b84f30, 0x7f12cb009320, 0xc2080ecf70, 0xc20822a000, 0x1c, 0xffff, 0xc2080b2018, 0xc208e9a620, ...)
        /opt/gopath/src/github.com/miekg/dns/server.go:330 +0x510
created by github.com/miekg/dns.(*Server).serveUDP
        /opt/gopath/src/github.com/miekg/dns/server.go:299 +0x1fb

**Comment by ryanuber** [comment]
Closing due to inactivity. Please ping us if this comes up again!
