### ISSUE TITLE
Consul 0.8.5 UI Uncaught EmberError when clicking a node on Nodes tab

### ISSUE THREAD

**Issue by nikonyrh** [hashicorp/consul#3233]
### Version info

Consul Docker image from https://hub.docker.com/r/library/consul/:

```
Consul build:
        prerelease =
        revision = 2c77151
        version = 0.8.5
```

Registrator Docker image from gliderlabs/registrator (`registrator --version` = v7).

### Operating system and Environment details
AWS Ubuntu 14.04.5, 3.13.0-108-generic, Docker version 1.13.0, build 49bf474
Docker image startup command: `docker run -e SERVICE_IGNORE=1 -d -h node-name -p 8300-8302:8300-8302/tcp -p 8300-8302:8300-8302/udp -p 8400:8400 -p 8500:8500 consul:0.8.5 agent -server -client 0.0.0.0 -advertise 192.168.3.164 -join 192.168.3.23 -ui`
Browser: Chrome 59.0.3071.115 on Windows 10

### Description of the Issue (and unexpected/desired result)
Unexpected Javascript error on Consul UI's Nodes tab when clicking a node's name, prevents all usage of the tab:

```
application.min.js:120 Uncaught EmberError
description: undefined
fileName: undefined
lineNumber: undefined
message: "<App.NodesShowView:ember996> Handlebars error: Could not find property 'tomographyGraph' on object <App.NodesShowController:ember989>."
name: "Error"
number: undefined
stack: "Error: <App.NodesShowView:ember996> Handlebars error: Could not find property 'tomographyGraph' on object <App.NodesShowController:ember989>.
    at EmberError (http://192.168.3.164:8500/ui/static/application.min.js:123:492)
    at Class.helperMissingHelper (http://192.168.3.164:8500/ui/static/application.min.js:120:17174)
    at Object.eval (eval at createFunctionContext (http://192.168.3.164:8500/ui/static/application.min.js:90:384), <anonymous>:148:287)
    at http://192.168.3.164:8500/ui/static/application.min.js:35:208
    at Class.render (http://192.168.3.164:8500/ui/static/application.min.js:132:22576)
    at Class._renderToBuffer (http://192.168.3.164:8500/ui/static/application.min.js:132:17077)
    at apply (http://192.168.3.164:8500/ui/static/application.min.js:124:23836)
    at Class.superFunction (http://192.168.3.164:8500/ui/static/application.min.js:123:18548)
    at Class._renderToBuffer (http://192.168.3.164:8500/ui/static/application.min.js:132:28592)
    at apply (http://192.168.3.164:8500/ui/static/application.min.js:124:23836)"
```

### Reproduction steps
When going to http://192.168.3.164:8500 I get redirected to `/ui/#/dc1/services`, as it should. I am able to click on services and see on which nodes they are running. Also key/value UI is working as it should. However when I click any node's name I get an exception as shown above.

For some reason this bug did not re-appear when I was upgrading Consul on an other datacenter :o

**Comment by nikonyrh** [comment]
Update: I might have old Javascript cached on my browser, sorry for the misled report.
