### ISSUE TITLE
Cluster lost leadership after adding 3 more servers

### ISSUE THREAD

**Issue by hamstah** [hashicorp/consul#3768]
When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.9.2`
Server: `0/9/2`

### `consul info` for both Client and Server

```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease = 
        revision = 75ca2ca
        version = 0.9.2
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 
        server = true
raft:
        applied_index = 4441401
        commit_index = 4441401
        fsm_pending = 0
        last_contact = 1.723895932s
        last_log_index = 4441403
        last_log_term = 3
        last_snapshot_index = 4438442
        last_snapshot_term = 3
        latest_configuration = [{Suffrage:Voter ID:10.30.87.74:8300 Address:10.30.87.74:8300} {Suffrage:Voter ID:10.30.4.29:8300 Address:10.30.4.29:8300} {Suffrage:Voter ID:10.30.134.219:8300 Address:10.30.134.219:8300} {Suffrage:Vot
er ID:10.30.151.60:8300 Address:10.30.151.60:8300} {Suffrage:Voter ID:10.30.72.85:8300 Address:10.30.72.85:8300} {Suffrage:Voter ID:10.30.4.34:8300 Address:10.30.4.34:8300}]
        latest_configuration_index = 4441402
        num_peers = 5
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 188
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 91
        max_procs = 2
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 33
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 94
        members = 9
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

centos (amazon ami) on aws.

```
{
  "advertise_addr": "10.30.4.29",
  "bootstrap": false,
  "server": true,
  "datacenter": "eu-west-1",
  "data_dir": "/var/consul",
  "log_level": "INFO",
  "bootstrap_expect": 3,
  "enable_syslog": true,
  "start_join": [],
  "retry_join": [
    "provider=aws tag_key=Name tag_value=main-consul-vault"
  ],
  "leave_on_terminate": true,
  "addresses": {
    "http": "0.0.0.0"
  },
  "ports": {
    "http": 8500
  }
}
```

### Description of the Issue (and unexpected/desired result)

Had a stable cluster with 3 servers and 3 separate agents.
Added 3 more servers with aws autoscaling to cycle the instances to bigger sizes.
As the new servers joined the cluster, leadership was lost and it doesn't get resolved.

### Log Fragments or Link to [gist](https://gist.github.com/)

https://gist.githubusercontent.com/hamstah/50b39dc72081d7071e72fbdadf9f58c9/raw/b49be50029670a1c6a3e00f2476644d847136fc2/log

```
$ consul members
Node                                                    Address             Status  Type    Build  Protocol  DC
consul-vault-i-012dde7e69f4f2533.test.paywithcurl.tech  10.30.87.74:8301    alive   server  0.9.2  2         eu-west-1
consul-vault-i-02d23654286345ba7.test.paywithcurl.tech  10.30.4.34:8301     alive   server  0.9.2  2         eu-west-1
consul-vault-i-0349defd933378da1.test.paywithcurl.tech  10.30.134.219:8301  alive   server  0.9.2  2         eu-west-1
consul-vault-i-099d87f78c76c5f95.test.paywithcurl.tech  10.30.72.85:8301    alive   server  0.9.2  2         eu-west-1
consul-vault-i-0d781a5c3f695c4d7.test.paywithcurl.tech  10.30.4.29:8301     alive   server  0.9.2  2         eu-west-1
consul-vault-i-0fd1aa1f84f27a9c5.test.paywithcurl.tech  10.30.151.60:8301   alive   server  0.9.2  2         eu-west-1
ecs-cluster-i-00b7681243f17cece.test.paywithcurl.tech   10.30.10.48:8301    alive   client  0.9.2  2         eu-west-1
ecs-cluster-i-00e26e5a2905614d0.test.paywithcurl.tech   10.30.138.10:8301   alive   client  0.9.2  2         eu-west-1
ecs-cluster-i-0b50e41df7492e851.test.paywithcurl.tech   10.30.82.227:8301   alive   client  0.9.2  2         eu-west-1
```

**Comment by hamstah** [comment]
I've tried restarting the previous leader (10.30.87.74) but it now panics on start
```
==> Starting Consul agent...
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft.NewRaft(0xc4201d6360, 0x1a7d5a0, 0xc42036cb40, 0x1a84200, 0xc42037f880, 0x1a803e0, 0xc420382900, 0x1a7e7a0, 0xc420382a80, 0x1a85700, ...)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft/api.go:491 +0xb0b
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc420242780, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/consul/agent/consul/server.go:633 +0x5e9
github.com/hashicorp/consul/agent/consul.NewServerLogger(0xc4202398c0, 0xc420203ea0, 0xc42016fec0, 0x0, 0x1, 0x2)
        /gopath/src/github.com/hashicorp/consul/agent/consul/server.go:341 +0xd2e
github.com/hashicorp/consul/agent.(*Agent).Start(0xc4201721e0, 0xc4201721e0, 0x0)
        /gopath/src/github.com/hashicorp/consul/agent/agent.go:271 +0x225
github.com/hashicorp/consul/command.(*AgentCommand).run(0xc42023e0f0, 0xc42000e160, 0x2, 0x2, 0x0)
        /gopath/src/github.com/hashicorp/consul/command/agent.go:781 +0x506
github.com/hashicorp/consul/command.(*AgentCommand).Run(0xc42023e0f0, 0xc42000e160, 0x2, 0x2, 0xc4201ffc90)
        /gopath/src/github.com/hashicorp/consul/command/agent.go:728 +0x56
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201d8180, 0xc4201d8180, 0x40, 0xc42022b480)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:160 +0x1cc
main.realMain(0xc420000340)
        /gopath/src/github.com/hashicorp/consul/main.go:50 +0x3fd
main.main()
        /gopath/src/github.com/hashicorp/consul/main.go:19 +0x22
```

This looks like a pretty bad state to get into by only scaling up the number of nodes

**Comment by hamstah** [comment]
I still have 2 of the original 3 nodes running (I've removed the 3 new ones) but I can't do anything with them.

I've tried to force-leave the 3 new nodes and also the one I lost when restarting, the show as `left` when running consul members. The log still refer to them when trying to contact them for a vote. I thought I would try to remove the peers from the raft db, but all the commands fail with an error 500 because of the lack of leader. 

I also can't do a snapshot with the built in command for the same reason. 

Could you please advise how to restore the cluster, the only solution I have now is to rebuild a cluster and copy the data folders (while remembering which state not to copy over like raft) and restore it manually, but I'm hoping there is something more mature than that.

**Comment by slackpad** [comment]
Hi @hamstah sorry you are running into this. It's seems unusual that your last snapshot was from Nov. 3, is there anything in the logs on those existing servers related to writing snapshots?

In any case, if you pass `-stale` to `consul snapshot save` then it will write out the contents from the server you are connected to, even if there's no current leader. You should also be able to use https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json on those two remaining nodes by updating the peers.json to include just them.

**Comment by hamstah** [comment]
Hi James thanks for looking into it.

On  that day in November I had to rescue the cluster from someone deleting
the ec2 instances of the cluster. I recreated a cluster from the data in an
ebs volume.

I had to do some surgery as the nodes ip and hostname had changed.

That worked fine until the 28th of Dec when I added more servers. But I
guess something was wrong with it somewhere. I have snapshots I created as
backup from early December so the cluster was healthy .

None of the troubleshooting steps worked as their is no leader so the
operator or snapshot commands don't work. I tried a boostrap of 1 but it
still refuses to start with the log missing error. That happens on every
node.

I do no longer have the nodes running as I had to try to fix it, but I kept
a full copy of the /var/consul and /var/log/consul of these nodes in a
backup.

I did try creating the peers.json and starting but it still complained
about the log missing. I also tried removing the serf data, then it gave me
à slightly different error with the index Id that was missing (instead of a
crash dump)

I was surprised to not be able to do anything to manipulate the files like
doing a snapshot or exporting the local data somehow without leadership or
without having to run the daemon, am I missing something?

Was running 6 modes with expect 3 a mistake that could explain it?

Thanks!

**Comment by slackpad** [comment]
> Was running 6 modes with expect 3 a mistake that could explain it?

Oh interesting - if a subset of servers managed to bootstrap themselves they could have formed their own leader and led to a split-brain kind of scenario.

> I was surprised to not be able to do anything to manipulate the files like
doing a snapshot or exporting the local data somehow without leadership or
without having to run the daemon, am I missing something?

The snapshot command will work during an outage if you pass the `-stale` argument.

> I had to do some surgery as the nodes ip and hostname had changed.

There's definitely a lot of potential for problems there. Consul 1.0 defaults the Raft protocol to 3, which internally uses node IDs instead of IPs to track the Raft quorum membership, so with that version of Consul if you were able to attach the old EBS volumes to new servers they should have retained their node IDs and Consul will now sort out the IP mapping and fix it up automatically (see #1580).

**Comment by hamstah** [comment]
> Oh interesting - if a subset of servers managed to bootstrap themselves they could have formed their own leader and led to a split-brain kind of scenario.

I was thinking of the split brain issue, but I would expect my initial cluster to not go down in that case.
I would expect to have 2 separate clusters of 3 nodes.

> The snapshot command will work during an outage if you pass the -stale argument.

Yes but the daemon needs to be healthy and running (ie not my case where the log is missing). Maybe something like "log index missing, last known index is, do you want to bootstrap from that?" Or just have the option to do a snapshot to the last valid index (or any index specified). The issue is that in that situation nothing works, not `consul info`, not `consul members` etc.

Good to hear about 1.0 though.

I feel like the files I have might be valuable to track down the issues I mentioned above and help make the tools more robust to recover in these situations? I basically got me to lose my cluster data despite having the data on disk. There should always be an option to restore from the data file IMO

**Comment by slackpad** [comment]
> I feel like the files I have might be valuable to track down the issues I mentioned above and help make the tools more robust to recover in these situations? I basically got me to lose my cluster data despite having the data on disk. There should always be an option to restore from the data file IMO

That's fair for sure. We could document this and make some better tooling around it - it's possible to take the snapshot files from your data directory and restore them into a fresh cluster using `consul snapshot restore`.

To manually create a snapshot archive, create a .tar.gz archive with the `meta.json`, `state.bin`, and a `SHA256SUMS` file covering those inside:

```
$ CONSUL_HTTP_ADDR=demo.consul.io:80 consul snapshot save foo.tar.gz
Saved and verified snapshot to index 671350

$ tar xzvf foo.tar.gz
x meta.json
x state.bin
x SHA256SUMS 

$ cat SHA256SUMS
7b2620c44dbce402052d26ad93a729c697f4f8f3a7a82687a6e8008b18c8d686  meta.json
0b244b1e3fa3ea0c2f11c8da9b02531e7538ce8d74603dcf784f596eda6ab11b  state.bin
```

If you still have those files laying around it would be interesting to attempt a recovery that way.

**Comment by hamstah** [comment]
Thanks, I will give it a try.

Should we also investigate the split brain scenario and how it's handled? Just want to make sure that the condition to reproduce my issues are not just a mistake as easy to make.

**Comment by slackpad** [comment]
> Should we also investigate the split brain scenario and how it's handled?

Yeah I was thinking about that more and I think that would only apply to a totally fresh cluster where you deploy 6 configured with bootstrap expect set to 3 and you get 2 leaders and you get a split brain for a while until they eventually add the other servers and then fight it out for a while.

For your scale up case, none of the existing servers should acknowledge a potentially new leader since it will have a lower term than the true leader. It's worth an extra look though to make sure that's correct, though.
