### ISSUE TITLE
consul crash with ports config parameters

### ISSUE THREAD

**Issue by qli-aa** [hashicorp/consul#3817]
I found when I used below configs (Consul 1.0.0/1.0.1/1.0.2), consul will crash
......
   "ports": {
        "serf_wan": -1
    },
  ......

but with 0.9.3 it is ok.

**Comment by slackpad** [comment]
```
consul agent -dev -config-file=crash.json
==> Starting Consul agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4b2615e]

goroutine 1 [running]:
github.com/hashicorp/consul/agent.(*Agent).consulConfig(0xc4200781a0, 0xc42024d450, 0xdf8475800, 0xc42018e360)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/agent/agent.go:701 +0x32e
github.com/hashicorp/consul/agent.(*Agent).Start(0xc4200781a0, 0xc4200781a0, 0x0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/agent/agent.go:276 +0x228
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc4202b9800, 0xc420010160, 0x2, 0x2, 0x0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/agent.go:337 +0x414
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc4202b9800, 0xc420010160, 0x2, 0x2, 0xc4202c16e0)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/command/agent/agent.go:77 +0x50
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42018d320, 0xc42018d320, 0x40, 0xc4202c1900)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.realMain(0x4bbb147)
        /Users/james/projects/_go/src/github.com/hashicorp/consul/main.go:52 +0x416
main.main()
        /Users/james/projects/_go/src/github.com/hashicorp/consul/main.go:19 +0x22
```
