### ISSUE TITLE
Possible memory leak in Consul 1.1.0

### ISSUE THREAD

**Issue by eugenepaniot** [hashicorp/consul#4140]
#### Overview of the Issue

Consul server dramtically ate all avalaible memory. ~6Gb in ~10 minutes.

#### Reproduction Steps

Seems, the issue occur then node is a leader.
We have a large (from my point of view) consul installation with 175 members and ~3900 registered services.
Data size:
```
# du -hs  /var/lib/consul-server/
205M	/var/lib/consul-server/
```

```
# consul-client operator raft list-peers
Node                    ID                                    Address             State     Voter  RaftProtocol
ams02-c01-css02-server  1a98415d-aa38-5094-9ed5-490d5ceb01e3  10.62.80.143:18300  follower  true   3
ams02-c01-css04-server  0e258b86-3c5d-d6e0-4119-00f4d25ed23a  10.62.4.2:18300     follower  true   3
ams02-c01-css03-server  984b886d-3544-1372-4ec0-452e46b98f07  10.62.80.145:18300  leader    true   3
ams02-c01-css05-server  940eba8a-eae0-6b2e-5ede-d23af446ed47  10.62.4.3:18300     follower  true   3
ams02-c01-css01-server  f3f55da2-e670-05dd-1ed2-bb994bb95c76  10.62.80.130:18300  follower  true   3
```

### Consul info for Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 5174058f
	version = 1.1.0
consul:
	bootstrap = false
	known_datacenters = 8
	leader = true
	leader_addr = 10.62.80.145:18300
	server = true
raft:
	applied_index = 816577279
	commit_index = 816577279
	fsm_pending = 0
	last_contact = 0
	last_log_index = 816577279
	last_log_term = 597465
	last_snapshot_index = 816563633
	last_snapshot_term = 597465
	latest_configuration = [{Suffrage:Voter ID:1a98415d-aa38-5094-9ed5-490d5ceb01e3 Address:10.62.80.143:18300} {Suffrage:Voter ID:0e258b86-3c5d-d6e0-4119-00f4d25ed23a Address:10.62.4.2:18300} {Suffrage:Voter ID:984b886d-3544-1372-4ec0-452e46b98f07 Address:10.62.80.145:18300} {Suffrage:Voter ID:940eba8a-eae0-6b2e-5ede-d23af446ed47 Address:10.62.4.3:18300} {Suffrage:Voter ID:f3f55da2-e670-05dd-1ed2-bb994bb95c76 Address:10.62.80.130:18300}]
	latest_configuration_index = 816557290
	num_peers = 4
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 597465
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 112399
	max_procs = 4096
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1756
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 9410
	members = 174
	query_queue = 0
	query_time = 58
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1656
	members = 26
	query_queue = 0
	query_time = 58
```

</details>

### Operating system and Environment details

CentOS Linux release 7.3.1611 (Core) 

### Log Fragments

```
# systemctl status consul-server
● consul-server.service - Consul Server
   Loaded: loaded (/usr/lib/systemd/system/consul-server.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/consul-server.service.d
           └─highpriority.conf, limits.conf, restart.conf, syslog.conf
   Active: active (running) since Fri 2018-05-18 16:21:45 UTC; 15min ago
     Docs: http://www.consul.io
 Main PID: 79551 (consul-server)
   Memory: 5.9G
   CGroup: /system.slice/consul-server.service
           └─79551 /usr/bin/consul-server agent -config-file=/etc/consul/server.json -data-dir=/var/lib/consul-server

May 18 16:36:51 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:51 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.73.42:54257
May 18 16:36:56 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:56 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.61.1.196:41856
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.19.12:44877
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.80.127:35237
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.6.118:41632
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.84.25:35732
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.19.49:60696
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.68.245:37046
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.11.197:53426
May 18 16:36:57 ams02-c01-css03 consul-server[79551]: 2018/05/18 16:36:57 [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=10.62.82.60:34780
```

![screenshot from 2018-05-18 19-54-57](https://user-images.githubusercontent.com/17274766/40247526-65b40fe4-5ad5-11e8-8b3b-4b747e287fc9.png)

Then memory is over got an error:

`fatal error: runtime: out of memory`

### Pprof

`curl -s http://localhost:18500/debug/pprof/goroutine?debug=1 > ~/goroutines.txt`

[goroutines.txt](https://github.com/hashicorp/consul/files/2017741/goroutines.txt)

`go tool pprof -proto -output consul_heap.prof /usr/bin/consul-server http://localhost:18500/debug/pprof/heap`

[consul_heap.prof.gz](https://github.com/hashicorp/consul/files/2017745/consul_heap.prof.gz)

```
go tool pprof -top /usr/bin/consul-server ./consul_heap.prof

# go tool pprof -top /usr/bin/consul-server ./consul_heap.prof
1023.82MB of 1048.35MB total (97.66%)
Dropped 608 nodes (cum <= 5.24MB)
Showing top 80 nodes out of 87 (cum >= 55.31MB)
      flat  flat%   sum%        cum   cum%
  538.53MB 51.37% 51.37%   560.03MB 53.42%  github.com/hashicorp/consul/vendor/github.com/hashicorp/net-rpc-msgpackrpc.NewCodecFromHandle
   90.60MB  8.64% 60.01%    90.60MB  8.64%  bytes.makeSlice
   69.26MB  6.61% 66.62%    69.26MB  6.61%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).decodeBytes
   45.50MB  4.34% 70.96%    45.50MB  4.34%  github.com/hashicorp/consul/vendor/github.com/hashicorp/yamux.newStream
   40.50MB  3.86% 74.82%   124.76MB 11.90%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.(*Decoder).decodeValue
   31.01MB  2.96% 77.78%    31.01MB  2.96%  runtime.malg
   29.26MB  2.79% 80.57%    29.26MB  2.79%  runtime.procresize
   19.50MB  1.86% 82.43%    19.50MB  1.86%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb.watchFew
      18MB  1.72% 84.15%       18MB  1.72%  reflect.unsafe_New
   16.50MB  1.57% 85.72%       32MB  3.05%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-immutable-radix.(*Txn).insert
      15MB  1.43% 87.15%       15MB  1.43%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).decodeString
      13MB  1.24% 88.39%       13MB  1.24%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.(*Encoder).encodeValue
      13MB  1.24% 89.63%       13MB  1.24%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-immutable-radix.(*Txn).writeNode
   12.50MB  1.19% 90.83%    12.50MB  1.19%  github.com/hashicorp/consul/agent/structs.(*ServiceNode).PartialClone
   11.50MB  1.10% 91.92%    11.50MB  1.10%  time.NewTimer
    9.50MB  0.91% 92.83%       10MB  0.95%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb.(*StringFieldIndex).FromObject
       9MB  0.86% 93.69%    99.60MB  9.50%  github.com/hashicorp/consul/vendor/github.com/hashicorp/yamux.(*Stream).readData
    8.50MB  0.81% 94.50%       13MB  1.24%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.NewEncoder
       8MB  0.76% 95.26%     8.50MB  0.81%  github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/codec.NewDecoder
    6.50MB  0.62% 95.88%     7.29MB   0.7%  github.com/hashicorp/consul/vendor/github.com/hashicorp/yamux.(*Session).waitForSendErr
       6MB  0.57% 96.45%   117.76MB 11.23%  github.com/hashicorp/consul/agent/consul/fsm.restoreKV
       6MB  0.57% 97.03%    40.36MB  3.85%  runtime.systemstack
       3MB  0.29% 97.31%    48.80MB  4.65%  github.com/hashicorp/consul/agent/consul.(*Catalog).ServiceNodes
    2.64MB  0.25% 97.56%    48.15MB  4.59%  github.com/hashicorp/consul/vendor/github.com/hashicorp/yamux.(*Session).incomingStream
    0.50MB 0.048% 97.61%     5.50MB  0.52%  github.com/hashicorp/consul/agent/consul/state.(*Store).ensureServiceTxn
    0.50MB 0.048% 97.66%   135.81MB 12.95%  net/rpc.(*Server).ServeRequest
         0     0% 97.66%    90.60MB  8.64%  bytes.(*Buffer).ReadFrom
         0     0% 97.66%    90.60MB  8.64%  bytes.(*Buffer).grow
         0     0% 97.66%   125.27MB 11.95%  github.com/hashicorp/consul/agent.(*Agent).Start

```

### Telemetry

Runtime bytes:

![screenshot from 2018-05-18 20-07-54](https://user-images.githubusercontent.com/17274766/40248085-6a2a253e-5ad7-11e8-8ee0-2cb57973c99d.png)

Heap objs

![screenshot from 2018-05-18 20-08-09](https://user-images.githubusercontent.com/17274766/40248107-7a848f50-5ad7-11e8-8289-aed6a4e2d16f.png)

Num goroutines

![screenshot from 2018-05-18 20-08-23](https://user-images.githubusercontent.com/17274766/40248127-858e9c7e-5ad7-11e8-8d19-e9f5b45b3d04.png)

Malloc/free

![screenshot from 2018-05-18 20-08-39](https://user-images.githubusercontent.com/17274766/40248269-14f27912-5ad8-11e8-8c18-db0cdbe0e399.png)

Ready to get any additional information. Please help.
Thank you!

**Comment by eugenepaniot** [comment]
Consul Go logs then issue occur
```
2018-05-22T10:08:00.460676+00:00 ams02-c01-css03 INFO consul-server[1322]: goroutine 3275289 [select, 10 minutes]:
2018-05-22T10:08:00.460818+00:00 ams02-c01-css03 INFO consul-server[1322]: github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb.watchFew(0xc481923830, 0x20, 0x20, 0xc5792b6780, 0x0)
2018-05-22T10:08:00.460957+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb/watch_few.go:15 +0x81c
2018-05-22T10:08:00.464836+00:00 ams02-c01-css03 INFO consul-server[1322]: github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb.WatchSet.Watch(0xc5095c5bf0, 0xc5792b6780, 0x0)
2018-05-22T10:08:00.464991+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/go-memdb/watch.go:56 +0x11c
2018-05-22T10:08:00.465154+00:00 ams02-c01-css03 INFO consul-server[1322]: github.com/hashicorp/consul/agent/consul.(*Server).blockingQuery(0xc4249f63c0, 0xc56e8cd050, 0xc5791e4c18, 0xc5791e3020, 0x0, 0x0)
2018-05-22T10:08:00.465302+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/agent/consul/rpc.go:418 +0x194
2018-05-22T10:08:00.465458+00:00 ams02-c01-css03 INFO consul-server[1322]: github.com/hashicorp/consul/agent/consul.(*Catalog).ServiceNodes(0xc42262f3e0, 0xc56e8ccfd0, 0xc5791e4c00, 0x0, 0x0)
2018-05-22T10:08:00.465601+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/agent/consul/catalog_endpoint.go:247 +0x14c
2018-05-22T10:08:00.465741+00:00 ams02-c01-css03 INFO consul-server[1322]: reflect.Value.call(0xc424cdb4a0, 0xc42262f4c8, 0x13, 0x14f0b47, 0x4, 0xc425e1ee28, 0x3, 0x3, 0x1305a40, 0x19, ...)
2018-05-22T10:08:00.465911+00:00 ams02-c01-css03 INFO consul-server[1322]: /goroot/src/reflect/value.go:447 +0x969
2018-05-22T10:08:00.466055+00:00 ams02-c01-css03 INFO consul-server[1322]: reflect.Value.Call(0xc424cdb4a0, 0xc42262f4c8, 0x13, 0xc425e1ee28, 0x3, 0x3, 0x16, 0x16, 0x16)
2018-05-22T10:08:00.466209+00:00 ams02-c01-css03 INFO consul-server[1322]: /goroot/src/reflect/value.go:308 +0xa4
2018-05-22T10:08:00.466372+00:00 ams02-c01-css03 INFO consul-server[1322]: net/rpc.(*service).call(0xc424dd6280, 0xc424da85a0, 0xc5792b4fd8, 0x0, 0xc424d70d80, 0xc5791e2fe0, 0x13211a0, 0xc56e8ccfd0, 0x16, 0x1116f20, ...)
2018-05-22T10:08:00.466540+00:00 ams02-c01-css03 INFO consul-server[1322]: /goroot/src/net/rpc/server.go:384 +0x14e
2018-05-22T10:08:00.466684+00:00 ams02-c01-css03 INFO consul-server[1322]: net/rpc.(*Server).ServeRequest(0xc424da85a0, 0x161f820, 0xc5791e4b40, 0xc5791e4b40, 0xc56e920e40)
2018-05-22T10:08:00.466828+00:00 ams02-c01-css03 INFO consul-server[1322]: /goroot/src/net/rpc/server.go:504 +0x235
2018-05-22T10:08:00.466969+00:00 ams02-c01-css03 INFO consul-server[1322]: github.com/hashicorp/consul/agent/consul.(*Server).handleConsulConn(0xc4249f63c0, 0x1627080, 0xc56e920e40)
2018-05-22T10:08:00.470443+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/agent/consul/rpc.go:154 +0x143
2018-05-22T10:08:00.470707+00:00 ams02-c01-css03 INFO consul-server[1322]: created by github.com/hashicorp/consul/agent/consul.(*Server).handleMultiplexV2
2018-05-22T10:08:00.470856+00:00 ams02-c01-css03 INFO consul-server[1322]: /gopath/src/github.com/hashicorp/consul/agent/consul/rpc.go:139 +0x18a
```

Last 1000 lines log file attached [meml.txt](https://github.com/hashicorp/consul/files/2026375/meml.txt)

**Comment by mkeeler** [comment]
@eugenpaniot Are there any other insights as to what is going on in that cluster or in what ways it might differ from your other smaller cluster. More behavioral information might help to pinpoint the root cause. What your Consul usage look like in terms of API usage, watches etc. Are you using consul-template?

One thing we found given your heap profile and the go routine dump is that it looks like there are over 100K go routines doing blocking RPC calls for watches. Is your cluster utilizing those blocking queries heavily and are you intending to have that many blocking at once. At the very least, that is what is consuming all of your memory.

**Comment by eugenepaniot** [comment]
@mkeeler  thank you for the investigation it could very help. Actually there are no differences between clusters, just ther size - 3nodes (small) and 5 nodes (big). 

That I found are: 

1. My collegues use consul-template and making subscribtion to all services in all DC (8 - "ams02", "ams05", "ams04", "spb01", "sv701", "aws19", "xia01", "xmn02"), but, consul-template making connection to the one DC (via ams02 DC (where issue occur))

```
... consul-template[17094]: (runner) watching 3520 dependencies ...
```

2. Another usage is subscription on services throught nginx module https://github.com/weibocom/nginx-upsync-module. It makes HTTP GET /v1/catalog/service/%service-name%?recurse&index=%index% to **local consul agent** for ~3500 services.

How may I find sources (IP, or agent ID, etc.) of this watchers, and destination watch (catalog service/services, or kv) ?

Thank you!

**Comment by eugenepaniot** [comment]
I've executed consul-client monitor for 2 hours on one node
`# consul-client monitor -log-level=trace -http-addr=127.0.0.1:8500`

Log from monitor attached: [cc-mon.txt](https://github.com/hashicorp/consul/files/2027422/cc-mon.txt)

**Comment by mkeeler** [comment]
@eugenepaniot There isn't anyway to determine the source of those blocking queries at this time.

When you say that your colleagues are using consul-template do you mean that multiple people are using consul-template independently. If so are you using the deduplication in consul-template?

Do you have multiple nginx servers using that plugin? Each one should be doing ~3500 5 minute long blocking queries.

**Comment by eugenepaniot** [comment]
@mkeeler yes, we have multiple nginx servers (~10). So, I confirm that all watcher from nginx module.. 

On the every nginx nodes we have local consul agent installed, and we are planning update consul to the lattest consul version 1.1.0 with
` "discovery_max_stale": "10m"`

Could it help decrease memory on the consul servers?

**Comment by eugenepaniot** [comment]
@mkeeler I can create pull request to https://github.com/weibocom/nginx-upsync-module and add support of any needed headers/calls/etc that could help decrease load to consul :)
But I'm not sure if "HTTP GET /v1/catalog/service/%service-name%?recurse&index=%index%" requests would be handled by local consul agent, or follower, because this is a "watch" (has index parameter) (as I understand..)  Or am I wrong? 
Or I can move requests from local consul agent to consul servers (followers) directly, to distribute requests accross all nodes, could it helps?

**Comment by mkeeler** [comment]
@eugenepaniot The way it works is that the local agent in your case would handle the HTTP request and issue its own internal RPC call to one of the servers in the datacenter which may or may not be the leader. The server handling that RPC then will do one of a few things.

1. If the RPC is bound for a different datacenter it will forward the RPC to a server in the desired datacenter
2. If the RPC is allowed to operate on stale data (like when the original HTTP request had the stale or max_stale query params set) then regardless of whether its the server it will attempt to perform the RPC locally. 
3. If not allowed to be stale then it will ensure the RPC gets forwarded to the leader and the leader will perform the RPC.

There are some other subtleties here with needing to check that the data isn't too stale and when the server RPCs are sent to changes but in general thats how things work.

So in your case if you added `max_stale=10m` to the query params sent with that GET request it should still do what you want. Passing the index query param just modifies how whatever server that is selected to finally perform the RPC operates (blocking until the raft index is at least at that index)

**Comment by eugenepaniot** [comment]
@mkeeler  thank you so much for your help

**Comment by mkeeler** [comment]
@eugenepaniot Glad I could help.
