### ISSUE TITLE
Consul 1.1 crashes on CentOS 5

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4183]
#### Overview of the Issue

Consul 1.1 crashes on CentOS 5. v1.0.7 appears to be the last version to work.

Looks like the Go compiler in (1.10.1) removed support for a flag needed in CentOS 5. In golang/go#24980 they note that 1.10 worked for the reporter.

Dunno if this is expected, certainly surprised us.

#### Reproduction Steps

```
consul
```

### Consul info for both Client and Server

N/A

### Operating system and Environment details

CentOS 5
x86-64

### Log Fragments

```
# consul
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x1508dc1, 0x17)
	/goroot/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x35768d8b1f200, 0xc42005ff70)
	/goroot/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
	/goroot/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
	/goroot/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
	/goroot/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable]:
os/signal.signal_enable(0x2)
	/goroot/src/runtime/sigqueue.go:207 +0x7c
os/signal.enableSignal(0x2)
	/goroot/src/os/signal/signal_unix.go:49 +0x2a
os/signal.Notify.func1(0x2)
	/goroot/src/os/signal/signal.go:129 +0xa3
os/signal.Notify(0xc42033a660, 0xc4201e5718, 0x2, 0x2)
	/goroot/src/os/signal/signal.go:141 +0x131
github.com/hashicorp/consul/command.MakeShutdownCh(0xc4202374ea)
	/gopath/src/github.com/hashicorp/consul/command/registry.go:51 +0xc9
github.com/hashicorp/consul/command.init.0.func7(0x1624b60, 0xc42027e5d0, 0x14f0f53, 0x4, 0xc4201e5758, 0xc4201cd440)
	/gopath/src/github.com/hashicorp/consul/command/commands_oss.go:62 +0x22
github.com/hashicorp/consul/command.Map.func1(0xc4201cd440, 0x14f0f53, 0x4, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/registry.go:35 +0x3a
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).initAutocompleteSub.func1(0x14f0f53, 0x4, 0x12585a0, 0xc420263520, 0x0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:431 +0x189
github.com/hashicorp/consul/vendor/github.com/armon/go-radix.recursiveWalk(0xc42027e9c0, 0xc4201e59f8, 0x1258500)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/armon/go-radix/radix.go:475 +0xcf
github.com/hashicorp/consul/vendor/github.com/armon/go-radix.recursiveWalk(0xc42027ed80, 0xc4201e59f8, 0xc420263400)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/armon/go-radix/radix.go:481 +0x7c
github.com/hashicorp/consul/vendor/github.com/armon/go-radix.recursiveWalk(0xc42027e660, 0xc4201e59f8, 0xc4202634c0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/armon/go-radix/radix.go:481 +0x7c
github.com/hashicorp/consul/vendor/github.com/armon/go-radix.(*Tree).WalkPrefix(0xc420231c80, 0x0, 0x0, 0xc4201e59f8)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/armon/go-radix/radix.go:413 +0x146
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).initAutocompleteSub(0xc4201cd440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:451 +0xdd
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).initAutocomplete(0xc4201cd440)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:378 +0xb1
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).init(0xc4201cd440)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:357 +0x3a4
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).(github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.init)-fm()
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:145 +0x2a
sync.(*Once).Do(0xc4201cd4e0, 0xc4201e5e10)
	/goroot/src/sync/once.go:44 +0xbe
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201cd440, 0xc4201cd440, 0x40, 0xc4202638e0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:158 +0x6d
main.realMain(0xc420078058)
	/gopath/src/github.com/hashicorp/consul/main.go:52 +0x3ee
main.main()
	/gopath/src/github.com/hashicorp/consul/main.go:19 +0x22

goroutine 5 [runnable]:
os/signal.loop()
	/goroot/src/os/signal/signal_unix.go:20
created by os/signal.init.0
	/goroot/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [runnable]:
text/template/parse.(*lexer).emit(0xc4201856c0, 0x6)
	/goroot/src/text/template/parse/lex.go:154 +0xae
text/template/parse.lexText(0xc4201856c0, 0x1552cc8)
	/goroot/src/text/template/parse/lex.go:266 +0x1dc
text/template/parse.(*lexer).run(0xc4201856c0)
	/goroot/src/text/template/parse/lex.go:228 +0x37
created by text/template/parse.lex
	/goroot/src/text/template/parse/lex.go:221 +0x15f

goroutine 11 [runnable]:
text/template/parse.(*lexer).emit(0xc4201e77a0, 0x6)
	/goroot/src/text/template/parse/lex.go:154 +0xae
text/template/parse.lexText(0xc4201e77a0, 0x1552cc8)
	/goroot/src/text/template/parse/lex.go:266 +0x1dc
text/template/parse.(*lexer).run(0xc4201e77a0)
	/goroot/src/text/template/parse/lex.go:228 +0x37
created by text/template/parse.lex
	/goroot/src/text/template/parse/lex.go:221 +0x15f

goroutine 13 [chan send, locked to thread]:
runtime.gopark(0x15529b0, 0xc420332838, 0x14f68b3, 0x9, 0x1164916, 0x3)
	/goroot/src/runtime/proc.go:291 +0x11a
runtime.goparkunlock(0xc420332838, 0x14f68b3, 0x9, 0x16, 0x3)
	/goroot/src/runtime/proc.go:297 +0x5e
runtime.chansend(0xc4203327e0, 0xc42004f740, 0xc42004f701, 0x456f62, 0x8)
	/goroot/src/runtime/chan.go:234 +0x25b
runtime.chansend1(0xc4203327e0, 0xc42004f740)
	/goroot/src/runtime/chan.go:125 +0x35
runtime.ensureSigM.func1()
	/goroot/src/runtime/signal_unix.go:560 +0x152
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2361 +0x1
```

**Comment by mkeeler** [comment]
@dekimsey As Consul is written in Go we can't support any platforms that Go doesn't support.

According to the [Go platform requirements](https://github.com/golang/go/wiki/MinimumRequirements) CentOS 5 is expressly not supported due to having too old of a kernel. The fact that Consul may have not crashed previously seems to just be a coincidence. Upgrading to 1.10.1 was done to pull in bug fixes for other supported platforms so the binary released by HashiCorp will continue to need to be built with that at least that Go version.

For now, Consul does still seem to build properly using a 1.9 compiler for x86_64 linux so you may want to try building it yourself and see if it has similar issues. This probably isn't a good long term solution though and other changes in Consul/Go could potentially break it again in the future.

**Comment by dekimsey** [comment]
That's fine, I just wanted to make sure it was well known. I wasn't sure if
you all were aware of the change.--

Danny.

Beware! The mind of the believer stagnates. It fails to grow outward into
an unlimited, infinite universe.

Frank Herbert, Heretics of Dune

**Comment by mkeeler** [comment]
@dekimsey Yeah, it certainly wasn't known/expected but not terribly surprising either. Thanks for the heads up.
