### ISSUE TITLE
Consul tcp check does not close cleanly there by throwing  Transport Connection java.io.EOFException

### ISSUE THREAD

**Issue by hfarooqui** [hashicorp/consul#4457]
I have defined following tcp check in consul over stomp port (61650).
```

            {
                "id": "broker_check",
                "name": "check if broker_master is listening on port 61650",
                "tcp": "10.206.24.221:61650",
                "interval": "10s"
            },

```

However I see following exceptions in the broker logs

```
2018-07-27 08:18:06,263 | DEBUG | Transport Connection to: tcp://10.206.24.221:58220 failed: java.io.EOFException | org.apache.activemq.broker.TransportConnection.Transport | ActiveMQ Transport: tcp:///10.206.24.221:58220@61650
java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)[:1.8.0_172]
	at org.apache.activemq.transport.stomp.StompWireFormat.readHeaderLine(StompWireFormat.java:174)[activemq-stomp-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.stomp.StompWireFormat.readLine(StompWireFormat.java:167)[activemq-stomp-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.stomp.StompWireFormat.parseAction(StompWireFormat.java:200)[activemq-stomp-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.stomp.StompWireFormat.unmarshal(StompWireFormat.java:112)[activemq-stomp-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)[activemq-client-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)[activemq-client-5.14.5.jar:5.14.5]
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)[activemq-client-5.14.5.jar:5.14.5]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_172]
2018-07-27 08:18:06,264 | DEBUG | Unregistering MBean com.mobileiron.activemq:type=Broker,brokerName=broker2_master,connector=clientConnectors,connectorName=stomp,connectionViewType=remoteAddress,connectionName=tcp_//10.206.24.221_58220 | org.apache.activemq.broker.jmx.ManagementContext | ActiveMQ Transport: tcp:///10.206.24.221:58220@61650
2018-07-27 08:18:06,265 | DEBUG | Stopping connection: tcp://10.206.24.221:58220 | org.apache.activemq.broker.TransportConnection | ActiveMQ BrokerService[broker2_master] Task-2
2018-07-27 08:18:06,266 | DEBUG | Stopping transport tcp:///10.206.24.221:58220@61650 | org.apache.activemq.transport.tcp.TcpTransport | ActiveMQ BrokerService[broker2_master] Task-2
```

Am I missing something here?

**Comment by hfarooqui** [comment]
Thanks Matt.

For now I am using script to do TCP check using STOMP client.
With this I do not see any warnings in the log.
