### ISSUE TITLE
ACL config file error on server startup

### ISSUE THREAD

**Issue by ADeane6** [hashicorp/consul#4770]
#### Overview of the Issue

With ACL enabled and a default acl policy file, consul fails to start with a GO panic

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 server nodes
1. with the following ACL config
    
```
# Default all keys to read-only
key "" {
    policy = "read"
}
key "foo/" {
    policy = "write"
}

# Default all services to allow registration. Also permits all
# services to be discovered.
service "" {
    policy = "write"
}

# Deny registration access to services prefixed "secure-".
# Discovery of the service is still allowed in read mode.
service "secure-" {
    policy = "read"
}

# Allow firing any user event by default.
event "" {
    policy = "write"
}

# Deny firing events prefixed with "destroy-".
event "destroy" {
    policy = "deny"
}

# Default prepared queries to read-only.
query "" {
    policy = "read"
}

# Read-only mode for the encryption keyring by default (list only)
keyring = "read"

# Read-only mode for Consul operator interfaces (list only)
operator = "read"
```

1. `panic: key: []map[string]interface{} with more than one element not supported: [map[:[map[policy:read]]] map[foo/:[map[policy:write]]]]`

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

Consul Version: 1.2.3

</details>

### Operating system and Environment details

RHEL 7, AWS

### Log Fragments

```
Oct 09 10:06:54 hostname consul[16710]: panic: key: []map[string]interface{} with more than one element not supported: [map[:[map[policy:read]]] map[foo/:[map[policy:write]]]]
Oct 09 10:06:54 hostname consul[16710]: goroutine 1 [running]:
Oct 09 10:06:54 hostname consul[16710]: github.com/hashicorp/consul/agent/config.patchValue(0xc420404e83, 0x3, 0x16a93c0, 0xc420464740, 0xc4204f8f30, 0x8, 0x8, 0xc420438ca0, 0xc420404f50)
Oct 09 10:06:54 hostname consul[16710]: /go/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:57 +0x9fd
Oct 09 10:06:54 hostname consul[16710]: github.com/hashicorp/consul/agent/config.patchValue(0x0, 0x0, 0x17fda20, 0xc4203a4fc0, 0xc4204f8f30, 0x8, 0x8, 0x0, 0x0)
Oct 09 10:06:54 hostname consul[16710]: /go/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:24 +0x181
Oct 09 10:06:54 hostname consul[16710]: github.com/hashicorp/consul/agent/config.patchSliceOfMaps(0xc4203a4fc0, 0xc4204f8f30, 0x8, 0x8, 0x0)
Oct 09 10:06:54 hostname consul[16710]: /go/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:8 +0x61
Oct 09 10:06:54 hostname consul[16710]: github.com/hashicorp/consul/agent/config.Parse(0xc42047a000, 0x318, 0x1c29c1a, 0x3, 0xc4200b4bd0, 0xc4200b4c10, 0xc4200b4c40, 0xc4200b4c70, 0x0, 0xc
```

**Comment by pearkes** [comment]
#4791 will likely have fixed parsing errors such as these for policies that are incorrect, hopefully we can supply a better error message.
