### ISSUE TITLE
Consul does not boot anymore - "panic: failed to save current term: MDB_PAGE_FULL: Internal error - page has no more space"

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/consul#509]
```
==> WARNING: Expect Mode enabled, expecting 3 servers
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
panic: failed to save current term: MDB_PAGE_FULL: Internal error - page has no more space

goroutine 16 [running]:
runtime.panic(0x9e48a0, 0xc2080b0050)
        /opt/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/hashicorp/raft.(*Raft).setCurrentTerm(0xc208130000, 0x18d)
        /opt/gopath/src/github.com/hashicorp/raft/raft.go:1523 +0x17a
github.com/hashicorp/raft.NewRaft(0xc208004f00, 0x7faf4018d578, 0xc2080f10b0, 0x7faf4018d5b0, 0xc20812e000, 0x7faf4018d600, 0xc20812e000, 0x7faf4018d640, 0xc20812e080, 0x7faf4018d548, ...)
        /opt/gopath/src/github.com/hashicorp/raft/raft.go:221 +0x98b
github.com/hashicorp/consul/consul.(*Server).setupRaft(0xc208011a20, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:370 +0x9e0
github.com/hashicorp/consul/consul.NewServer(0xc2080118c0, 0xc2080118c0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:228 +0x9ea
github.com/hashicorp/consul/command/agent.(*Agent).setupServer(0xc208047040, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:263 +0x50
github.com/hashicorp/consul/command/agent.Create(0xc2080e4800, 0x7faf4018c1e8, 0xc2080ab6c0, 0x415a98, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:115 +0x4ed
github.com/hashicorp/consul/command/agent.(*Command).setupAgent(0xc208053540, 0xc2080e4800, 0x7faf4018c1e8, 0xc2080ab6c0, 0xc2080bbd10, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:256 +0xd4
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc208053540, 0xc20800e020, 0x2, 0x2, 0x0)
        /opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:468 +0xa82
github.com/mitchellh/cli.(*CLI).Run(0xc2080534a0, 0xc2080534a0, 0x0, 0x0)
        /opt/gopath/src/github.com/mitchellh/cli/cli.go:100 +0x3a1
main.realMain(0x4120ee)
        /opt/gopath/src/github.com/hashicorp/consul/main.go:37 +0x2fb
main.main()

goroutine 19 [finalizer wait]:
runtime.park(0x424b00, 0x107d870, 0x1068a49)
        /opt/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x107d870, 0x1068a49)
        /opt/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /opt/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /opt/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /opt/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /opt/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 23 [select]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc2080e2140)
        /opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xa8
created by github.com/armon/go-metrics.NewInmemSignal
        /opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x168

goroutine 24 [sleep]:
time.Sleep(0x3b9aca00)
        /opt/go/src/pkg/runtime/time.goc:39 +0x31
github.com/armon/go-metrics.(*Metrics).collectStats(0xc20801bea0)
        /opt/gopath/src/github.com/armon/go-metrics/metrics.go:67 +0x2b
created by github.com/armon/go-metrics.New
        /opt/gopath/src/github.com/armon/go-metrics/start.go:61 +0x9b

goroutine 25 [select]:
github.com/hashicorp/consul/consul.(*ConnPool).reap(0xc2080ec190)
        /opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:362 +0x48a
created by github.com/hashicorp/consul/consul.NewPool
        /opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:155 +0xda

goroutine 17 [syscall]:
runtime.goexit()
        /opt/go/src/pkg/runtime/proc.c:1445

goroutine 27 [runnable]:
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080050e0)
        /opt/gopath/src/github.com/hashicorp/raft/net_transport.go:336
created by github.com/hashicorp/raft.NewNetworkTransport
        /opt/gopath/src/github.com/hashicorp/raft/net_transport.go:135 +0x1c9
```

**Comment by lyrixx** [comment]
I updated consul to v0.5.0 ; I'm closing this one, until it happens again.

Thanks all for your feedback
