### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by frafra** [hashicorp/consul#5127]
#### Overview of the Issue

Crash when rebooting.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Reboot a server
1. Crash

Servers launched with this command:

```
podman run --detach \
  --volume "$consul_data":/consul/data:Z \
  --net=host \
  consul agent \
    -server \
    -bind=$ip \
    -retry-join=$first \
    -bootstrap-expect=$quorum
```

### Operating system and Environment details

Official Docker image.

```
# podman run --rm consul -v
Consul v1.4.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Log Fragments

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf486ed]

goroutine 1 [running]:
github.com/containers/libpod/libpod.(*storageService).GetRunDir(0xc0003d85a0, 0xc0003c9f80, 0x40, 0x0, 0xc000387080, 0x0, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/libpod/storage.go:304 +0x2d
github.com/containers/libpod/libpod.(*Container).refresh(0xc000074880, 0x1f7b960, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/libpod/container_internal.go:317 +0xc4
github.com/containers/libpod/libpod.(*Runtime).refresh(0xc0000c00c0, 0xc0003cb6a0, 0x15, 0x0, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/libpod/runtime.go:722 +0x16c
github.com/containers/libpod/libpod.makeRuntime(0xc0000c00c0, 0x14745c0, 0xc00037ca50)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/libpod/runtime.go:616 +0xc6b
github.com/containers/libpod/libpod.NewRuntime(0xc00000e0c0, 0x1, 0x1, 0x0, 0x1, 0xc00000e0c0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/libpod/runtime.go:349 +0x39a
github.com/containers/libpod/cmd/podman/libpodruntime.GetRuntimeWithStorageOpts(0xc000106b00, 0xc00053e4c8, 0xc000038780, 0x1b, 0xc00003d200)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:156 +0x6f5
github.com/containers/libpod/cmd/podman/libpodruntime.GetRuntime(0xc000106b00, 0x12c674c, 0x6, 0xc00053e600)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/cmd/podman/libpodruntime/runtime.go:22 +0x120
main.execCmd(0xc000106b00, 0x0, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/cmd/podman/exec.go:74 +0xde
github.com/containers/libpod/vendor/github.com/urfave/cli.HandleAction(0x111a740, 0x1359cd0, 0xc000106b00, 0x0, 0xc000386000)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x12c5078, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12f0d7a, 0x24, 0x0, ...)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:165 +0x459
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc000144c40, 0xc0001062c0, 0x0, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:383 +0x827
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.startApp(0x12c9a21, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12d3089, 0x11, 0x0, ...)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:377 +0x808
github.com/containers/libpod/vendor/github.com/urfave/cli.Command.Run(0x12c9a21, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12d3089, 0x11, 0x0, ...)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/command.go:103 +0x80f
github.com/containers/libpod/vendor/github.com/urfave/cli.(*App).Run(0xc000144a80, 0xc0000301e0, 0x6, 0x6, 0x0, 0x0)
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/vendor/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
	/builddir/build/BUILD/libpod-db08685af57206c21fd3dd150ecb70d7147ce7f4/_build/src/github.com/containers/libpod/cmd/podman/main.go:258 +0x148c
```

**Comment by pearkes** [comment]
This actually looks like a bug in libpod, not Consul, as the panic shows. If you determine otherwise please open a new issue. Unfortunately I don't know enough about libpod to give any specific advice here.
