### ISSUE TITLE
Consul panics on "acl set-agent-token"

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/consul#5531]
#### Overview of the Issue

Consul agent panics when trying to `acl set-agent-token`

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Start the Consul agent
2. Try to set the agent acl token via `consul acl set-agent-token default xxx-xxx-xxx`
3. Consul panics with:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x72a7ee]

goroutine 1 [running]:
github.com/hashicorp/consul/api.(*Agent).updateTokenOnce(0xc0006a3d28, 0x28ecda1, 0x7, 0x7ffd459b6728, 0x24, 0x0, 0xc0006a3ba8, 0x4eff39, 0xc000251900, 0xc0006a3bf8)
	/go/src/github.com/hashicorp/consul/api/agent.go:1005 +0x1be
github.com/hashicorp/consul/api.(*Agent).updateTokenFallback(0xc0006a3d28, 0x28ecda1, 0x7, 0x28f034c, 0x9, 0x7ffd459b6728, 0x24, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/hashicorp/consul/api/agent.go:992 +0x6a
github.com/hashicorp/consul/api.(*Agent).UpdateDefaultACLToken(0xc0006a3d28, 0x7ffd459b6728, 0x24, 0x0, 0x7ffd459b6720, 0x7, 0x7ffd459b6728)
	/go/src/github.com/hashicorp/consul/api/agent.go:962 +0x7a
github.com/hashicorp/consul/command/acl/agenttokens.(*cmd).Run(0xc0006de780, 0xc00004a080, 0x2, 0x2, 0xc000447b80)
	/go/src/github.com/hashicorp/consul/command/acl/agenttokens/agent_tokens.go:54 +0x739
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0005039e0, 0xc0005039e0, 0x80, 0xc000447fe0)
	/go/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x207
main.realMain(0xc000098058)
	/go/src/github.com/hashicorp/consul/main.go:53 +0x38d
main.main()
	/go/src/github.com/hashicorp/consul/main.go:20 +0x22
```
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 1
build:
	prerelease =
	revision = 567e41ff
	version = 1.4.3
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 56
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 166
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1979
	members = 36
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 4
	services = 4
build:
	prerelease =
	revision = 567e41ff
	version = 1.4.3
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = redacted:8300
	server = true
raft:
	applied_index = 15836563
	commit_index = 15836563
	fsm_pending = 0
	last_contact = 0
	last_log_index = 15836563
	last_log_term = 814
	last_snapshot_index = 15832832
	last_snapshot_term = 814
	latest_configuration = [{Suffrage:Voter ID:0463ab91-3497-bcf9-1cbb-630e5bedff37 Address:redacted:8300} {Suffrage:Voter ID:2057b376-5b13-0e5a-f144-01efcd2c7c93 Address:redacted:8300} {Suffrage:Voter ID:3a9240d9-15d5-6ea6-8505-24ad83ca8d9f Address:redacted:8300}]
	latest_configuration_index = 15819069
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 814
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 327
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 166
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1979
	members = 36
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 347
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

CentOS Linux release 7.6.1810 (Core)

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by danlsgiga** [comment]
I just discovered that this is happening because I'm missing the `{"acl": "enabled": true}` in the consul agent config. Once I added that, the command now succeeds.

**Comment by mkeeler** [comment]
This could also happen if you used a 1.4.3 cli against a 1.4.2 or below agent.
