### ISSUE TITLE
Test case failures for GO env(GOTEST_PKG) - "./agent" and "./agent/consul"

### ISSUE THREAD

**Issue by ghatwala** [hashicorp/consul#5675]
#### Overview of the Issue
Getting Test case failures for "env: GOTEST_PKGS="./agent"
```
FAIL	github.com/hashicorp/consul/agent	480.548s
Exit code: 1
panic: test timed out after 8m0s
goroutine 60114 [running]:
testing.(*M).startAlarm.func1()
	/home/travis/.gimme/versions/go1.12.1.linux.ppc64le/src/testing/testing.go:1334 +0xcc
created by time.goFunc
	/home/travis/.gimme/versions/go1.12.1.linux.ppc64le/src/time/sleep.go:169 +0x44
goroutine 1 [chan receive, 4 minutes]:
testing.tRunner.func1(0xc000206800)
	/home/travis/.gimme/versions/go1.12.1.linux.ppc64le/src/testing/testing.go:841 +0x1f0
--- FAIL: TestPreparedQuery_Integration (0.86s)
    prepared_query_endpoint_test.go:1080: bad: {my-service [] {} dc1 0 {0 0s true leader}}
FAIL	github.com/hashicorp/consul/agent	480.548s
GNUmakefile:155: recipe for target 'test-internal' failed
make[1]: *** [test-internal] Error 1
make[1]: Leaving directory '/home/travis/gopath/src/github.com/hashicorp/consul'
```
Getting Test case failures for "env: GOTEST_PKGS="./agent/consul"
```
panic: runtime error: invalid memory address or nil pointer dereference
FAIL	github.com/hashicorp/consul/agent/consul	79.580s
Exit code: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x107ee474]
goroutine 29758 [running]:
github.com/hashicorp/consul/agent/consul.TestACLReplication_TokensRedacted.func3(0xc0005e6040)
	/home/travis/gopath/src/github.com/hashicorp/consul/agent/consul/acl_replication_test.go:643 +0x124
github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/sdk/testutil/retry.run.func2(0xc001ae5c30, 0xc0016a2a80, 0xc0005e6040)
	/home/travis/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/sdk/testutil/retry/retry.go:130 +0x60
created by github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/sdk/testutil/retry.run
	/home/travis/gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/sdk/testutil/retry/retry.go:128 +0x120
FAIL	github.com/hashicorp/consul/agent/consul	79.580s
FAIL	github.com/hashicorp/consul/agent/consul	79.580s
GNUmakefile:155: recipe for target 'test-internal' failed
make[1]: *** [test-internal] Error 1
make[1]: Leaving directory '/home/travis/gopath/src/github.com/hashicorp/consul'
```

#### Reproduction Steps
Please refer to the logs here 
For GOTEST_PKGS="./agent" - https://travis-ci.org/hashicorp/consul/jobs/521105070
For GOTEST_PKGS="./agent/consul" - https://travis-ci.org/hashicorp/consul/jobs/521105071

### Operating system and Environment details
For - ppc64le architecture. 
Trying to add support for power via this PR - https://github.com/hashicorp/consul/pull/5674

### Log Fragments
Travis build log url attached.

Any pointers to resolve above issues ?

**Comment by ghatwala** [comment]
Close this.
