### ISSUE TITLE
invalid memory address or nil pointer dereference when using set-agent-token

### ISSUE THREAD

**Issue by joewilliams** [hashicorp/consul#5762]
#### Overview of the Issue

`consul acl set-agent-token default` fails with a nil pointer defreference when the ACL blocks the addition of the token.

#### Reproduction Steps

Steps to reproduce this issue, eg:

```
$ docker images | grep consul
consul                         latest              9c9974471250        5 days ago          108MB
```
```
$ docker exec e508b52cc65a consul -v
Consul v1.4.4
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
```
$ docker exec e508b52cc65a consul acl set-agent-token default a634b52e-2c7f-2c0e-6a72-3e52792db9d1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x72a7ee]

goroutine 1 [running]:
github.com/hashicorp/consul/api.(*Agent).updateTokenOnce(0xc0005b1d28, 0x28ecb67, 0x7, 0x7ffe6b67ef1d, 0x24, 0x0, 0xc0005b1ba8, 0x4eff39, 0xc0006fb900, 0xc0005b1bf8)
	/go/src/github.com/hashicorp/consul/api/agent.go:1005 +0x1be
github.com/hashicorp/consul/api.(*Agent).updateTokenFallback(0xc0005b1d28, 0x28ecb67, 0x7, 0x28f0112, 0x9, 0x7ffe6b67ef1d, 0x24, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/hashicorp/consul/api/agent.go:992 +0x6a
github.com/hashicorp/consul/api.(*Agent).UpdateDefaultACLToken(0xc0005b1d28, 0x7ffe6b67ef1d, 0x24, 0x0, 0x7ffe6b67ef15, 0x7, 0x7ffe6b67ef1d)
	/go/src/github.com/hashicorp/consul/api/agent.go:962 +0x7a
github.com/hashicorp/consul/command/acl/agenttokens.(*cmd).Run(0xc00001c3c0, 0xc00004a120, 0x2, 0x2, 0xc000483bc0)
	/go/src/github.com/hashicorp/consul/command/acl/agenttokens/agent_tokens.go:54 +0x739
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc00051f440, 0xc00051f440, 0x80, 0xc000483d60)
	/go/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x207
main.realMain(0xc000094058)
	/go/src/github.com/hashicorp/consul/main.go:53 +0x38d
main.main()
	/go/src/github.com/hashicorp/consul/main.go:20 +0x22
```

Server log:
```
    2019/05/01 22:02:26 [ERR] http: Request PUT /v1/agent/token/default, error: ACL not found from=127.0.0.1:50090
```
### Consul info for both Client and Server

```
$ docker exec e508b52cc65a consul info -token=0D37E04F-05E6-4EED-86BE-3B3A9D959BB5
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = ea5210a3
	version = 1.4.4
consul:
	acl = enabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 172.17.0.2:8300
	server = true
raft:
	applied_index = 43
	commit_index = 43
	fsm_pending = 0
	last_contact = 0
	last_log_index = 43
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:570fd3c0-fe98-df06-6485-0586b0337b67 Address:172.17.0.2:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 83
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Running in docker on OSX.

**Comment by pearkes** [comment]
This is fixed in https://github.com/hashicorp/consul/pull/5533 and available in 1.5.0. Thanks for reporting!
