### ISSUE TITLE
Failed to apply request

### ISSUE THREAD

**Issue by tj** [hashicorp/consul#685]
Went to upgrade the v0.4.1 servers to the RC, seemed to work for a moment, and it's exploding with the following panic over and over. Any suggestions to clear whatever these calls are?

```
panic: failed to apply request: []byte{0x5, 0x84, 0xaa, 0x44, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0xa3, 0x64, 0x63, 0x31, 0xa2, 0x4f, 0x70, 0xa4, 0x72, 0x65, 0x61, 0x70, 0xa9, 0x52, 0x65, 0x61, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0xce, 0x0, 0xf, 0xc8, 0x3, 0xa5, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0xa0}

goroutine 26 [running]:
runtime.panic(0x9e48a0, 0xc2082aa830)
  /opt/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/hashicorp/consul/consul.(*consulFSM).Apply(0xc20813c9f0, 0xc2082b2c80, 0x0, 0x0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/fsm.go:86 +0x2b0
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080d2000)
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:522 +0xb9f
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:232 +0x26
github.com/hashicorp/raft.func·008()
  /opt/gopath/src/github.com/hashicorp/raft/state.go:152 +0x4e
created by github.com/hashicorp/raft.(*raftState).goFunc
  /opt/gopath/src/github.com/hashicorp/raft/state.go:153 +0x9c

goroutine 16 [select]:
github.com/hashicorp/consul/command/agent.NewDNSServer(0xc2080cec80, 0xc208059048, 0x7f0e191dce58, 0xc20803aea0, 0xaeb3b0, 0x7, 0xc20809daa0, 0xe, 0x0, 0x0, ...)
  /opt/gopath/src/github.com/hashicorp/consul/command/agent/dns.go:122 +0xa0c
github.com/hashicorp/consul/command/agent.(*Command).setupAgent(0xc2080ccdc0, 0xc208059000, 0x7f0e191dce58, 0xc20803aea0, 0xc208029aa0, 0x0, 0x0)
  /opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:305 +0xc2a
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc2080ccdc0, 0xc20800e020, 0x3, 0x3, 0x0)
  /opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:468 +0xa82
github.com/mitchellh/cli.(*CLI).Run(0xc2080ccd20, 0xc2080ccd20, 0x0, 0x0)
  /opt/gopath/src/github.com/mitchellh/cli/cli.go:100 +0x3a1
main.realMain(0x4120ee)
  /opt/gopath/src/github.com/hashicorp/consul/main.go:37 +0x2fb
main.main()
  /opt/gopath/src/github.com/hashicorp/consul/main.go:12 +0x1e

goroutine 19 [finalizer wait]:
runtime.park(0x424b00, 0x107d870, 0x1068a49)
  /opt/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x107d870, 0x1068a49)
  /opt/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
  /opt/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
  /opt/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
  /opt/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
  /opt/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 32 [select]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc2080638c0)
  /opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xa8
created by github.com/armon/go-metrics.NewInmemSignal
  /opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x168

goroutine 33 [sleep]:
time.Sleep(0x3b9aca00)
  /opt/go/src/pkg/runtime/time.goc:39 +0x31
github.com/armon/go-metrics.(*Metrics).collectStats(0xc20805caf0)
  /opt/gopath/src/github.com/armon/go-metrics/metrics.go:67 +0x2b
created by github.com/armon/go-metrics.New
  /opt/gopath/src/github.com/armon/go-metrics/start.go:61 +0x9b

goroutine 34 [select]:
github.com/hashicorp/consul/consul.(*ConnPool).reap(0xc20805cdc0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:362 +0x48a
created by github.com/hashicorp/consul/consul.NewPool
  /opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:155 +0xda

goroutine 33 [syscall]:
runtime.goexit()
  /opt/go/src/pkg/runtime/proc.c:1445

goroutine 24 [select]:
github.com/hashicorp/consul/consul.(*RaftLayer).Accept(0xc208063d80, 0x0, 0x0, 0x0, 0x0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/raft_rpc.go:56 +0x14d
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208060120)
  /opt/gopath/src/github.com/hashicorp/raft/net_transport.go:339 +0x4f
created by github.com/hashicorp/raft.NewNetworkTransport
  /opt/gopath/src/github.com/hashicorp/raft/net_transport.go:135 +0x1c9

goroutine 25 [select]:
github.com/hashicorp/raft.(*Raft).runFollower(0xc2080d2000)
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:571 +0x77c
github.com/hashicorp/raft.(*Raft).run(0xc2080d2000)
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:556 +0x90
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:231 +0x26
github.com/hashicorp/raft.func·008()
  /opt/gopath/src/github.com/hashicorp/raft/state.go:152 +0x4e
created by github.com/hashicorp/raft.(*raftState).goFunc
  /opt/gopath/src/github.com/hashicorp/raft/state.go:153 +0x9c

goroutine 27 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080d2000)
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:1533 +0x3bd
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
  /opt/gopath/src/github.com/hashicorp/raft/raft.go:233 +0x26
github.com/hashicorp/raft.func·008()
  /opt/gopath/src/github.com/hashicorp/raft/state.go:152 +0x4e
created by github.com/hashicorp/raft.(*raftState).goFunc
  /opt/gopath/src/github.com/hashicorp/raft/state.go:153 +0x9c

goroutine 28 [select]:
github.com/hashicorp/consul/consul.(*Server).monitorLeadership(0xc20811a2c0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/leader.go:32 +0x19d
created by github.com/hashicorp/consul/consul.(*Server).setupRaft
  /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:378 +0xa6f

goroutine 29 [select]:
github.com/hashicorp/serf/serf.(*serfQueries).stream(0xc20822f770)
  /opt/gopath/src/github.com/hashicorp/serf/serf/internal_query.go:80 +0x238
created by github.com/hashicorp/serf/serf.newSerfQueries
  /opt/gopath/src/github.com/hashicorp/serf/serf/internal_query.go:73 +0x9f

goroutine 30 [select]:
github.com/hashicorp/serf/serf.(*Snapshotter).stream(0xc2080c6630)
  /opt/gopath/src/github.com/hashicorp/serf/serf/snapshot.go:175 +0x890
created by github.com/hashicorp/serf/serf.NewSnapshotter
  /opt/gopath/src/github.com/hashicorp/serf/serf/snapshot.go:123 +0x510

goroutine 31 [IO wait]:
net.runtime_pollWait(0x7f0e191dddd8, 0x72, 0x0)
  /opt/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20816a060, 0x72, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20816a060, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20816a000, 0xc43d00, 0x0, 0x7f0e191dc440, 0xb)
  /opt/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803c048, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
github.com/hashicorp/memberlist.(*Memberlist).tcpListen(0xc20813a1c0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:173 +0x2b
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:121 +0xa3b

goroutine 49 [IO wait]:
net.runtime_pollWait(0x7f0e191ddd28, 0x72, 0x0)
  /opt/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20816a0d0, 0x72, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20816a0d0, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).readFrom(0xc20816a070, 0xc2080d8000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f0e191dc440, 0xb)
  /opt/go/src/pkg/net/fd_unix.go:269 +0x3db
net.(*UDPConn).ReadFromUDP(0xc20803c068, 0xc2080d8000, 0x10000, 0x10000, 0x436faa, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/udpsock_posix.go:67 +0x129
net.(*UDPConn).ReadFrom(0xc20803c068, 0xc2080d8000, 0x10000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/udpsock_posix.go:82 +0x142
github.com/hashicorp/memberlist.(*Memberlist).udpListen(0xc20813a1c0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:235 +0x2a4
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:122 +0xa59

goroutine 50 [select]:
github.com/hashicorp/memberlist.(*Memberlist).udpHandler(0xc20813a1c0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:320 +0x2d8
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:123 +0xa77

goroutine 51 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc20813a1c0, 0x3b9aca00, 0xc20816a620, 0xc2081f42a0, 0xc20809c810)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:98 +0x14a
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:70 +0x151

goroutine 52 [select]:
github.com/hashicorp/memberlist.(*Memberlist).pushPullTrigger(0xc20813a1c0, 0xc2081f42a0)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:122 +0x196
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:76 +0x269

goroutine 53 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc20813a1c0, 0xbebc200, 0xc20816a690, 0xc2081f42a0, 0xc20809c820)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:104 +0x109
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:82 +0x31a

goroutine 54 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReap(0xc2080d6000)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1333 +0x1b4
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:364 +0x1289

goroutine 55 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReconnect(0xc2080d6000)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1349 +0xc7
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:365 +0x12a7

goroutine 56 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d6000, 0xadfa10, 0x6, 0xc20809f500)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:366 +0x12e5

goroutine 57 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d6000, 0xaddf50, 0x5, 0xc20809f530)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:367 +0x1326

goroutine 58 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d6000, 0xae3530, 0x5, 0xc20809f560)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:368 +0x1367

goroutine 60 [select]:
github.com/hashicorp/consul/consul.(*Server).lanEventHandler(0xc20811a2c0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/serf.go:37 +0x3ae
created by github.com/hashicorp/consul/consul.NewServer
  /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:240 +0xc6c

goroutine 61 [select]:
github.com/hashicorp/serf/serf.(*serfQueries).stream(0xc20809fe00)
  /opt/gopath/src/github.com/hashicorp/serf/serf/internal_query.go:80 +0x238
created by github.com/hashicorp/serf/serf.newSerfQueries
  /opt/gopath/src/github.com/hashicorp/serf/serf/internal_query.go:73 +0x9f

goroutine 62 [select]:
github.com/hashicorp/serf/serf.(*Snapshotter).stream(0xc20803e160)
  /opt/gopath/src/github.com/hashicorp/serf/serf/snapshot.go:175 +0x890
created by github.com/hashicorp/serf/serf.NewSnapshotter
  /opt/gopath/src/github.com/hashicorp/serf/serf/snapshot.go:123 +0x510

goroutine 63 [IO wait]:
net.runtime_pollWait(0x7f0e191ddc78, 0x72, 0x0)
  /opt/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20816a840, 0x72, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20816a840, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20816a7e0, 0xc43d00, 0x0, 0x7f0e191dc440, 0xb)
  /opt/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803c0c0, 0xc2080ba030, 0x0, 0x0)
  /opt/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
github.com/hashicorp/memberlist.(*Memberlist).tcpListen(0xc20813a2a0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:173 +0x2b
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:121 +0xa3b

goroutine 64 [IO wait]:
net.runtime_pollWait(0x7f0e191ddb18, 0x72, 0x0)
  /opt/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20816a8b0, 0x72, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20816a8b0, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).readFrom(0xc20816a850, 0xc20817c000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f0e191dc440, 0xb)
  /opt/go/src/pkg/net/fd_unix.go:269 +0x3db
net.(*UDPConn).ReadFromUDP(0xc20803c0c8, 0xc20817c000, 0x10000, 0x10000, 0x436faa, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/udpsock_posix.go:67 +0x129
net.(*UDPConn).ReadFrom(0xc20803c0c8, 0xc20817c000, 0x10000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/udpsock_posix.go:82 +0x142
github.com/hashicorp/memberlist.(*Memberlist).udpListen(0xc20813a2a0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:235 +0x2a4
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:122 +0xa59

goroutine 65 [select]:
github.com/hashicorp/memberlist.(*Memberlist).udpHandler(0xc20813a2a0)
  /opt/gopath/src/github.com/hashicorp/memberlist/net.go:320 +0x2d8
created by github.com/hashicorp/memberlist.newMemberlist
  /opt/gopath/src/github.com/hashicorp/memberlist/memberlist.go:123 +0xa77

goroutine 66 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc20813a2a0, 0x12a05f200, 0xc20816abd0, 0xc2081f46c0, 0xc20809d750)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:98 +0x14a
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:70 +0x151

goroutine 67 [select]:
github.com/hashicorp/memberlist.(*Memberlist).pushPullTrigger(0xc20813a2a0, 0xc2081f46c0)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:122 +0x196
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:76 +0x269

goroutine 68 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc20813a2a0, 0x1dcd6500, 0xc20816ac40, 0xc2081f46c0, 0xc20809d760)
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:98 +0x14a
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
  /opt/gopath/src/github.com/hashicorp/memberlist/state.go:82 +0x31a

goroutine 69 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReap(0xc2080d61a0)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1333 +0x1b4
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:364 +0x1289

goroutine 70 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReconnect(0xc2080d61a0)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1349 +0xc7
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:365 +0x12a7

goroutine 71 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d61a0, 0xadfa10, 0x6, 0xc2081e5020)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:366 +0x12e5

goroutine 72 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d61a0, 0xaddf50, 0x5, 0xc2081e5050)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:367 +0x1326

goroutine 73 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc2080d61a0, 0xae3530, 0x5, 0xc2081e5080)
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:1439 +0x3f1
created by github.com/hashicorp/serf/serf.Create
  /opt/gopath/src/github.com/hashicorp/serf/serf/serf.go:368 +0x1367

goroutine 75 [select]:
github.com/hashicorp/consul/consul.(*Server).wanEventHandler(0xc20811a2c0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/serf.go:69 +0x281
created by github.com/hashicorp/consul/consul.NewServer
  /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:249 +0xddf

goroutine 76 [IO wait]:
net.runtime_pollWait(0x7f0e191dde88, 0x72, 0x0)
  /opt/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208038530, 0x72, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208038530, 0x0, 0x0)
  /opt/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc2080384d0, 0xc43d00, 0x0, 0x7f0e191dc440, 0xb)
  /opt/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc2080ba0f8, 0x60fdc4, 0x0, 0x0)
  /opt/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc2080ba0f8, 0x0, 0x0, 0x0, 0x0)
  /opt/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/hashicorp/consul/consul.(*Server).listen(0xc20811a2c0)
  /opt/gopath/src/github.com/hashicorp/consul/consul/rpc.go:47 +0x55
created by github.com/hashicorp/consul/consul.NewServer
  /opt/gopath/src/github.com/hashicorp/consul/consul/server.go:252 +0xdf7

goroutine 77 [select]:
github.com/hashicorp/consul/command/agent.(*Agent).handleEvents(0xc2080cec80)
  /opt/gopath/src/github.com/hashicorp/consul/command/agent/user_event.go:114 +0x25d
created by github.com/hashicorp/consul/command/agent.Create
  /opt/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:135 +0x694

```

**Comment by tj** [comment]
Just realized the bin was from HEAD that's probably the problem haha.. confirming..

**Comment by tj** [comment]
s'all good, sorry for the noise. That's what I get for forgetting to checkout the tag!
