### ISSUE TITLE
Consul agent goes to panic when used words in health checks start from uppercase.

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/consul#6870]
#### Overview of the Issue

Consul agent goes to panic when used words in checks start from uppercase.
The behavior has changed since version consul 1.0.0, tested with 0.8.4, 0.9.4 and 1.6.2.

I think consul client don't should go to panic, but exit with an error.

#### Reproduction Steps

Create a check like this:

```{
    "services": [
        {
            "Address": "127.0.0.1",
            "Checks": [
                {
                    "Id": "portCheck",
                    "Interval": "1s",
                    "Name": "TCP Health check",
                    "Tcp": "127.0.0.1:3306"
                },
                {
                    "Id": "mysqlHealthCheck",
                    "Interval": "20s",
                    "Name": "MySQL Health Check",
                    "Script": "echo 0"
                }
            ],
            "ID": "mysql-1",
            "Name": "mysql-1",
            "Port": 3306,
            "Tags": [
                "mysql"
            ]
        }
    ]
}
```

run consul agent:
`consul agent -config-dir=/opt/hashicorp/consul.d -config-dir=/var/opt/hashicorp/consul/checks.d -data-dir=/var/opt/hashicorp/consul/data -config-file=/opt/hashicorp/consul/etc/consul-client.json`

### Operating system and Environment details

Red Hat  7.6

### Log Fragments

```
panic: services.Checks: []map[string]interface{} with more than one element not supported: [map[Name:TCP Health check Tcp:127.0.0.1:3306 Interval:1s Id:portCheck] map[Id:mysqlHealthCheck Name:MySQL Health Check Script:echo 0 Interval:20s]]

goroutine 1 [running]:
github.com/hashicorp/consul/agent/config.patchValue(0xc42064ba30, 0xf, 0x10c1000, 0xc4206a3820, 0xc4205ffab8, 0x6, 0x6, 0xc42064ba30, 0xf)
	/gopath/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:42 +0xb2c
github.com/hashicorp/consul/agent/config.patchValue(0xc42064b9d0, 0x8, 0x11b9060, 0xc420678a80, 0xc4205ffab8, 0x6, 0x6, 0xc4206956d0, 0x19)
	/gopath/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:24 +0x181
github.com/hashicorp/consul/agent/config.patchValue(0xc42064b9d0, 0x8, 0x10c1000, 0xc4206a3840, 0xc4205ffab8, 0x6, 0x6, 0xc4200d7607, 0xc4200d7606)
	/gopath/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:34 +0x405
github.com/hashicorp/consul/agent/config.patchValue(0x0, 0x0, 0x11b9060, 0xc420678a50, 0xc4205ffab8, 0x6, 0x6, 0x0, 0xc420688c60)
	/gopath/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:24 +0x181
github.com/hashicorp/consul/agent/config.patchSliceOfMaps(0xc420678a50, 0xc4205ffab8, 0x6, 0x6, 0xc42025ebe8)
	/gopath/src/github.com/hashicorp/consul/agent/config/patch_hcl.go:8 +0x61
github.com/hashicorp/consul/agent/config.Parse(0xc4200d6dc0, 0x2a5, 0x142eab2, 0x4, 0x0, 0xc420670ad0, 0xc420571980, 0xc4205719c0, 0x0, 0xc42064afe8, ...)
	/gopath/src/github.com/hashicorp/consul/agent/config/config.go:80 +0x238
github.com/hashicorp/consul/agent/config.(*Builder).Build(0xc4201e1800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/hashicorp/consul/agent/config/builder.go:273 +0x8a3
github.com/hashicorp/consul/agent/config.(*Builder).BuildAndValidate(0xc4201e1800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/hashicorp/consul/agent/config/builder.go:212 +0x93
github.com/hashicorp/consul/command/agent.(*cmd).readConfig(0xc4201e1000, 0x41ea06)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:100 +0x156
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc4201e1000, 0xc4200ae020, 0x5, 0x5, 0x0)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:301 +0x8b
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc4201e1000, 0xc4200ae020, 0x5, 0x5, 0xc4202bde00)
	/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:77 +0x50
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc42027ed80, 0xc42027ed80, 0x40, 0xc4203100c0)
	/gopath/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.realMain(0xc42009a058)
	/gopath/src/github.com/hashicorp/consul/main.go:52 +0x3ee
main.main()
	/gopath/src/github.com/hashicorp/consul/main.go:19 +0x22
```

**Comment by crhino** [comment]
Hi @Nmishin. You are right in that setting `Checks` with an uppercase `C` causes the client to panic. Although this used to work pre-1.0.0, it is now expected behavior to fail in this scenario, given that we require `snake_case` in config files, [see here](https://www.consul.io/docs/agent/services.html#service-definition-parameter-case).

There is potential for a better error message rather than a panic, I agree. How much pain is this panic message causing you? If it is sufficiently annoying, we could look into it further.

**Comment by Nmishin** [comment]
Hi @crhino, thank you for the fast reply. I spent about 2-3 hours on investigating this.
I'm not sure, do we need to update the code base, but at least need to add some notice about changing behavior to the [Upgrading Specific Versions](https://www.consul.io/docs/upgrade-specific.html#consul-1-0)
I prepared the PR but some check is failed state ... 
Could you check it, please?

**Comment by chowmean** [comment]
@crhino created a PR for this https://github.com/hashicorp/consul/pull/6883. Please suggest if this is correct or there are other changes required.

**Comment by jsosulska** [comment]
#6878 has been merged. Closing issues.
