### ISSUE TITLE
Strange panics on 1.6.2

### ISSUE THREAD

**Issue by imcitius** [hashicorp/consul#6892]
Hello

I recently setup a new application cluster with consul 1.6.1.
The cluster is very same as few dozens of same clusters I manage, but I getting random consul cluster malfunctions.

Seeking into consul logs on servers side, I found these panics:

```
Dec 06 09:22:34 consul-0 consul[24512]: 2019/12/06 09:22:34 [INFO]  raft: aborting pipeline replication to peer {Voter a55e737c-0abb-1d5e-0273-c7b534b0b86f 192.168.124.186:8300}
Dec 06 09:22:34 consul-0 consul[24512]: panic: runtime error: index out of range
Dec 06 09:22:34 consul-0 consul[24512]: goroutine 169 [running]:
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/consul/logger.(*LogFile).pruneFiles(0xc00047d3b0, 0x0, 0x0)
Dec 06 09:22:34 consul-0 consul[24512]: /home/circleci/project/consul/logger/logfile.go:110 +0x231
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/consul/logger.(*LogFile).rotate(0xc00047d3b0, 0x2f42dd8, 0xc00047d418)
Dec 06 09:22:34 consul-0 consul[24512]: /home/circleci/project/consul/logger/logfile.go:88 +0x71
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/consul/logger.(*LogFile).Write(0xc00047d3b0, 0xc000700dc0, 0x8a, 0x282, 0x0, 0x0, 0x0)
Dec 06 09:22:34 consul-0 consul[24512]: /home/circleci/project/consul/logger/logfile.go:133 +0xc6
Dec 06 09:22:34 consul-0 consul[24512]: io.(*multiWriter).Write(0xc0006e01c0, 0xc000700dc0, 0x8a, 0x282, 0x0, 0xc0004cae00, 0x22bdf603)
Dec 06 09:22:34 consul-0 consul[24512]: /usr/local/go/src/io/multi.go:60 +0x87
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/go-hclog.(*writer).Flush(0xc00013f980, 0xbf72a55600000003, 0x4e94d6bc8c0a, 0x51db8e0)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/go-hclog@v0.9.2/writer.go:21 +0x13c
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/go-hclog.(*intLogger).Log(0xc0007574a0, 0xc000000003, 0xc00016e380, 0x67, 0x0, 0x0, 0x0)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/go-hclog@v0.9.2/intlogger.go:115 +0x13b
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/go-hclog.(*intLogger).Info(0xc0007574a0, 0xc00016e380, 0x67, 0x0, 0x0, 0x0)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/go-hclog@v0.9.2/intlogger.go:400 +0x65
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/raft.(*Raft).pipelineReplicate(0xc000250000, 0xc000bc8780, 0x0, 0x0)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/replication.go:456 +0x894
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/raft.(*Raft).replicate(0xc000250000, 0xc000bc8780)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/replication.go:183 +0x29d
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/raft.(*Raft).startStopReplication.func1()
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/raft.go:488 +0x33
Dec 06 09:22:34 consul-0 consul[24512]: github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000250000, 0xc0001c6520)
Dec 06 09:22:34 consul-0 consul[24512]: /go/pkg/mod/github.com/hashicorp/raft@v1.1.1/state.go:146 +0x53
Dec 06 09:22:34 consul-0 consul[24512]: created by github.com/hashicorp/raft.(*raftState).goFunc
Dec 06 09:22:34 consul-0 systemd[1]: consul.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 06 09:22:34 consul-0 systemd[1]: Unit consul.service entered failed state.
Dec 06 09:22:34 consul-0 systemd[1]: consul.service failed.
```

I tried to upgrade cluster to 1.6.2, but its not helped.
I do not know how to reproduce it, because it is very random, 1-2 occurrences per day.
Could this be a bug?

### Operating system and Environment details

Centos 7, amd64

**Comment by i0rek** [comment]
Thank you for reporting, this looks serious, we will be looking into this!

**Comment by imcitius** [comment]
Downgraded the cluster to 1.5.3 and got this instead (agent's log):

```
Dec 08 20:51:47 iron-prod2-pgsql-05 consul[131103]: panic: runtime error: index out of range
Dec 08 20:51:47 iron-prod2-pgsql-05 consul[131103]: goroutine 182 [running]:
Dec 08 20:51:47 iron-prod2-pgsql-05 consul[131103]: github.com/hashicorp/consul/logger.(*LogFile).pruneFiles(0xc000225180, 0x0, 0x0)
Dec 08 20:51:47 iron-prod2-pgsql-05 consul[131103]: /home/circleci/project/consul/logger/logfile.go:110 +0x231
```

**Comment by imcitius** [comment]
I suppose, log rotation settings could be related to the issue, (due to `logger.(*LogFile).pruneFiles`), so here it is:
```
    "log_file": "/var/log/consul/consul.log",
    "log_level": "INFO",
    "log_rotate_bytes": 1073741824,
    "log_rotate_duration": "24h",
    "log_rotate_max_files": -1,
```

Now I'm trying change to 
```
    "enable_syslog": true,
    "log_level": "INFO",
```

And see what happens then.
