### ISSUE TITLE
Panic upgrading from 1.6.3 -> 1.7.0-beta4

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#7223]
When upgrading Consul from OSS 1.6.3 to 1.7.0-ent-beta4 the Consul server panics:

```
2020-02-05T00:56:56.856Z [INFO]  agent.server: New leader elected: payload=consul-server-0
panic: failed to decode request: codec.decoder: readContainerLen: Unrecognized descriptor byte: hex: 85, dec: 133
goroutine 53 [running]:
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).applyConnectCAOperation(0xc0008dacc0, 0xc0003e0001, 0xcf, 0xcf, 0x8, 0x0, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/commands_oss.go:307 +0xcf3
github.com/hashicorp/consul/agent/consul/fsm.New.func1(0xc0003e0001, 0xcf, 0xcf, 0x8, 0x0, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/fsm.go:90 +0x56
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).Apply(0xc0008dacc0, 0xc0004ee0a0, 0xc000bc0660, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/fsm.go:125 +0x2c0
github.com/hashicorp/go-raftchunking.(*ChunkingFSM).Apply(0xc000748000, 0xc0004ee0a0, 0x616d540, 0xc00012dc90)
	/go/pkg/mod/github.com/hashicorp/go-raftchunking@v0.6.1/fsm.go:66 +0x5b
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0002e6ac0)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:90 +0x273
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc0002c8c00, 0x40, 0x40)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc00004e600)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:219 +0x3af
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc00004e600, 0xc0001a4610)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:144 +0x66
```

Notes:
* No panic occurs upgrading from 1.6.3 -> 1.6.3-ent
* A panic also occurs upgrading from 1.6.3 -> 1.7.0-ent-beta3

**Comment by rboyer** [comment]
Reproduction steps that work for me:
```
$ mkdir out
$ consul-1.6.3 agent -server -bootstrap -data-dir=./out -bind 127.0.0.1 -hcl 'connect {enabled = true }'
```
In another terminal:
```
$ for i in $(seq 200); do curl -sL localhost:8500/v1/agent/connect/ca/leaf/foo$i; done > /dev/null
```
Back in the first terminal, Ctrl-C consul:
```
$ consul-1.7.0+ent-beta4 agent -server -bootstrap -data-dir=./dd -bind 127.0.0.1 -hcl 'connect {enabled = true }'
    2020-02-05T12:41:55.188-0600 [INFO]  agent.server: New leader elected: payload=babyshark
panic: failed to decode request: codec.decoder: readContainerLen: Unrecognized descriptor byte: hex: 85, dec: 133

goroutine 27 [running]:
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).applyConnectCAOperation(0xc00016d380, 0xc00005c0d1, 0xcf, 0xcf, 0x5, 0x0, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/commands_oss.go:307 +0xcf3
github.com/hashicorp/consul/agent/consul/fsm.New.func1(0xc00005c0d1, 0xcf, 0xcf, 0x5, 0x0, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/fsm.go:90 +0x56
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).Apply(0xc00016d380, 0xc00018f450, 0xc0007153e0, 0x0)
	/home/circleci/project/consul-enterprise/agent/consul/fsm/fsm.go:125 +0x2c0
github.com/hashicorp/go-raftchunking.(*ChunkingFSM).Apply(0xc0006a81e0, 0xc00018f450, 0x616d540, 0xc0006e5c90)
	/go/pkg/mod/github.com/hashicorp/go-raftchunking@v0.6.1/fsm.go:66 +0x5b
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000530350)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:90 +0x273
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00009e600, 0x40, 0x40)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc0002a0c00)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/fsm.go:219 +0x3af
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0002a0c00, 0xc000222f40)
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc
	/go/pkg/mod/github.com/hashicorp/raft@v1.1.2/state.go:144 +0x66
```

**Comment by rboyer** [comment]
It also panics from `1.6.3 -> 1.7.0-beta4` (oss-to-oss)

**Comment by i0rek** [comment]
git bisect has spoken:

```
45d57ca6010cc83a57da37d98c96bc5d13dea5ed is the first bad commit
commit 45d57ca6010cc83a57da37d98c96bc5d13dea5ed
Author: Paul Banks <banks@banksco.de>
Date:   Mon Nov 11 20:57:16 2019 +0000

    connect: Allow CA Providers to store small amount of state (#6751)
```

**Comment by rboyer** [comment]
The `structs.CAConfiguration` type picked up a `MarshalBinary/UnmarshalBinary` pair of functions, to slightly control how the data is serialized. Unfortunately this was backwards incompatible and the new implementation doesn't generate the same leading bytes. Example of before/after:

```
// header for CAConfiguration not using MarshalBinary (1.6.x)
([]uint8) (len=91) {
 00000000  86 a9 43 6c 75 73 74 65  72 49 44 a3 61 62 63 a6  |..ClusterID.abc.|

// header for CAConfiguration using MarshalBinary (1.7.x)
([]uint8) (len=101) {
 00000000  da 00 62 87 a9 43 6c 75  73 74 65 72 49 44 a3 61  |..b..ClusterID.a|
```

**Comment by mkeeler** [comment]
We automatically generate binary marshallers for protobuf types now, so we might need to find a way to selectively disable that.

**Comment by rboyer** [comment]
I think the same bug actually exists in AuthMethods as of `663cf1e9a8`

**Comment by rboyer** [comment]
I don't currently see a way to backwards-compatibly msgpack encode/decode slightly differently, especially not with the binary marshal/unmarshal hooks.

**Comment by mkeeler** [comment]
It looks like in 1.6.x we had `86 <real data>` and in 1.7.0 we have `da 00 62 87 <real data>` but the real data looks the same.

**Comment by mkeeler** [comment]
This is one of those times not being on the upstream ugorji/go is biting us. If so we would have these structs define the `Selfer` interface and all should just work. I think the issue is that we are creating new encoders.
