### ISSUE TITLE
Consul does not boot anymore - "Assertion 'rc == 0' failed in mdb_page_dirty()"

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/consul#731]
```
/opt/gopath/src/github.com/armon/gomdb/mdb.c:1763: Assertion 'rc == 0' failed in mdb_page_dirty()
SIGABRT: abort
PC=0x7f09dca50cc9
signal arrived during cgo execution

goroutine 16 [syscall]:
runtime.cgocall(0x403bf0, 0xc2080aceb8)
	/opt/go/src/pkg/runtime/cgocall.c:143 +0xe5 fp=0xc2080acea0 sp=0xc2080ace58
github.com/armon/gomdb._Cfunc_mdb_txn_commit(0x28820c0, 0x0)
	github.com/armon/gomdb/_obj/_cgo_defun.c:349 +0x31 fp=0xc2080aceb8 sp=0xc2080acea0
github.com/armon/gomdb.(*Txn).Commit(0xc20802e528, 0x0, 0x0)
	/opt/gopath/src/github.com/armon/gomdb/txn.go:66 +0x3c fp=0xc2080acef0 sp=0xc2080aceb8
github.com/hashicorp/raft-mdb.(*MDBStore).Set(0xc2080a9d40, 0x105ca68, 0xb, 0xb, 0xc2080af550, 0x8, 0x8, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/raft-mdb/mdb_store.go:315 +0x1d9 fp=0xc2080acfb8 sp=0xc2080acef0
github.com/hashicorp/raft-mdb.(*MDBStore).SetUint64(0xc2080a9d40, 0x105ca68, 0xb, 0xb, 0x15655, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/raft-mdb/mdb_store.go:337 +0xa3 fp=0xc2080ad020 sp=0xc2080acfb8
github.com/hashicorp/raft.(*Raft).setCurrentTerm(0xc208130000, 0x15655)
	/opt/gopath/src/github.com/hashicorp/raft/raft.go:1522 +0x89 fp=0xc2080ad0c0 sp=0xc2080ad020
github.com/hashicorp/raft.NewRaft(0xc208004e40, 0x7f09dd1e30e8, 0xc2080fec90, 0x7f09dd1e3120, 0xc2080a9d40, 0x7f09dd1e3170, 0xc2080a9d40, 0x7f09dd1e31b0, 0xc2080a9dc0, 0x7f09dd1e30b8, ...)
	/opt/gopath/src/github.com/hashicorp/raft/raft.go:221 +0x98b fp=0xc2080ad228 sp=0xc2080ad0c0
github.com/hashicorp/consul/consul.(*Server).setupRaft(0xc20809d4a0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/consul/server.go:370 +0x9e0 fp=0xc2080ad490 sp=0xc2080ad228
github.com/hashicorp/consul/consul.NewServer(0xc20809d340, 0xc20809d340, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/consul/server.go:228 +0x9ea fp=0xc2080ad5e0 sp=0xc2080ad490
github.com/hashicorp/consul/command/agent.(*Agent).setupServer(0xc208045040, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:263 +0x50 fp=0xc2080ad660 sp=0xc2080ad5e0
github.com/hashicorp/consul/command/agent.Create(0xc2080df800, 0x7f09dd1e1ea8, 0xc2080a9400, 0x415a98, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/command/agent/agent.go:115 +0x4ed fp=0xc2080ad818 sp=0xc2080ad660
github.com/hashicorp/consul/command/agent.(*Command).setupAgent(0xc2080515e0, 0xc2080df800, 0x7f09dd1e1ea8, 0xc2080a9400, 0xc2080b98f0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:256 +0xd4 fp=0xc2080ad990 sp=0xc2080ad818
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc2080515e0, 0xc20800e020, 0x2, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/command/agent/command.go:468 +0xa82 fp=0xc2080adcf0 sp=0xc2080ad990
github.com/mitchellh/cli.(*CLI).Run(0xc208051540, 0xc208051540, 0x0, 0x0)
	/opt/gopath/src/github.com/mitchellh/cli/cli.go:100 +0x3a1 fp=0xc2080addb8 sp=0xc2080adcf0
main.realMain(0x4120ee)
	/opt/gopath/src/github.com/hashicorp/consul/main.go:37 +0x2fb fp=0xc2080adf40 sp=0xc2080addb8
main.main()
	/opt/gopath/src/github.com/hashicorp/consul/main.go:12 +0x1e fp=0xc2080adf50 sp=0xc2080adf40
runtime.main()
	/opt/go/src/pkg/runtime/proc.c:247 +0x11a fp=0xc2080adfa8 sp=0xc2080adf50
runtime.goexit()
	/opt/go/src/pkg/runtime/proc.c:1445 fp=0xc2080adfb0 sp=0xc2080adfa8
created by _rt0_go
	/opt/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 19 [finalizer wait]:
runtime.park(0x424b00, 0x107d870, 0x1068a49)
	/opt/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x107d870, 0x1068a49)
	/opt/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/opt/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/opt/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/opt/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/opt/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 23 [select]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc2080e0040)
	/opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xa8
created by github.com/armon/go-metrics.NewInmemSignal
	/opt/gopath/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x168

goroutine 24 [sleep]:
time.Sleep(0x3b9aca00)
	/opt/go/src/pkg/runtime/time.goc:39 +0x31
github.com/armon/go-metrics.(*Metrics).collectStats(0xc208019cc0)
	/opt/gopath/src/github.com/armon/go-metrics/metrics.go:67 +0x2b
created by github.com/armon/go-metrics.New
	/opt/gopath/src/github.com/armon/go-metrics/start.go:61 +0x9b

goroutine 25 [select]:
github.com/hashicorp/consul/consul.(*ConnPool).reap(0xc2080fc000)
	/opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:362 +0x48a
created by github.com/hashicorp/consul/consul.NewPool
	/opt/gopath/src/github.com/hashicorp/consul/consul/pool.go:155 +0xda

goroutine 17 [syscall]:
runtime.goexit()
	/opt/go/src/pkg/runtime/proc.c:1445

goroutine 27 [select]:
github.com/hashicorp/consul/consul.(*RaftLayer).Accept(0xc2080e0540, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/consul/consul/raft_rpc.go:56 +0x14d
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208005020)
	/opt/gopath/src/github.com/hashicorp/raft/net_transport.go:339 +0x4f
created by github.com/hashicorp/raft.NewNetworkTransport
	/opt/gopath/src/github.com/hashicorp/raft/net_transport.go:135 +0x1c9

rax     0x0
rbx     0x7fffe37331f0
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x4eb9
rsi     0x4eb9
rbp     0x2881e80
rsp     0x7fffe37330a8
r8      0x7f09dd211740
r9      0x6761705f62646d20
r10     0x8
r11     0x202
r12     0x6
r13     0x28820c0
r14     0x2881e80
r15     0x0
rip     0x7f09dca50cc9
rflags  0x202
cs      0x33
fs      0x0
gs      0x0

```

**Comment by armon** [comment]
Hmm this looks like a bug in LMDB. I can try to report upstream, but this is out of my league.

**Comment by lyrixx** [comment]
Hm, I already reported a similar bug: https://github.com/hashicorp/consul/issues/509

I still use consul v0.4.1 though.

BTW, I had to delete the whole content of "data-dir" :( Hopefully I deployed 3 servers node. But, To be very honest, I really like consul, but sometime it afraid me a lot (you can see [my issues](https://github.com/hashicorp/consul/issues/created_by/lyrixx))

**Comment by armon** [comment]
@lyrixx I understand. We are actively migrating away from LMDB because of issues like these. The next major release will not use LMDB for data storage.

**Comment by lyrixx** [comment]
@armon I'm happy to hear that ;) What are you going to use?

**Comment by ryanbreen** [comment]
https://github.com/hashicorp/raft-boltdb

It's inspired by LMDB but is pure Go, so it won't require cgo.  Should make issues less opaque and also open the door for cross-compilation.

**Comment by lyrixx** [comment]
@ryanbreen Thanks ;)

**Comment by hyc** [comment]
armon, how many issues like this have you encountered? This is the first I've heard of any problems. You should have contacted upstream sooner.

**Comment by lyrixx** [comment]
I only met this error once.

**Comment by armon** [comment]
@hyc This is the first time I've seen this particular issue.

**Comment by hyc** [comment]
@armon I guess I was looking for the more general - how many LMDB-specific issues have you encountered. But now I see you were on 0.9.11 for a long time. Your issue #509 sounds like our ITS#7815 that was fixed in 0.9.12. Still, we would have investigated if you had let us know you were having problems.

**Comment by armon** [comment]
@hyc Honestly LMDB has been mostly very trouble free and great for us. The main difficulties are it forces us to use cgo and cross-compilation becomes much more challenging. There have been very few bugs, and the performance is still higher than boltdb, even including the penalty LMDB pays due to the cgo boundary.

The switch is being done for a few reasons:
* The assumption of data size being larger than memory is mostly a non-issue for Consul
* The main catalog is not persisted to disk anyways (we use the LMDB flags to avoid flushing)
* Using LMDB causes us to serialize/deserialize and the pressure on the GC is too high

On the negative side, we have benchmarked boltdb and know it to be slower (10-15%) but this only affects the write performance which is already high enough. Real-world Consul deploys just don't do 4K+ writes/sec.

**Comment by hyc** [comment]
Ah, sure, I understand the portability gain from being pure Go. Makes sense.

**Comment by lyrixx** [comment]
I updated consul to v0.5.0 ; I'm closing this one, until it happens again.

Thanks all for your feedback
