### ISSUE TITLE
cannot expose multiple paths with service-defaults

### ISSUE THREAD

**Issue by rrondeau** [hashicorp/consul#7602]
Hi

I can not expose multiple path with service-defaults config entry.
When using this config :
```
{
  "Kind": "service-defaults",
  "Protocol": "http",
  "Name": "my-service",
  "Expose": {
    "Paths": [
      {
        "LocalPathPort": "8080",
        "Path": "/healthz",
        "Protocol": "http",
        "ListenerPort": 20001
      },
      {
        "LocalPathPort": "8080",
        "Path": "/metrics",
        "Protocol": "http",
        "ListenerPort": 9100
      }
    ]
  }
}
```
I get this :
```
panic: Expose.Paths: []map[string]interface{} with more than one element not supported: [map[ListenerPort:%!s(float64=20001) LocalPathPort:8080 Path:/healthz Protocol:http] map[ListenerPort:%!s(float64=9100) LocalPathPort:8080 Path:/metrics Protocol:http]]

goroutine 1 [running]:
github.com/hashicorp/consul/lib.patchValue(0xc00031a320, 0xc, 0x279c880, 0xc0010b47e0, 0x50d2cc8, 0x0, 0x0, 0x50d2cc8, 0x0, 0x0, ...)
	/home/circleci/project/consul/lib/patch_hcl.go:56 +0xc5a
github.com/hashicorp/consul/lib.patchValue(0xc00031a318, 0x6, 0x2945160, 0xc001098b40, 0x50d2cc8, 0x0, 0x0, 0x50d2cc8, 0x0, 0x0, ...)
	/home/circleci/project/consul/lib/patch_hcl.go:35 +0x1ab
github.com/hashicorp/consul/lib.patchValue(0x0, 0x0, 0x2945160, 0xc001098b10, 0x50d2cc8, 0x0, 0x0, 0x50d2cc8, 0x0, 0x0, ...)
	/home/circleci/project/consul/lib/patch_hcl.go:35 +0x1ab
github.com/hashicorp/consul/lib.PatchSliceOfMaps(0xc001098b10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/consul/lib/patch_hcl.go:20 +0x1fc
github.com/hashicorp/consul/command/config/write.newDecodeConfigEntry(0xc001098b10, 0xc00000e4e8, 0xc00011d040, 0x185, 0x0)
	/home/circleci/project/consul/command/config/write/config_write.go:142 +0x18e
github.com/hashicorp/consul/command/config/write.parseConfigEntry(0xc00011d040, 0x185, 0x0, 0x0, 0xc00011d040, 0x185)
	/home/circleci/project/consul/command/config/write/config_write.go:109 +0xf8
github.com/hashicorp/consul/command/config/write.(*cmd).Run(0xc0000b3ae0, 0xc00004c0f0, 0x1, 0x1, 0xc000479a60)
	/home/circleci/project/consul/command/config/write/config_write.go:68 +0x192
github.com/mitchellh/cli.(*CLI).Run(0xc00046cdc0, 0xc00046cdc0, 0x80, 0xc000479ba0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.realMain(0xc000098058)
	/home/circleci/project/consul/main.go:53 +0x393
main.main()
	/home/circleci/project/consul/main.go:20 +0x22
```
Maybe i am doing something wrong here but the docs say the `Paths` key is an array of path objects.
https://www.consul.io/docs/agent/config-entries/service-defaults.html#paths

I am using Consul v1.7.1.

Thanks

**Comment by freddygv** [comment]
Hi @rrondeau

Thanks for the report. You're definitely not doing anything wrong. This is an issue with decoding the slice of path structs.

Unfortunately the only workaround available is to declare the paths in the service definition of each proxy, as shown [here](https://www.consul.io/docs/connect/registration/service-registration.html#expose-paths-configuration-reference).

I have a PR out with the fix, and it will be included in the next release. I expect Consul 1.7.3 should be out before the end of April.

PR: #7611
