### ISSUE TITLE
autoTLS on consul agent results in panic

### ISSUE THREAD

**Issue by jeroenjacobs79** [hashicorp/consul#7635]
#### Overview of the Issue

I have 3 Consul servers running, and they seem to work fine. When adding an agent, it crashes with the following error:

````
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.073Z [INFO]  agent: Joining cluster...: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.073Z [INFO]  agent: discover-aws: Address type  is not supported. Valid values are {private_v4,public_v4,public_v6}. Falling back to 'private_v4': cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.073Z [INFO]  agent: discover-aws: Region not provided. Looking up region in metadata...: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.074Z [WARN]  agent.client.manager: No servers available
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.074Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.074Z [WARN]  agent.client.manager: No servers available
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.074Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.075Z [INFO]  agent: discover-aws: Region is eu-west-1: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.075Z [INFO]  agent: discover-aws: Filter instances with ConsulCluster=hic-infra-consul: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.170Z [INFO]  agent: discover-aws: Instance i-065cc99a5e7d98691 has private ip 10.9.10.53: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.170Z [INFO]  agent: discover-aws: Instance i-0f81df8b9431b4df8 has private ip 10.9.11.166: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.170Z [INFO]  agent: discover-aws: Instance i-0e94be6155c555fd0 has private ip 10.9.12.245: cluster=LAN
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.170Z [INFO]  agent: Discovered servers: cluster=LAN cluster=LAN servers="10.9.10.53 10.9.11.166 10.9.12.245"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.170Z [INFO]  agent: (LAN) joining: lan_addresses=[10.9.10.53, 10.9.11.166, 10.9.12.245]
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: ip-10-9-12-245 10.9.12.245
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: ip-10-9-11-166 10.9.11.166
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [WARN]  agent.client.memberlist.lan: memberlist: Refuting an alive message for 'ip-10-9-10-145' (10.9.10.145:8301) meta:([255 137 167 115 101 103 109 101 110 116 160 163 118 115 110 161 50 167 118 115 110 95 109 105 110 161 50 167 118 115 110 95 109 97 120 161 51 165 98 117 105 108 100 174 49 46 55 46 50 58 57 101 97 49 97 50 48 52 164 97 99 108 115 161 48 164 114 111 108 101 164 110 111 100 101 162 100 99 177 104 111 115 116 105 110 103 45 101 117 45 119 101 115 116 45 49 162 105 100 218 0 36 54 97 101 98 49 50 54 98 45 51 97 57 52 45 54 56 53 55 45 52 56 49 53 45 101 52 54 102 56 57 48 48 97 57 50 55] VS [255 137 164 114 111 108 101 164 110 111 100 101 162 105 100 218 0 36 54 97 101 98 49 50 54 98 45 51 97 57 52 45 54 56 53 55 45 52 56 49 53 45 101 52 54 102 56 57 48 48 97 57 50 55 163 118 115 110 161 50 167 118 115 110 95 109 105 110 161 50 164 97 99 108 115 161 48 162 100 99 177 104 111 115 116 105 110 103 45 101 117 45 119 101 115 116 45 49 167 115 101 103 109 101 110 116 160 167 118 115 110 95 109 97 120 161 51 165 98 117 105 108 100 174 49 46 55 46 50 58 57 101 97 49 97 50 48 52]), vsn:([1 5 2 2 5 4] VS [1 5 2 2 5 4])
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: ip-10-9-10-53 10.9.10.53
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client: adding server: server="ip-10-9-12-245 (Addr: tcp/10.9.12.245:8300) (DC: hosting-eu-west-1)"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client: adding server: server="ip-10-9-11-166 (Addr: tcp/10.9.11.166:8300) (DC: hosting-eu-west-1)"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.176Z [INFO]  agent.client: adding server: server="ip-10-9-10-53 (Addr: tcp/10.9.10.53:8300) (DC: hosting-eu-west-1)"
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.180Z [INFO]  agent: (LAN) joined: number_of_nodes=3
Apr 11 12:36:44 ip-10-9-10-145 consul: 2020-04-11T12:36:44.180Z [INFO]  agent: Join cluster completed. Synced with initial agents: cluster=LAN num_agents=3
Apr 11 12:36:44 ip-10-9-10-145 consul: panic: runtime error: invalid memory address or nil pointer dereference
Apr 11 12:36:44 ip-10-9-10-145 consul: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4602ac]
Apr 11 12:36:44 ip-10-9-10-145 consul: goroutine 67 [running]:
Apr 11 12:36:44 ip-10-9-10-145 consul: crypto/tls.(*clientHandshakeStateTLS13).sendClientCertificate(0xc00063adc8, 0x0, 0x0)
Apr 11 12:36:44 ip-10-9-10-145 consul: /usr/local/go/src/crypto/tls/handshake_client_tls13.go:540 +0x129
Apr 11 12:36:44 ip-10-9-10-145 consul: crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc00063adc8, 0xc0007f6240, 0x0)
Apr 11 12:36:44 ip-10-9-10-145 consul: /usr/local/go/src/crypto/tls/handshake_client_tls13.go:91 +0x230
Apr 11 12:36:44 ip-10-9-10-145 consul: crypto/tls.(*Conn).clientHandshake(0xc00006ee00, 0x0, 0x0)
Apr 11 12:36:44 ip-10-9-10-145 consul: /usr/local/go/src/crypto/tls/handshake_client.go:198 +0x49e
Apr 11 12:36:44 ip-10-9-10-145 consul: crypto/tls.(*Conn).Handshake(0xc00006ee00, 0x0, 0x0)
Apr 11 12:36:44 ip-10-9-10-145 consul: /usr/local/go/src/crypto/tls/conn.go:1362 +0x12b
Apr 11 12:36:44 ip-10-9-10-145 consul: crypto/tls.(*Conn).Write(0xc00006ee00, 0xc0006e1f48, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr 11 12:36:44 ip-10-9-10-145 consul: /usr/local/go/src/crypto/tls/conn.go:1094 +0xb7
Apr 11 12:36:44 ip-10-9-10-145 consul: github.com/hashicorp/consul/agent/pool.(*ConnPool).getNewConn(0xc000156070, 0xc000645fa0, 0x11, 0x35ee760, 0xc000584510, 0x2, 0x7f368ded3601, 0x0, 0x11, 0xc0000a8998)
Apr 11 12:36:44 ip-10-9-10-145 consul: /home/circleci/project/consul/agent/pool/pool.go:349 +0x118
Apr 11 12:36:44 ip-10-9-10-145 consul: github.com/hashicorp/consul/agent/pool.(*ConnPool).acquire(0xc000156070, 0xc000645fa0, 0x11, 0x35ee760, 0xc000584510, 0x2, 0xc000156001, 0x10, 0xc00068b1b8, 0x47c352)
Apr 11 12:36:44 ip-10-9-10-145 consul: /home/circleci/project/consul/agent/pool/pool.go:228 +0x4d1
Apr 11 12:36:44 ip-10-9-10-145 consul: github.com/hashicorp/consul/agent/pool.(*ConnPool).getClient(0xc000156070, 0xc000645fa0, 0x11, 0x35ee760, 0xc000584510, 0x2, 0x2ca3b201, 0x1, 0xc00004e550, 0x1, ...)
Apr 11 12:36:44 ip-10-9-10-145 consul: /home/circleci/project/consul/agent/pool/pool.go:406 +0x9b
Apr 11 12:36:44 ip-10-9-10-145 consul: github.com/hashicorp/consul/agent/pool.(*ConnPool).rpc(0xc000156070, 0xc000645fa0, 0x11, 0x35ee760, 0xc000584510, 0x2, 0x3068b0d, 0x17, 0x1, 0x2fce6e0, ...)
Apr 11 12:36:44 ip-10-9-10-145 consul: /home/circleci/project/consul/agent/pool/pool.go:462 +0xb6
Apr 11 12:36:44 ip-10-9-10-145 consul: github.com/hashicorp/consul/agent/pool.(*ConnPool).RPC(0xc000156070, 0xc000645fa0, 0x11, 0x35ee760, 0xc000584510, 0x2, 0x3068b0d, 0x17, 0x6874202c64656901, 0x2fce6e0, ...)
Apr 11 12:36:44 ip-10-9-10-145 consul: /home/circleci/project/consul/agent/pool/pool.go:432 +0xfa
````

#### Reproduction Steps

I'm using Consul 1.7.2 on both agents and servers.

This is client config:

````
{
  "datacenter": "hosting-eu-west-1",
  "node_name": "ip-10-9-10-145",
  "rejoin_after_leave": true,
  "domain": "consul",
  "bind_addr": "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}",
  "log_level": "info",
  "retry_join": ["provider=aws tag_key=ConsulCluster tag_value=hic-infra-consul"],
  "leave_on_terminate": true,

  "server": false,

  "connect": {
      "enabled": true
  },

  "node_meta": {
    "instance_type": "t3.small",
    "region": "eu-west-1",
    "arch": "x86_64",
    "availability_zone": "eu-west-1a",
    "image_id": "ami-0713f98de93617bb4",
    "instance_id": "i-070369d40031640d5"
  },

  "encrypt": "<redacted>",

  "data_dir": "/var/lib/consul",
  "disable_remote_exec": true,

  "ports": {
    "grpc": 8502,
    "https": 8501,
    "http": -1
  },

  "verify_outgoing": true,
  "verify_incoming": false,
  "verify_server_hostname": true,

  "auto_encrypt": {
    "allow_tls": true
  },

  "ca_file": "/etc/consul-ssl/ecdsa_consul_ca.pem",

  "enable_local_script_checks": true
}
````
This is config file of the servers:

````
{
  "datacenter": "hosting-eu-west-1",
  "node_name": "ip-10-9-11-166",
  "rejoin_after_leave": true,
  "domain": "consul",
  "bind_addr": "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}",
  "log_level": "info",
  "retry_join": ["provider=aws tag_key=ConsulCluster tag_value=hic-infra-consul"],
  "leave_on_terminate": true,

  "server": true,
  "bootstrap_expect": 3,

  "connect": {
      "enabled": true
  },

  "node_meta": {
    "instance_type": "t3.small",
    "region": "eu-west-1",
    "arch": "x86_64",
    "availability_zone": "eu-west-1b",
    "image_id": "ami-0713f98de93617bb4",
    "instance_id": "i-0f81df8b9431b4df8"
  },

  "encrypt": "<redacted>",

  "data_dir": "/var/lib/consul",
  "disable_remote_exec": true,

  "ports": {
    "grpc": 8502,
    "https": 8501,
    "http": -1
  },

  "verify_outgoing": true,
  "verify_incoming": true,
  "verify_server_hostname": true,

  "auto_encrypt": {
    "allow_tls": true
  },

  "key_file": "/etc/consul-ssl/consul_server-key.pem",
  "cert_file": "/etc/consul-ssl/consul_server.pem",
  "ca_file": "/etc/consul-ssl/ecdsa_consul_ca.pem",

  "enable_local_script_checks": true
}
````

### Consul info for both Client and Server

Both run 1.7.2

```
no output from client 'consul info' as it crashes
```

</details>

<details>
  <summary>Server info</summary>

```
[root@ip-10-9-11-166 ec2-user]# /opt/consul/consul info -http-addr=https://localhost:8501 -ca-file=/etc/consul-ssl/ecdsa_consul_ca.pem -client-cert=/etc/consul-ssl/consul_server.pem -client-key /etc/consul-ssl/consul_server-key.pem
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 9ea1a204
	version = 1.7.2
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.9.11.166:8300
	server = true
raft:
	applied_index = 667321
	commit_index = 667321
	fsm_pending = 0
	last_contact = 0
	last_log_index = 667321
	last_log_term = 4
	last_snapshot_index = 655463
	last_snapshot_term = 2
	latest_configuration = [{Suffrage:Voter ID:23027446-49d8-58a4-34ff-4fa90a0d8d80 Address:10.9.10.53:8300} {Suffrage:Voter ID:46ff731b-594e-3420-e074-061378435dee Address:10.9.11.166:8300} {Suffrage:Voter ID:dc30d1d9-6236-50af-2e39-00d2371f9c17 Address:10.9.12.245:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 4
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 109
	max_procs = 2
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 21
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 12
	members = 4
	query_queue = 0
	query_time = 1
[root@ip-10-9-11-166 ec2-user]#
```

</details>

### Operating system and Environment details

AWS Linux v2, amd64

### Log Fragments

See above.

**Comment by jeroenjacobs79** [comment]
I also tried with 1.6.4 on a fresh cluster, and it also results in a similar crash

**Comment by jeroenjacobs79** [comment]
This is the x509 information of both the CA certifcate , as the server certificate (in case this information helps).

ca cert:

````
openssl x509 -in ecdsa_consul_ca.pem -text                                                                                                                                                                   [±master ●●]
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            55:e0:dd:8d:79:bf:22:2a:dd:86:a9:f7:b9:ee:44:4d:71:f0:86:f4
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=US, ST=Consul, L=Consul, O=hosting-eu-west-1, CN=Consul Root CA
        Validity
            Not Before: Feb  8 11:16:00 2020 GMT
            Not After : Feb  1 11:16:00 2045 GMT
        Subject: C=US, ST=Consul, L=Consul, O=hosting-eu-west-1, CN=Consul Root CA
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:ba:4a:ad:9e:58:04:e7:60:a2:94:1d:98:2e:17:
                    6a:ba:66:d8:14:02:73:68:0f:bf:50:cd:63:86:f8:
                    b3:e1:bf:1a:06:f9:56:df:aa:cf:03:39:cc:80:ce:
                    71:3c:fe:a6:c2:5f:5d:47:51:8e:a5:4f:49:b1:6a:
                    2d:14:35:8e:31
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                8B:B5:58:86:0B:01:93:EF:18:07:DC:77:1B:D9:E4:8D:E0:84:BD:1D
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:09:13:52:7d:c9:dc:ab:72:95:01:a3:14:1c:ed:
         4b:01:37:f5:a5:f1:05:ff:34:fe:5f:51:61:6b:38:91:56:bb:
         02:20:0e:a8:58:30:18:11:f3:dc:8c:4e:65:82:1b:1c:03:d9:
         eb:2a:da:1b:60:8c:8c:6d:28:75:fe:10:de:f6:09:ac
-----BEGIN CERTIFICATE-----
MIICCzCCAbKgAwIBAgIUVeDdjXm/Iirdhqn3ue5ETXHwhvQwCgYIKoZIzj0EAwIw
ZDELMAkGA1UEBhMCVVMxDzANBgNVBAgTBkNvbnN1bDEPMA0GA1UEBxMGQ29uc3Vs
MRowGAYDVQQKExFob3N0aW5nLWV1LXdlc3QtMTEXMBUGA1UEAxMOQ29uc3VsIFJv
b3QgQ0EwHhcNMjAwMjA4MTExNjAwWhcNNDUwMjAxMTExNjAwWjBkMQswCQYDVQQG
EwJVUzEPMA0GA1UECBMGQ29uc3VsMQ8wDQYDVQQHEwZDb25zdWwxGjAYBgNVBAoT
EWhvc3RpbmctZXUtd2VzdC0xMRcwFQYDVQQDEw5Db25zdWwgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABLpKrZ5YBOdgopQdmC4Xarpm2BQCc2gPv1DN
Y4b4s+G/Ggb5Vt+qzwM5zIDOcTz+psJfXUdRjqVPSbFqLRQ1jjGjQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSLtViGCwGT7xgH
3Hcb2eSN4IS9HTAKBggqhkjOPQQDAgNHADBEAiAJE1J9ydyrcpUBoxQc7UsBN/Wl
8QX/NP5fUWFrOJFWuwIgDqhYMBgR89yMTmWCGxwD2esq2htgjIxtKHX+EN72Caw=
-----END CERTIFICATE-----
````

server cert:

````
openssl x509 -in consul-server.pem -text                                                                                                                                                                     [±master ●●]
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            70:59:b3:fd:aa:ce:0e:e7:b0:93:3c:85:58:eb:af:af:6a:2c:35:98
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=US, ST=Consul, L=Consul, O=hosting-eu-west-1, CN=Consul Root CA
        Validity
            Not Before: Feb  8 12:34:00 2020 GMT
            Not After : Feb  6 12:34:00 2025 GMT
        Subject: C=US, ST=Consul, L=Consul, O=hosting-eu-west-1, CN=server.hosting-eu-west-1.consul
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:f1:5e:5f:ff:aa:58:36:a9:d4:52:de:e3:bc:57:
                    de:4c:5a:dc:89:a2:f2:6b:7f:9b:57:14:a7:7d:28:
                    19:d4:97:73:52:65:c5:97:92:43:9a:54:fa:91:c4:
                    02:38:bf:12:4b:30:a0:28:11:ba:65:c9:fa:ff:e3:
                    98:53:a0:83:07
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                8A:D1:06:7F:F5:EF:8E:09:94:B5:47:23:0A:30:FB:F2:33:CC:69:66
            X509v3 Authority Key Identifier:
                keyid:8B:B5:58:86:0B:01:93:EF:18:07:DC:77:1B:D9:E4:8D:E0:84:BD:1D

            X509v3 Subject Alternative Name:
                DNS:server.hosting-eu-west-1.consul, DNS:localhost, IP Address:127.0.0.1
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:b2:a0:cf:48:b0:e2:71:5e:a2:a0:cc:89:87:
         3e:c9:1d:d5:7e:76:00:c8:45:84:be:9a:2a:16:42:de:e8:9f:
         4b:02:21:00:f7:15:c4:8f:37:99:92:65:c0:f2:c9:32:b0:ec:
         2d:d8:9a:0f:a2:2d:5f:13:a9:3a:c1:de:3c:be:d8:13:7e:30
-----BEGIN CERTIFICATE-----
MIICmjCCAj+gAwIBAgIUcFmz/arODuewkzyFWOuvr2osNZgwCgYIKoZIzj0EAwIw
ZDELMAkGA1UEBhMCVVMxDzANBgNVBAgTBkNvbnN1bDEPMA0GA1UEBxMGQ29uc3Vs
MRowGAYDVQQKExFob3N0aW5nLWV1LXdlc3QtMTEXMBUGA1UEAxMOQ29uc3VsIFJv
b3QgQ0EwHhcNMjAwMjA4MTIzNDAwWhcNMjUwMjA2MTIzNDAwWjB1MQswCQYDVQQG
EwJVUzEPMA0GA1UECBMGQ29uc3VsMQ8wDQYDVQQHEwZDb25zdWwxGjAYBgNVBAoT
EWhvc3RpbmctZXUtd2VzdC0xMSgwJgYDVQQDEx9zZXJ2ZXIuaG9zdGluZy1ldS13
ZXN0LTEuY29uc3VsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8V5f/6pYNqnU
Ut7jvFfeTFrciaLya3+bVxSnfSgZ1JdzUmXFl5JDmlT6kcQCOL8SSzCgKBG6Zcn6
/+OYU6CDB6OBvTCBujAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFIrRBn/1744JlLVH
Iwow+/IzzGlmMB8GA1UdIwQYMBaAFIu1WIYLAZPvGAfcdxvZ5I3ghL0dMDsGA1Ud
EQQ0MDKCH3NlcnZlci5ob3N0aW5nLWV1LXdlc3QtMS5jb25zdWyCCWxvY2FsaG9z
dIcEfwAAATAKBggqhkjOPQQDAgNJADBGAiEAsqDPSLDicV6ioMyJhz7JHdV+dgDI
RYS+mioWQt7on0sCIQD3FcSPN5mSZcDyyTKw7C3Ymg+iLV8TqTrB3jy+2BN+MA==
-----END CERTIFICATE-----
````

Since my servers are in an auto-scaling group, the server-key, server-cert, and ca-cert are shared between instances.

Since Consul does not verify CN's except the server.<datacenter>.consul CN, this shouldn't be a problem I think.

**Comment by jeroenjacobs79** [comment]
Duplicate of https://github.com/hashicorp/consul/issues/7407

**Comment by i0rek** [comment]
@jeroenjacobs79 thanks for reporting. Since it is a duplicate, does that mean that your issue is resolved now too? I will add a check for the config options soon, so that consul errors out if the the wrong auto_encrypt config is used for clients or servers.

**Comment by jeroenjacobs79** [comment]
Hello,

Yes, it is resolved :) Replaced `allow_tls` by `tls` on the client, and everything started working as expected ;-)
