### ISSUE TITLE
Consul UI behind Nginx proxy doesn't work

### ISSUE THREAD

**Issue by maplewf** [hashicorp/consul#7928]
**Old UI or New UI**
Consul 1.7.3 UI

**Describe the problem you're having**
I'm using Consul 1.7.3 and want to put its UI behind Nginx proxy for integrating with our own web services.  But no matter what I configured, it just didn't work. Consul always show the Error page like below:
```
Error

Consul returned an error. You may have visited a URL that is loading an unknown resource, so you can try going back to the root or try re-submitting your ACL Token/SecretID by going back to ACLs.
Try looking in our documentation
```
The browser console report following error:
```
Error while processing route: dc.kv.folder e.map is not a function TypeError: e.map is not a function
    at r.normalizePayload (http://192.168.18.99/consul/assets/consul-ui-80219c43077ea818f035ddb261cd9256.js:1172:34)
    at r.normalizeResponse (http://192.168.18.99/consul/assets/consul-ui-80219c43077ea818f035ddb261cd9256.js:1165:12)
    at r [as normalizeResponse] (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:3018:9)
    at Pe (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:7179:68)
    at http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:7195:76
    at w (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5076:12)
    at _ (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5074:128)
    at t.invoke (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4609:163)
    at e.t.flush (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4601:74)
    at e.t.flush (http://192.168.18.99/consul/assets/vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4614:358)
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2680
error @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2680
O @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2690
c.triggerEvent @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2621
t.trigger @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4876
c.transitionDidError @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2621
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4867
w @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5076
_ @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5074
v @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5072
t.invoke @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4609
t.flush @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4601
t.flush @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4614
r._end @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4676
_boundAutorunEnd @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4626
Promise.then (async)
n @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4585
r._scheduleAutorun @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4690
r._ensureInstance @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4688
r.schedule @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4647
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:2778
g @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5072
p @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5069
m @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5072
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5097
success @ consul-ui-80219c43077ea818f035ddb261cd9256.js:1241
u @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:949
fireWith @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:950
A @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:1230
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:1240
load (async)
send @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:1240
ajax @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:1218
(anonymous) @ consul-ui-80219c43077ea818f035ddb261cd9256.js:1245
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5097
e @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5097
(anonymous) @ consul-ui-80219c43077ea818f035ddb261cd9256.js:1240
requestForFindAll @ consul-ui-80219c43077ea818f035ddb261cd9256.js:26
(anonymous) @ consul-ui-80219c43077ea818f035ddb261cd9256.js:37
request @ consul-ui-80219c43077ea818f035ddb261cd9256.js:1235
a @ consul-ui-80219c43077ea818f035ddb261cd9256.js:37
findAll @ consul-ui-80219c43077ea818f035ddb261cd9256.js:53
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:7194
w @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5076
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:5083
t.invoke @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4609
t.flush @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4601
t.flush @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4614
r._end @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4676
r.end @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4631
r._run @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4678
r._join @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4677
r.join @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:4642
h @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:3492
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:3495
l @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:956
c @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:957
setTimeout (async)
(anonymous) @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:958
u @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:949
fireWith @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:950
fire @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:950
u @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:949
fireWith @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:950
ready @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:967
H @ vendor-5b94eb6a11bff93d1247a342ee40dbf8.js:967
``` 

Here comes my configuration:

- Consul agent command line:
```
/usr/bin/consul agent -server -node consul-server -client 0.0.0.0 -ui -ui-content-path /consul/ -bind 127.0.0.1 -bootstrap-expect 1 -data-dir /etc/consul/data -config-dir /etc/consul/consul.d
```
- nginx proxy:
```
    location /consul {
        proxy_pass http://127.0.0.1:8500;
        proxy_set_header Host $host;
        proxy_redirect off;
```

BTW, configuration above uses the `-ui-content-path` to change the prefix of url, but the same error still happen when I fallback to use the default prefix `/ui/`.

**Comment by johncowen** [comment]
Hi @maplewf 

Thanks for reporting this!

I have a couple of questions to help me to figure out what is happening here:

1. What browser are you using?
2. Does the UI work when you are not using nginx?
3. Is it just the KV page that errors, i.e. can you use the anything at all in the UI?

I actually have a theory as to what is happening here, but if you can come back to me on the above that would be great!

Thanks,

**Comment by maplewf** [comment]
Hi @johncowen 

Thanks for reply. I'm sorry to miss these details in my first description.

About browser, the error message above comes from Chrome, but the same error happened on Microsoft Edge, Firefox and IE too

Consul UI works fine if it's not behind the proxy.

The error happened on all subpages of consul UI

best regards.

**Comment by johncowen** [comment]
Perfect! Thankyou for that. Would it be possible to pass over a screengrab of what you are seeing in the WebInspector > [Network] > [XHR] tab? Similar to the screengrab you can see at the bottom of this issue https://github.com/hashicorp/consul/issues/7927 (Network tab)

**Comment by maplewf** [comment]
Here comes:

![image](https://user-images.githubusercontent.com/18524415/82445534-9106a780-9ad7-11ea-8bf4-6d0b46d23ce7.png)

![image](https://user-images.githubusercontent.com/18524415/82445582-a7146800-9ad7-11ea-9a79-ec77e5e62cc9.png)

![image](https://user-images.githubusercontent.com/18524415/82445661-cad7ae00-9ad7-11ea-90ba-7ccbc5fd5593.png)

**Comment by maplewf** [comment]
Hi @johncowen,

Any update? Do you have any clue about what cause it? Is there any workaround here? Thanks in advance.

best regards

**Comment by johncowen** [comment]
Hi @maplewf 

Sorry for the the delay, we had a release go out Thursday and we've had long weekend.

I've tried running the UI myself via nginx and everything seems to work fine.

```
location / {
        proxy_pass http://127.0.0.1:8500;
        proxy_set_header Host $host;
        proxy_redirect off;
}
```

The above config seemed to work both with and without `-ui-content-path` set.

If you to continue into problems with your deployment we generally redirect folks to our [Forum](https://discuss.hashicorp.com/c/consul/29) for help.

**Comment by maplewf** [comment]
Hi @johncowen 

It also works for me with your configuration, but unfortunately, most of reverse proxy will use prefix, could you please try the nginx configuration below:

```
location /ui {
        proxy_pass http://127.0.0.1:8500;
        proxy_set_header Host $host;
        proxy_redirect off;
}
``` 

this is configuration which cause the problem, or is there any special requirement for consul to use prefix in reverse proxy?

best regards

**Comment by johncowen** [comment]
Hey @maplewf 

I think it's the fact that you want to reverse proxy the entire UI plus API to `/somewhere-else`. The API cannot be moved from `/v1` currently. It always has to be at the root.

You can run the UI `/somewhere-else` using the `-ui-content-path` setting. But the API must always be present at `/v1`.

Does that sound like it might explain what you are running in to?

For example if I add:

```
location /consul {
        proxy_pass http://127.0.0.1:8500;
        proxy_set_header Host $host;
        proxy_redirect off;
}
location /v1 {
        proxy_pass http://127.0.0.1:8500;
        proxy_set_header Host $host;
        proxy_redirect off;
}
```

This also works, but `/v1` always has to be at `/v1`.

Generally we suggest using subdomains for this (if I understand what you are trying to do correctly)

**Comment by johncowen** [comment]
Actually @maplewf , I'm going to pass something by the rest of the team today and see if we can improve this slightly. I can't guarantee anything but I'll come back here and let you know the outcome. Just in case, currently at least, my previous comment still stands.

Thanks for your patience

**Comment by maplewf** [comment]
Hi @johncowen 

Thanks for your great help. If I understand right, it means that I not only need to proxy the UI but also need to proxy the API. I think I can accept your configuration right now since I have no `/v1` path in my web service yet, but it easily lead to conflict.

Besides, how to use subdomain in consul to fix this problem more gracefully as you mentioned?

best regards.

**Comment by johncowen** [comment]
Hi @maplewf 

Just to keep you up to date, yesterday I spoke to the rest of the team briefly about this.

The outcome of that is we are going to investigate making the `-ui-content-path` setting to prefix the `/v1` API url. Doing this potentially could have other consequences as this is essentially a change in existing functionality.

If we cannot do this then we spoke about the potential of adding further settings to the UI when running consul to enable users/operators to configure things like this.

My main reasoning for coming back to you here is to let you know that it nothing will be changing in the immediate term, so if you can work around this in the meantime with subdomains or similar that might be better for you.

Slightly longer term, I can come back here to update any changes towards this.

Thanks,

**Comment by maplewf** [comment]
Hi @johncowen,

Thanks for your great support. I understand current situation. It's OK for me to use the configuration mentioned above to work this problem around. Besides, could you please share how to use subdomain way in consul to fix the problem? Thanks.

best regards.

**Comment by johncowen** [comment]
Hi @maplewf 

Setting up a subdomain in Nginx isn't something specific to consul, I would guess if you take a look at the Nginx documentation you would get a better explanation of setting up subdomains in Nginx then you would from me!

I am guessing the outcome would be that you would serve the ui at something like `https://consul.domain-name/ui` which would contact the API at `https://consul.domain-name/v1`.

Our community forums are another good place to ask about things like this:

https://discuss.hashicorp.com/c/consul/29

As many people have similar usecases.

**Comment by blake** [comment]
For those watching this issue, a workaround for this was shared in #11627 which you can consider using Consul adds support for running the UI behind a  proxied sub-path.
