### ISSUE TITLE
HTTP API on client becomes unresponsive if registration is attempted with an unresponsive leader

### ISSUE THREAD

**Issue by ghicks-rmn** [hashicorp/consul#795]
This is an oddly specific case, and may not actually be a 'bug', but is reproducible on my system:
* Create a cluster of 3 Consul servers using Docker containers.
* Add a client node to the cluster.
* Pause the leader container and immediately after register a service on the client:
```bash
docker pause consul1; docker exec consul_client curl -i -s -X PUT -d '{"Name" "testservice3"}' http://localhost:8500/v1/agent/service/register
```
* Register a second service on the client:
```bash
docker exec consul_client curl -i -s -X PUT -d '{"Name" "testservice4"}' http://localhost:8500/v1/agent/service/register
```
* Unpause the original cluster leader (consul1).

The first registration attempt will return 200 OK, but the DNS record will not appear anywhere.
The second registration attempt (and apparently all other calls to the HTTP API) will freeze indefinitely.
When the original leader is unpaused, both service registrations will propagate and be visible in DNS.

I realize this could be caused in part by testing with "pause", but I suspect that this may be exposing a race condition that hasn't been addressed yet:
* consul1 (leader) becomes unresponsive
* consul_client passes a registration request to consul1 before a new leader is chosen (or possibly before it finds out that consul1 is no longer leader)
* consul_client ends up in a 'stuck' state of some kind dependent on consul1

I'm still investigating the implications of this, as I find out more I will add to this issue. I'm seeing this on consul version 0.5.0.

**Comment by armon** [comment]
Are there multiple server nodes available?

The registration is done async, so it will work even if the leader is paused/dead. When the leader recovers the agent performs anti-entropy to bring everything back into sync. WRT being "stuck", there is probably an indefinitely (or very long) TCP timeout when dialing the server, which is unable to respond due to being paused.

**Comment by ghicks-rmn** [comment]
@armon Sorry for the delayed response. Yes, multiple server nodes are available in the case I described - I created a cluster of three server nodes, each one a separate Docker container; consul1 is the leader in the scenario, the other two start as followers but one is promoted to leader when "docker pause" is applied to consul1. Other than pausing the leader, it's a normal three-node server cluster, implemented as containers.

If the issue is an arbitrarily long or indefinite TCP timeout, wouldn't this problem also occur if a network partition occurred in a real-world environment? Specifically:
1. consul1 loses connection to the cluster
2. consul_client1 tries to register a service before it learns that consul1 is down
3. consul_client1 waits, possibly indefinitely, for consul1 to respond
4. consul_client1 blocks on all HTTP API calls until it's restarted or the network partition is resolved

Let me know if you need any more information about the test case.

**Comment by armon** [comment]
Hmm this requires some more investigation. This doesn't happen in the real-world, so my guess is there is something particular about this setup. For example, the sockets are all local host, so TCP is never timing out since the OS knows both ends of the socket are alive.

**Comment by xakraz** [comment]
Hello, I am doing the same tests that @ghicks-rmn and ran into the same issues.

Any updates ?
What kind of information should we provide to help ?

**Comment by slackpad** [comment]
Hi @xakraz which version of Consul are you using? Consul 0.6.0 added some fixes that allow it to detect failed TCP connections more quickly and attempt reconnection.

**Comment by xakraz** [comment]
@slackpad : I am running Consul 0.5.2 currently, but I will test with the latest Consul 0.6.2 today and keep you posted. Thx for the lead !

**Comment by xakraz** [comment]
Hi @slackpad ,

I finally managed to test consul 0.5.2 vs the latest 0.6.3 and you are right, it has been fixed (at least in the latest version).

So I guess I will have to update all my servers know :p

### Consul 0.5.2

```ruby
$ rspec --format doc --color

cluster is set up
  server 'consul_am5_server_1'
    http 'http://10.0.4.182:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_am5_server_2'
    http 'http://10.0.4.164:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_am5_server_3'
    http 'http://10.0.4.183:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_am5_client_1'
    http 'http://10.0.4.142:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_am5_client_1'
version is : Node                 Address           Status  Type    Build  Protocol  DC
consul-am5-client-1  172.18.2.21:8301  alive   client  0.5.2  2         am5
consul-am5-server-1  172.18.2.11:8301  alive   server  0.5.2  2         am5
consul-am5-server-2  172.18.2.12:8301  alive   server  0.5.2  2         am5
consul-am5-server-3  172.18.2.13:8301  alive   server  0.5.2  2         am5
    Shows the Consul cluster topology
    http 'http://10.0.4.142:8500/v1/status/leader' with {:params=>{}, :method=>:get, :headers=>{}}
Leader is : "172.18.2.11:8300"
      returns that it has a leader


When the current cluster leader becomes unreachable
  server 'consul_am5_client_1'
Leader_pre is : "172.18.2.11:8300"
kill_leaders_network: Start
kill_leaders_network: DONE
Sleeping 10s
Leader_post is : "172.18.2.12:8300"
    gets a new leader
restore_leaders_network: Start
restore_leaders_network: DONE


Agent HTTP API - During servers cluster issue
  Agent endpoint: '/v1/agent/'
    server 'consul_am5_client_1'
sleeping 5
      can register service 'example'
sleeping 5
      has registered service 'example'
sleeping 5
      Service 'example' has been published to the Catalog
sleeping 5
      can deregister service 'example'
kill_leaders_network: Start
kill_leaders_network: DONE
      Kill current leader network: Network partition

RSpec::Retry: 2nd try ./spec/cluster_spec.rb:263
RSpec::Retry: 3rd try ./spec/cluster_spec.rb:263
      can register service 'example' (FAILED - 1)

RSpec::Retry: 2nd try ./spec/cluster_spec.rb:271
RSpec::Retry: 3rd try ./spec/cluster_spec.rb:271
      has registred service 'example' (FAILED - 2)

RSpec::Retry: 2nd try ./spec/cluster_spec.rb:282
RSpec::Retry: 3rd try ./spec/cluster_spec.rb:282
RSpec::Retry: 4th try ./spec/cluster_spec.rb:282
RSpec::Retry: 5th try ./spec/cluster_spec.rb:282
RSpec::Retry: 6th try ./spec/cluster_spec.rb:282
RSpec::Retry: 7th try ./spec/cluster_spec.rb:282
RSpec::Retry: 8th try ./spec/cluster_spec.rb:282
RSpec::Retry: 9th try ./spec/cluster_spec.rb:282
RSpec::Retry: 10th try ./spec/cluster_spec.rb:282
RSpec::Retry: 11th try ./spec/cluster_spec.rb:282
RSpec::Retry: 12th try ./spec/cluster_spec.rb:282
RSpec::Retry: 13th try ./spec/cluster_spec.rb:282
RSpec::Retry: 14th try ./spec/cluster_spec.rb:282
RSpec::Retry: 15th try ./spec/cluster_spec.rb:282
RSpec::Retry: 16th try ./spec/cluster_spec.rb:282
RSpec::Retry: 17th try ./spec/cluster_spec.rb:282
RSpec::Retry: 18th try ./spec/cluster_spec.rb:282
RSpec::Retry: 19th try ./spec/cluster_spec.rb:282
RSpec::Retry: 20th try ./spec/cluster_spec.rb:282
      Service 'example' has been published to the Catalog (FAILED - 3)
restore_leaders_network: Start
restore_leaders_network: DONE
      Restore old leader network: Network partition

RSpec::Retry: 2nd try ./spec/cluster_spec.rb:297
RSpec::Retry: 3rd try ./spec/cluster_spec.rb:297
RSpec::Retry: 4th try ./spec/cluster_spec.rb:297
RSpec::Retry: 5th try ./spec/cluster_spec.rb:297
RSpec::Retry: 6th try ./spec/cluster_spec.rb:297
RSpec::Retry: 7th try ./spec/cluster_spec.rb:297
RSpec::Retry: 8th try ./spec/cluster_spec.rb:297
RSpec::Retry: 9th try ./spec/cluster_spec.rb:297
RSpec::Retry: 10th try ./spec/cluster_spec.rb:297
RSpec::Retry: 11th try ./spec/cluster_spec.rb:297
      WARNING: Service 'example' has been published to the Catalog afer all ...
After all
restore_leaders_network: Start
restore_leaders_network: DONE
sleeping 5

Failures:

  1) Agent HTTP API - During servers cluster issue Agent endpoint: '/v1/agent/' server 'consul_am5_client_1' can register service 'example'
     Failure/Error: response = @consul_client.put("http://#{client.address}:8500/v1/agent/service/register?token=#{master_token}", body)
     HTTPClient::ReceiveTimeoutError:
       execution expired
     # ./spec/cluster_spec.rb:265:in `block (5 levels) in <top (required)>'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'

  2) Agent HTTP API - During servers cluster issue Agent endpoint: '/v1/agent/' server 'consul_am5_client_1' has registred service 'example'
     Failure/Error: response = @consul_client.get("http://#{client.address}:8500/v1/agent/services")
     HTTPClient::ReceiveTimeoutError:
       execution expired
     # ./spec/cluster_spec.rb:272:in `block (5 levels) in <top (required)>'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'

  3) Agent HTTP API - During servers cluster issue Agent endpoint: '/v1/agent/' server 'consul_am5_client_1' Service 'example' has been published to the Catalog
     Failure/Error: expect(JSON.parse(response.body).length).to eql(1)

       expected: 1
            got: 0

       (compared using eql?)
     # ./spec/cluster_spec.rb:286:in `block (5 levels) in <top (required)>'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/vagrant/.chefdk/gem/ruby/2.1.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'

Finished in 13 minutes 25 seconds (files took 10.27 seconds to load)
16 examples, 3 failures
```

### Consul 0.6.3

```ruby
$ rspec --format doc --color --tag setup

cluster is set up
  server 'consul_par_server_1'
    http 'http://10.0.4.123:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_par_server_2'
    http 'http://10.0.4.150:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_par_server_3'
    http 'http://10.0.4.151:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_par_client_1'
    http 'http://10.0.4.138:8500/v1/agent/self' with {:params=>{}, :method=>:get, :headers=>{}}
      returns that the node is up
  server 'consul_par_client_1'
version is : Node                 Address           Status  Type    Build  Protocol  DC
consul-par-client-1  172.18.1.21:8301  alive   client  0.6.3  2         par
consul-par-server-1  172.18.1.11:8301  alive   server  0.6.3  2         par
consul-par-server-2  172.18.1.12:8301  alive   server  0.6.3  2         par
consul-par-server-3  172.18.1.13:8301  alive   server  0.6.3  2         par
    Shows the Consul cluster topology
    http 'http://10.0.4.138:8500/v1/status/leader' with {:params=>{}, :method=>:get, :headers=>{}}
Leader is : "172.18.1.11:8300"
      returns that it has a leader


Agent HTTP API - During servers cluster issue
  Agent endpoint: '/v1/agent/'
    server 'consul_par_client_1'
sleeping 5
      can register service 'example'
sleeping 5
      has registered service 'example'
sleeping 5
      Service 'example' has been published to the Catalog
sleeping 5
      can deregister service 'example'
kill_leaders_network: Start
kill_leaders_network: DONE
      Kill current leader network: Network partition
sleeping 5
      can register service 'example'
sleeping 5
      has registred service 'example'
sleeping 10
      Service 'example' has been published to the Catalog
restore_leaders_network: Start
restore_leaders_network: DONE
      Restore old leader network: Network partition
      WARNING: Service 'example' has been published to the Catalog afer all ...
After all
restore_leaders_network: Start
restore_leaders_network: DONE
sleeping 5

Finished in 1 minute 13.5 seconds (files took 8.91 seconds to load)
16 examples, 0 failures
```

**Comment by xakraz** [comment]
@slackpad Have you some other feedbacks about the issue ?

From my point of view the update to Consul 0.6.3 solve it.

**Comment by slackpad** [comment]
Hi @xakraz thanks for the follow up report - I think we can close this. There were several changes in 0.6.0 around TCP connection handling, and specifically to fix the dead connection detection so we should be good.

**Comment by aantono** [comment]
Just ran into a similar issue, except the Leaders were fine but they managed to ran out of disk space due to overfilling log files and were unable to write snapshots to disk (https://github.com/hashicorp/consul/issues/1744), so the agent registration was still timing out.  Is it possible to fix that usecase as well?
We are using consul 0.6.4
