### ISSUE TITLE
envoy/go-control-plane panic in 1.8.0

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#8155]
Following this guide: https://www.consul.io/docs/connect/wan-federation-via-mesh-gateways

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a8648a]

goroutine 182 [running]:
github.com/envoyproxy/go-control-plane/envoy/api/v2.(*Cluster).MarshalTo(0x0, 0x54519f8, 0x0, 0x0, 0x29b9f60, 0x1, 0x54519f8)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/api/v2/cds.pb.go:2912 +0x3a
github.com/envoyproxy/go-control-plane/envoy/api/v2.(*Cluster).XXX_Marshal(0x0, 0x54519f8, 0x0, 0x0, 0x0, 0x7fd47bd01701, 0x0, 0x1, 0xc0005c0600, 0xc000192640)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/api/v2/cds.pb.go:490 +0x48
github.com/gogo/protobuf/proto.Marshal(0x384bb80, 0x0, 0x6, 0xc00024efc0, 0x1, 0x0, 0x3)
	/go/pkg/mod/github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d/proto/table_marshal.go:2939 +0x2d6
github.com/hashicorp/consul/agent/xds.createResponse(0x32a5ff7, 0x28, 0xc0005c21f8, 0x8, 0xc0005c21e8, 0x8, 0xc000119700, 0x6, 0x8, 0x454d4b, ...)
	/home/circleci/project/consul/agent/xds/response.go:21 +0x3a9
github.com/hashicorp/consul/agent/xds.(*xDSType).SendIfNew(0xc0004fadc0, 0xc00031a280, 0x1, 0xc00064b930, 0xc00064bb40, 0xc0005a9201)
	/home/circleci/project/consul/agent/xds/server.go:433 +0x26a
github.com/hashicorp/consul/agent/xds.(*Server).process(0xc000292b40, 0x388dc00, 0xc000215b80, 0xc0007b85a0, 0x0, 0x0)
	/home/circleci/project/consul/agent/xds/server.go:369 +0x832
github.com/hashicorp/consul/agent/xds.(*Server).StreamAggregatedResources(0xc000292b40, 0x388dc00, 0xc000215b80, 0x382c680, 0xc000292b40)
	/home/circleci/project/consul/agent/xds/server.go:171 +0xc5
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x319c3e0, 0xc000292b40, 0x3883a60, 0xc000482fc0, 0x54519f8, 0xc00073ac00)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/service/discovery/v2/ads.pb.go:197 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0000ce160, 0x3893e40, 0xc000775380, 0xc00073ac00, 0xc0001e8420, 0x53f0360, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1199 +0xd21
google.golang.org/grpc.(*Server).handleStream(0xc0000ce160, 0x3893e40, 0xc000775380, 0xc00073ac00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1279 +0xcd6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000059520, 0xc0000ce160, 0x3893e40, 0xc000775380, 0xc00073ac00)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

**Comment by krzysztof-miemiec** [comment]
I just upgraded from `1.8.0-beta2` to `1.8.0` and experienced this issue on K8s. Mesh Gateways won't boot, because they can't connect to Consul clients. Consul clients won't boot, because they panic.

Are there any known workarounds for staying on 1.8.0, before 1.8.1 is released?

**Comment by freddygv** [comment]
HI @krzysztof-miemiec, this will happen when gateways have a hostname as the address in their service definition. Like an AWS ELB hostname.

If you instead resolve the hostname to an IP address and provide that address in the service definition, then it shouldn't panic. 

If it panics without a hostname in the service definition, then that is separate from what was fixed. In that case I would appreciate more context regarding your setup.

**Comment by lkysow** [comment]
The workaround right now would be to fork the helm chart and add the `-resolve-hostnames` flag to the `consul-k8s service-address` command here:

https://github.com/hashicorp/consul-helm/blob/685c6d5435e510e8e56aafe7ba25a05dece394c5/templates/mesh-gateway-deployment.yaml#L143-L146

**Comment by krzysztof-miemiec** [comment]
@freddygv you perfectly described my case - I run Consul on EKS and ELB hostname is used in that case for Mesh Gateways. I reverted to `1.8.0-beta2`, which works quite well in my case and will wait for official release.
