### ISSUE TITLE
Consul server cannot elect leaders due to legacy ACL

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/consul#9482]
#### Overview of the Issue

I was running my consul 1.9.0 servers since a while and then I shut them down. After turning them back online, no master are elected anymore due to this errors https://gist.github.com/Lord-Y/6c2c25732c4c3d598b2ba1b676fb7d41

#### Reproduction Steps

Steps to reproduce this issue, eg:

### Consul Server config

```
{
    "acl": {
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enable_token_persistence": true,
        "enabled": true,
        "tokens": {
            "agent": "***REDACTED***",
            "master": "***REDACTED***",
        }
    },
    "advertise_addr": "***REDACTED***",
    "auto_encrypt": {
        "allow_tls": true
    },
    "bind_addr": "0.0.0.0",
    "bootstrap_expect": 3,
    "ca_file": "***REDACTED***",
    "cert_file": "***REDACTED***",
    "client_addr": "0.0.0.0",
    "connect": {
        "enabled": true
    },
    "data_dir": "/data/consul",
    "datacenter": "euw1",
    "disable_update_check": true,
    "enable_central_service_config": true,
    "encrypt": "***REDACTED***",
    "key_file": "***REDACTED***",
    "log_level": "DEBUG",
    "node_name": "node_name",
    "performance": {
        "raft_multiplier": 1
    },
    "ports": {
        "grpc": 8502,
        "https": 8501
    },
    "retry_join": [
        "***REDACTED***",
        "***REDACTED***",
        "***REDACTED***"
    ],
    "server": true,
    "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus"
    },
    "verify_incoming": false,
    "verify_outgoing": true,
    "verify_server_hostname": true
}
```

### Consul Server info

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = a417fe51
	version = 1.9.0
consul:
	acl = legacy
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 231418
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 253663
	last_log_term = 1547
	last_snapshot_index = 231418
	last_snapshot_term = 151
	latest_configuration = [{Suffrage:Voter ID:cd5ff8e5-2583-12a5-1ca5-1fc850dda203 Address:10.1.216.20:8300} {Suffrage:Voter ID:cecac2be-cd09-3f22-a512-cc7262033177 Address:10.1.216.19:8300} {Suffrage:Voter ID:50faa8b9-5a07-df02-259c-b36963b4e897 Address:10.1.216.21:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1547
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 73
	max_procs = 1
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1388
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 14368
	members = 2
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 2014
	members = 2
	query_queue = 0
	query_time = 1
```

From few seconds, I'm able to see all 3 `consul members` and quickly go on the UI. From the UI, I don't see any legacy tokens.
Any help on how to solve this issue?
Just for debug purpose, I switch acl back to `allow`, but it doesn't help at all.

### Operating system and Environment details
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by dnephin** [comment]
Thank you for the report! The error I see repeated in the logs is this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7ad232]
goroutine 45 [running]:
github.com/hashicorp/go-immutable-radix.(*Iterator).Next(0xc00301c1a0, 0xc0034e1d00, 0x0, 0x0, 0xc000272270, 0x0, 0xffffffffffffffff)
#011/go/pkg/mod/github.com/hashicorp/go-immutable-radix@v1.3.0/iter.go:178 +0xb2
github.com/hashicorp/go-memdb.(*radixIterator).Next(0xc00007d400, 0xc002e8f480, 0x3c5d7)
#011/go/pkg/mod/github.com/hashicorp/go-memdb@v1.3.0/txn.go:895 +0x2e
github.com/hashicorp/consul/agent/consul/state.cleanupMeshTopology(0x38ed020, 0xc002e8f480, 0x3c5d7, 0xc000c3a480, 0x3c5d7, 0xc000c3a5f0)
#011/home/circleci/project/consul/agent/consul/state/catalog.go:3271 +0x36c
github.com/hashicorp/consul/agent/consul/state.(*Store).deleteServiceTxn(0xc000aa6660, 0x38ed020, 0xc002e8f480, 0x3c5d7, 0xc000bd8bc0, 0x33, 0xc0008daee0, 0x6e, 0xc000c3a5f0, 0x0, ...)
#011/home/circleci/project/consul/agent/consul/state/catalog.go:1542 +0x8c5
github.com/hashicorp/consul/agent/consul/state.(*Store).deleteNodeTxn(0xc000aa6660, 0x38ed020, 0xc002e8f480, 0x3c5d7, 0xc000bd8bc0, 0x33, 0xb2597c, 0xc000833320)
#011/home/circleci/project/consul/agent/consul/state/catalog.go:715 +0x62d
github.com/hashicorp/consul/agent/consul/state.(*Store).DeleteNode(0xc000aa6660, 0x3c5d7, 0xc000bd8bc0, 0x33, 0x0, 0x0)
#011/home/circleci/project/consul/agent/consul/state/catalog.go:648 +0xbb
```

The legacy ACL warnings may be related. Did this crash start happening as a result of changing the ACL config, or were the servers restarted with the same config?

**Comment by Lord-Y** [comment]
My original config was with ACL "allow". Then I created all required tokens/policies before switching it to "deny". I restarted them one by one an everything was working. Longtime after that, I shutted them all down and after starting them, I saw all theses errors.  As it's not yet a productuon cluster I'll trash all datas an recreate it. Maybe I'm wrong but their is no way to enforce ACL version when starting a new cluster.

**Comment by dnephin** [comment]
We've received another bug report with this same panic #9566.

That issue mentions it happened when upgrading from 1.8.6 to 1.9.1, so it sounds like this might be a bug in the 1.9.x series. I think the title of this new issue is a bit closer to the root issue, so I'm going to close this one and we can track the problem in  #9566.

Thank you again for reporting this bug!
