### ISSUE TITLE
Cannot read property 'filter' of null - ingress gateway UI

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#9535]
#### Overview of the Issue

When clicking on Upstreams tab of ingress gateway, get UI error page:

> You may have visited a URL that is loading an unknown resource, so you can try going back to the root or try re-submitting your ACL Token/SecretID by going back to ACLs.

I think the key is that the `ingress-gateway` hasn't been configured with a config entry yet.

With console error:

```
anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2147
vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2147 Error while processing route: dc.services.show.upstreams Cannot read property 'filter' of null TypeError: Cannot read property 'filter' of null
    at http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:4660:10
    at r (http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:4854:79)
    at http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:4659:243
    at m.value (http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:4364:8)
    at m.value (http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:4659:213)
    at http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:114:34
    at http://localhost:8500/ui/assets/consul-ui-96519f8950b30a9089ad266bfea83ae6.js:123:195
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2147
error @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2147
A @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2157
c.triggerEvent @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2085
t.trigger @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4578
c.transitionDidError @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2085
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4571
b @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4777
y @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4775
h @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4773
t.invoke @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4298
t.flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4290
t.flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4304
r._end @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4367
_boundAutorunEnd @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4318
Promise.then (async)
n @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4274
flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2936
r._scheduleAutorun @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4381
r._ensureInstance @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4379
r.schedule @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4339
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2244
m @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4773
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4769
Promise.then (async)
o.async.n @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4769
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4769
t.invoke @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4298
t.flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4290
t.flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4304
r._end @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4367
_boundAutorunEnd @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4318
Promise.then (async)
n @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4274
flush @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2936
r._scheduleAutorun @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4381
r._ensureInstance @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4379
r.schedule @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4339
(anonymous) @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2244
g @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4784
t.resolve @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4632
e @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4571
r.getTransitionByIntent @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4692
r.transitionByIntent @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4682
r.doTransition @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4699
r.transitionTo @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:4730
s._doURLTransition @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2105
n.transitionTo @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:1912
transitionTo @ consul-ui-96519f8950b30a9089ad266bfea83ae6.js:2415
r @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:2485
value @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:9164
value @ vendor-f1a2b1943b4d0785db0fd026c638e16b.js:9164
n @ consul-ui-96519f8950b30a9089ad266bfea83ae6.js:2394

```

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Follow this guide: https://www.consul.io/docs/k8s/connect/ingress-gateways but don't create the `ingress-gateway` config entry
2. Open up the UI to the ingress gateway service and click on Upstreams tab

Consul version 1.9.1

**Comment by johncowen** [comment]
Hey @lkysow ,

Thanks for the extra info here, helped me figure out what was going on 👍
