### ISSUE TITLE
gomdb panic

### ISSUE THREAD

**Issue by artushin** [hashicorp/consul#970]
FYI. Got this panic last night on one of our cluster nodes.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x7fe440127044 pc=0x408bbc]
runtime stack:
runtime.gothrow(0xcb38f0, 0x2a)
	/usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e
goroutine 13529 [syscall, locked to thread]:
runtime.cgocall_errno(0x4043d0, 0xc2086dd1e0, 0xc200000000)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2086dd1c0 sp=0xc2086dd198
github.com/armon/gomdb._Cfunc_mdb_cursor_get(0x7ff444001ba0, 0xc2086dd228, 0xc2086dd218, 0x9, 0xc200000000)
	/usr/local/src/github.com/armon/gomdb/:83 +0x43 fp=0xc2086dd1e0 sp=0xc2086dd1c0
github.com/armon/gomdb.(*Cursor).Get(0xc208046bd8, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/src/github.com/armon/gomdb/cursor.go:76 +0xff fp=0xc2086dd240 sp=0xc2086dd1e0
github.com/hashicorp/consul/consul.(*MDBIndex).iterate(0xc208133a00, 0xc20873ed50, 0xc20aad7720, 0x9, 0x10, 0xc2086dd450, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/mdb_table.go:711 +0xa75 fp=0xc2086dd3b0 sp=0xc2086dd240
github.com/hashicorp/consul/consul.(*MDBTable).GetTxn(0xc2081a60c0, 0xc20873ed50, 0xbc4280, 0x7, 0xc20aad76f0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/usr/local/src/github.com/hashicorp/consul/consul/mdb_table.go:396 +0x1a4 fp=0xc2086dd470 sp=0xc2086dd3b0
github.com/hashicorp/consul/consul.(*StateStore).CheckServiceNodes(0xc2080e0180, 0xc20aad7656, 0x6, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/state_store.go:1011 +0x484 fp=0xc2086dd5b0 sp=0xc2086dd470
github.com/hashicorp/consul/consul.func·014(0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/health_endpoint.go:94 +0x137 fp=0xc2086dd620 sp=0xc2086dd5b0
github.com/hashicorp/consul/consul.(*Server).blockingRPCOpt(0xc208066420, 0xc208d6e6e0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:387 +0x194 fp=0xc2086dd780 sp=0xc2086dd620
github.com/hashicorp/consul/consul.(*Server).blockingRPC(0xc208066420, 0xc2097ed598, 0xc20873ec48, 0xc2080bd4e0, 0x3, 0x3, 0xc20acc3ca0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:309 +0xdd fp=0xc2086dd7f8 sp=0xc2086dd780
github.com/hashicorp/consul/consul.(*Health).ServiceNodes(0xc208046030, 0xc2097ed560, 0xc20873ec30, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/health_endpoint.go:97 +0x403 fp=0xc2086dd928 sp=0xc2086dd7f8
runtime.call64(0xb14b90, 0xc20873ec60, 0x1800000028)
	/usr/local/go/src/runtime/asm_amd64.s:403 +0x45 fp=0xc2086dd970 sp=0xc2086dd928
reflect.Value.call(0xa69160, 0xb14b90, 0x13, 0xba58c0, 0x4, 0xc2086dddb8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5 fp=0xc2086ddc88 sp=0xc2086dd970
reflect.Value.Call(0xa69160, 0xb14b90, 0x13, 0xc2086dddb8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc fp=0xc2086ddce8 sp=0xc2086ddc88
net/rpc.(*service).call(0xc2080453c0, 0xc2080b46c0, 0xc208e45570, 0xc208132700, 0xc2097dd720, 0xb15fa0, 0xc2097ed560, 0x16, 0x964f20, 0xc20873ec30, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7 fp=0xc2086dde08 sp=0xc2086ddce8
net/rpc.(*Server).ServeRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc20a21c740, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:497 +0x2a0 fp=0xc2086ddee8 sp=0xc2086dde08
github.com/hashicorp/consul/consul.(*Server).handleConsulConn(0xc208066420, 0x7ff44c5f3638, 0xc208392140)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:169 +0x160 fp=0xc2086ddfc8 sp=0xc2086ddee8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2086ddfd0 sp=0xc2086ddfc8
created by github.com/hashicorp/consul/consul.(*Server).handleMultiplexV2
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:154 +0x320
goroutine 1 [runnable]:
syscall.Syscall(0x57, 0xc208ee6d20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.Unlink(0xc208ee6cf0, 0x2b, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1178 +0x91
os.Remove(0xc208ee6cf0, 0x2b, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:266 +0x4d
os.RemoveAll(0xc208ee6cf0, 0x2b, 0x0, 0x0)
	/usr/local/go/src/os/path.go:68 +0x5b
os.RemoveAll(0xc20814b2f0, 0x22, 0x0, 0x0)
	/usr/local/go/src/os/path.go:102 +0x45f
github.com/hashicorp/consul/consul.(*StateStore).Close(0xc2080e0180, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/state_store.go:160 +0x5d
github.com/hashicorp/consul/consul.(*consulFSM).Close(0xc208045ac0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/fsm.go:68 +0x3e
github.com/hashicorp/consul/consul.(*Server).Shutdown(0xc208066420, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/server.go:510 +0x3c0
github.com/hashicorp/consul/command/agent.(*Agent).Shutdown(0xc2080dc000, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/command/agent/agent.go:432 +0x3f5
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc2080d60b0, 0xc20800a020, 0x1, 0x1, 0x1)
	/usr/local/src/github.com/hashicorp/consul/command/agent/command.go:727 +0x24ca
github.com/mitchellh/cli.(*CLI).Run(0xc2080db040, 0xc2080b8cc0, 0x0, 0x0)
	/usr/local/src/github.com/mitchellh/cli/cli.go:100 +0x3ce
main.realMain(0x412c1f)
	/usr/local/src/github.com/hashicorp/consul/main.go:40 +0x23b
main.main()
	/usr/local/src/github.com/hashicorp/consul/main.go:12 +0x1f
goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
goroutine 7 [select, 343 minutes]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc2080b4340)
	/usr/local/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xf1
created by github.com/armon/go-metrics.NewInmemSignal
	/usr/local/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x258
goroutine 8 [runnable]:
github.com/armon/go-metrics.(*StatsdSink).flushMetrics(0xc20801f820)
	/usr/local/src/github.com/armon/go-metrics/statsd.go:104 +0x85a
created by github.com/armon/go-metrics.NewStatsdSink
	/usr/local/src/github.com/armon/go-metrics/statsd.go:32 +0xd2
goroutine 9 [sleep]:
github.com/armon/go-metrics.(*Metrics).collectStats(0xc2080ba870)
	/usr/local/src/github.com/armon/go-metrics/metrics.go:67 +0x2c
created by github.com/armon/go-metrics.New
	/usr/local/src/github.com/armon/go-metrics/start.go:61 +0xe8
goroutine 10 [runnable]:
github.com/hashicorp/consul/consul.(*ConnPool).reap(0xc2080bab40)
	/usr/local/src/github.com/hashicorp/consul/consul/pool.go:367 +0x4bb
created by github.com/hashicorp/consul/consul.NewPool
	/usr/local/src/github.com/hashicorp/consul/consul/pool.go:160 +0x165
goroutine 33 [syscall, 343 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
goroutine 12136 [IO wait]:
net.(*pollDesc).Wait(0xc20a9b6df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a9b6df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a9b6d90, 0xc2090b6000, 0x1000, 0x1000, 0x0, 0x7ff44c5e8e50, 0xc209f516f0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080bfca0, 0xc2090b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc209e78de0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc209e78de0, 0x300000002, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:196 +0x86
github.com/hashicorp/raft.(*NetworkTransport).handleCommand(0xc2080101c0, 0xc209e78de0, 0xc209e78ea0, 0xc20a9b6e70, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/raft/net_transport.go:386 +0x4e
github.com/hashicorp/raft.(*NetworkTransport).handleConn(0xc2080101c0, 0x7ff44c5f0ae8, 0xc2080bfca0)
	/usr/local/src/github.com/hashicorp/raft/net_transport.go:370 +0x278
created by github.com/hashicorp/raft.(*NetworkTransport).listen
	/usr/local/src/github.com/hashicorp/raft/net_transport.go:357 +0x34b
goroutine 3090 [select]:
github.com/hashicorp/consul/consul.(*Server).blockingRPCOpt(0xc208066420, 0xc2094cbc70, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:391 +0x35a
github.com/hashicorp/consul/consul.(*Server).blockingRPC(0xc208066420, 0xc20865f6b8, 0xc20957b968, 0xc2080bd4e0, 0x3, 0x3, 0xc2094c9920, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:309 +0xdd
github.com/hashicorp/consul/consul.(*Health).ServiceNodes(0xc208046030, 0xc20865f680, 0xc20957b950, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/health_endpoint.go:97 +0x403
reflect.Value.call(0xa69160, 0xb14b90, 0x13, 0xba58c0, 0x4, 0xc208ca3db8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xa69160, 0xb14b90, 0x13, 0xc208ca3db8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080453c0, 0xc2080b46c0, 0xc20883cce8, 0xc208132700, 0xc20831d7a0, 0xb15fa0, 0xc20865f680, 0x16, 0x964f20, 0xc20957b950, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
net/rpc.(*Server).ServeRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc209b51c00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:497 +0x2a0
github.com/hashicorp/consul/consul.(*Server).handleConsulConn(0xc208066420, 0x7ff44c5f3638, 0xc2085aac80)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:169 +0x160
created by github.com/hashicorp/consul/consul.(*Server).handleMultiplexV2
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:154 +0x320
goroutine 65 [select, 343 minutes]:
github.com/hashicorp/consul/command/agent.(*Agent).handleEvents(0xc2080dc000)
	/usr/local/src/github.com/hashicorp/consul/command/agent/user_event.go:114 +0x2cc
created by github.com/hashicorp/consul/command/agent.Create
	/usr/local/src/github.com/hashicorp/consul/command/agent/agent.go:184 +0xba2
goroutine 13589 [select]:
github.com/hashicorp/yamux.(*Stream).Read(0xc208b0a500, 0xc209020000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/yamux/stream.go:125 +0x3ab
bufio.(*Reader).fill(0xc209477020)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc209477020, 0x300000000000003, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:196 +0x86
github.com/hashicorp/go-msgpack/codec.(*ioDecReader).readn1(0xc2098e7950, 0xc208e49ae0)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/decode.go:90 +0x45
github.com/hashicorp/go-msgpack/codec.(*msgpackDecDriver).initReadNext(0xc208cce700)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:540 +0x48
github.com/hashicorp/go-msgpack/codec.(*Decoder).decode(0xc209477080, 0x971d00, 0xc208527080)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/decode.go:635 +0x59
github.com/hashicorp/go-msgpack/codec.(*Decoder).Decode(0xc209477080, 0x971d00, 0xc208527080, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/decode.go:630 +0x7f
github.com/hashicorp/go-msgpack/codec.(*rpcCodec).read(0xc209a30400, 0x971d00, 0xc208527080, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/rpc.go:88 +0xd9
github.com/hashicorp/go-msgpack/codec.(*goRpcCodec).ReadRequestHeader(0xc209a30400, 0xc208527080, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/go-msgpack/codec/rpc.go:127 +0x61
net/rpc.(*Server).readRequestHeader(0xc2080b46c0, 0x7ff44c5f3720, 0xc209a30400, 0x0, 0x0, 0xc208527080, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:575 +0x97
net/rpc.(*Server).readRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc209a30400, 0xc200000000, 0x4, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/rpc/server.go:542 +0xa2
net/rpc.(*Server).ServeRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc209a30400, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:485 +0x7f
github.com/hashicorp/consul/consul.(*Server).handleConsulConn(0xc208066420, 0x7ff44c5f3638, 0xc208b0a500)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:169 +0x160
created by github.com/hashicorp/consul/consul.(*Server).handleMultiplexV2
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:154 +0x320
goroutine 14015 [IO wait]:
net.(*pollDesc).Wait(0xc208e4b250, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208e4b250, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208e4b1f0, 0xc209e8c000, 0x2, 0xffff, 0x0, 0x7ff44c5e8e50, 0xc2085c6330)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080bf9a0, 0xc209e8c000, 0x2, 0xffff, 0x41f801, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
github.com/miekg/dns.(*Conn).Read(0xc2082d3d60, 0xc209e8c000, 0xffff, 0xffff, 0xffff, 0x0, 0x0)
	/usr/local/src/github.com/miekg/dns/client.go:231 +0x150
github.com/miekg/dns.(*Conn).ReadMsg(0xc2082d3d60, 0xc208a7abd0, 0x0, 0x0)
	/usr/local/src/github.com/miekg/dns/client.go:203 +0x128
github.com/miekg/dns.(*Client).exchange(0xc2082d35e0, 0xc208a7abd0, 0xc2095879e0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/github.com/miekg/dns/client.go:181 +0x362
github.com/miekg/dns.(*Client).Exchange(0xc2082d35e0, 0xc208a7abd0, 0xc2095879e0, 0xe, 0xffffffffffffff01, 0x4256e9, 0x0, 0x0)
	/usr/local/src/github.com/miekg/dns/client.go:108 +0x83
created by github.com/miekg/dns.(*Server).Shutdown
	/usr/local/src/github.com/miekg/dns/server.go:357 +0x4cd
goroutine 21 [select, 1 minutes]:
github.com/hashicorp/consul/command/agent.(*localState).antiEntropy(0xc2080dc030, 0xc2080c8360)
	/usr/local/src/github.com/hashicorp/consul/command/agent/local.go:323 +0x33d
created by github.com/hashicorp/consul/command/agent.(*Agent).StartSync
	/usr/local/src/github.com/hashicorp/consul/command/agent/agent.go:523 +0x4a
goroutine 1987 [select]:
github.com/hashicorp/consul/consul.(*Server).blockingRPCOpt(0xc208066420, 0xc2094caaa0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:391 +0x35a
github.com/hashicorp/consul/consul.(*Server).blockingRPC(0xc208066420, 0xc2097d2758, 0xc208eda108, 0xc2080bd4e0, 0x3, 0x3, 0xc20832cd60, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:309 +0xdd
github.com/hashicorp/consul/consul.(*Health).ServiceNodes(0xc208046030, 0xc2097d2720, 0xc208eda0f0, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/health_endpoint.go:97 +0x403
reflect.Value.call(0xa69160, 0xb14b90, 0x13, 0xba58c0, 0x4, 0xc208b25db8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xa69160, 0xb14b90, 0x13, 0xc208b25db8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080453c0, 0xc2080b46c0, 0xc208f79c70, 0xc208132700, 0xc2087bcc80, 0xb15fa0, 0xc2097d2720, 0x16, 0x964f20, 0xc208eda0f0, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
net/rpc.(*Server).ServeRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc20933f500, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:497 +0x2a0
github.com/hashicorp/consul/consul.(*Server).handleConsulConn(0xc208066420, 0x7ff44c5f3638, 0xc2093852c0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:169 +0x160
created by github.com/hashicorp/consul/consul.(*Server).handleMultiplexV2
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:154 +0x320
goroutine 13911 [select]:
github.com/hashicorp/yamux.(*Session).keepalive(0xc20a354580)
	/usr/local/src/github.com/hashicorp/yamux/session.go:279 +0x106
created by github.com/hashicorp/yamux.newSession
	/usr/local/src/github.com/hashicorp/yamux/session.go:107 +0x4de
goroutine 13909 [IO wait]:
net.(*pollDesc).Wait(0xc2094badf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2094badf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2094bad90, 0xc2095f3000, 0x1000, 0x1000, 0x0, 0x7ff44c5e8e50, 0xc2097a41b0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2089782c8, 0xc2095f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2098aaba0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2098aaba0, 0xc209a5b9a0, 0xc, 0xc, 0xc2097a41a0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7ff44c5eb100, 0xc2098aaba0, 0xc209a5b9a0, 0xc, 0xc, 0xc, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7ff44c5eb100, 0xc2098aaba0, 0xc209a5b9a0, 0xc, 0xc, 0xc, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/hashicorp/yamux.(*Session).recvLoop(0xc20a354580, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/yamux/session.go:373 +0x10d
github.com/hashicorp/yamux.(*Session).recv(0xc20a354580)
	/usr/local/src/github.com/hashicorp/yamux/session.go:361 +0x28
created by github.com/hashicorp/yamux.newSession
	/usr/local/src/github.com/hashicorp/yamux/session.go:104 +0x499
goroutine 1969 [select]:
github.com/hashicorp/consul/consul.(*Server).blockingRPCOpt(0xc208066420, 0xc208d84730, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:391 +0x35a
github.com/hashicorp/consul/consul.(*Server).blockingRPC(0xc208066420, 0xc2089a8578, 0xc2085f9098, 0xc2080bd4e0, 0x3, 0x3, 0xc2082eec20, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/rpc.go:309 +0xdd
github.com/hashicorp/consul/consul.(*Health).ServiceNodes(0xc208046030, 0xc2089a8540, 0xc2085f9080, 0x0, 0x0)
	/usr/local/src/github.com/hashicorp/consul/consul/health_endpoint.go:97 +0x403
reflect.Value.call(0xa69160, 0xb14b90, 0x13, 0xba58c0, 0x4, 0xc2088b3db8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xa69160, 0xb14b90, 0x13, 0xc2088b3db8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080453c0, 0xc2080b46c0, 0xc20a00cc30, 0xc208132700, 0xc20a1d3660, 0xb15fa0, 0xc2089a8540, 0x16, 0x964f20, 0xc2085f9080, ...)
	/usr/local/go/src/net/rpc/server.go:382 +0x1f7
net/rpc.(*Server).ServeRequest(0xc2080b46c0, 0x7ff44c5f3720, 0xc20959a900, 0x0, 0x0)
```

**Comment by armon** [comment]
@artushin Looks like its coming from LMDB, hopefully this class of issue goes away with 0.6

**Comment by wwalker** [comment]
I'm seeing what appears to be this same failure on 2 servers in our environment.

Both times the server had been running less than 30 minutes.

**Comment by wwalker** [comment]
I've had two crashes now in less than an hour.  Both of them were while raft was making a snapshot:

    [wwalker@tst-mcontrol1 ~]$ sudo ls -ld --full-time /usr/local/consul/data/raft/snapshots/*.tmp
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:29:35.027083368 -0500 /usr/local/consul/data/raft/snapshots/213039-118337085-1443814174918.tmp
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:59:36.459527639 -0500 /usr/local/consul/data/raft/snapshots/213069-118379352-1443815976059.tmp
    [wwalker@tst-mcontrol1 ~]$ sudo ls -lrt --full-time /usr/local/consul/data/raft/snapshots/*.tmp/*
    -rw-r--r-- 1 consul consul       171 2015-10-02 14:29:35.027083368 -0500 /usr/local/consul/data/raft/snapshots/213039-118337085-1443814174918.tmp/meta.json
    -rw-r--r-- 1 consul consul 222814210 2015-10-02 14:33:02.204451806 -0500 /usr/local/consul/data/raft/snapshots/213039-118337085-1443814174918.tmp/state.bin
    -rw-r--r-- 1 consul consul       171 2015-10-02 14:59:36.459527639 -0500 /usr/local/consul/data/raft/snapshots/213069-118379352-1443815976059.tmp/meta.json
    -rw-r--r-- 1 consul consul 168624128 2015-10-02 15:01:35.615959200 -0500 /usr/local/consul/data/raft/snapshots/213069-118379352-1443815976059.tmp/state.bin
    [wwalker@tst-mcontrol1 ~]$ grep -B 1 0xb\  /var/log/consul
        2015/10/02 14:32:58 [WARN] agent: Check 'service:vault' is now critical
    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x1 addr=0x7fb062d6700c pc=0x408f29]
    --
        2015/10/02 15:01:32 [WARN] agent: Check 'service:ops-OrcDaemon' is now critical
    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x1 addr=0x7f6ec410b00a pc=0x408093]
    [wwalker@tst-mcontrol1 ~]$

**Comment by wwalker** [comment]
Interestingly it successfully creates every other snapshot:

    [wwalker@tst-mcontrol1 ~]$ sudo ls -lrtd --full-time /usr/local/consul/data/raft/snapshots/*                                              
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:29:35.027083368 -0500 /usr/local/consul/data/raft/snapshots/213039-118337085-1443814174918.tmp
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:51:25.448408795 -0500 /usr/local/consul/data/raft/snapshots/213069-118379352-1443815475164
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:59:36.459527639 -0500 /usr/local/consul/data/raft/snapshots/213069-118379352-1443815976059.tmp
    drwxr-xr-x 2 consul consul 4096 2015-10-02 14:59:40.483643651 -0500 /usr/local/consul/data/raft/snapshots/213071-118391259-1443815980162

**Comment by slackpad** [comment]
Once 0.6 is released we can close this out because we will have eliminated this code path entirely.

**Comment by ryanuber** [comment]
The unexpected signal error indicates that SIGSEGV was received while running C code, which in Consul's case could only be LMDB. Given that the path forward is to upgrade to avoid this class of issue, and that we don't have plans to dive into the C code to fix this, we can close this out now. The code in master should not exhibit this behavior at all. The RC releases can be tested, which are available [here](https://releases.hashicorp.com/consul/) in binary form. Please do let us know if you see this issue on 0.6+.
